### ISSUE TITLE
New build system in GAP 4.9 hardcodes library paths on Mac OS X

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-system/gap#2464] opened 2018-05-15 11:03 UTC
When I build GAP 4.9 on OS X, the library paths are hardcoded.  Since the usual Unix way is to make a package in a user directory, then move to a system directory, this behavior is broken for anyone who wants to install a shared copy of GAP on a Mac.  (There are so many reasons to avoid 'sudo make'!!)  It made building GAP 4.9 to embed in Gap.app tricky.  And I suspect that the hardcoded libraries may also be a problem for some other Unix systems such as like Linux.

### Observed behaviour
On OS X without a global gmp library, make GAP in one directory, such as ~/gap-4.9.1.  Rename the directory, or move the directory to a shared location such as /usr/local/lib/gap-4.9.1.  Running gap now failed with an error similar to:
`dyld: Library not loaded: /Users/russw/Downloads/gap-4.9.1/extern/install/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/russw/Downloads/gap/bin/x86_64-apple-darwin16.7.0-default64/gap
  Reason: image not found
Abort trap: 6`

The same issue arises with the Browse, Edim, and gauss packages, which also use gmp.  A similar issue arises with the semigroups package (but with a different library).

It's possible to fix the issue after build using the install_name_tool, using the following command line:
`install_name_tool -change /Users/russw/Downloads/gap-4.9.1/extern/install/gmp/lib/libgmp.10.dylib @executable_path/extern/install/gmp/lib/libgmp.10.dylib gap`

Then one must also run a similar command on Browse, Edim, gauss, and an analogous command on semigroups.  Probably it is better to fix at build time.

I did some research on the issue.  Here are two related articles.  The first is a clear and high-level overview.  The second has more technical examples.
https://wincent.com/wiki/@executable_path,_@load_path_and_@rpath
http://matthew-brett.github.io/docosx/mac_runtime_link.html

It seems very likely to me that a similar problem arises on linux.

I'm not sure of the best way to patch.  Maybe GMP_LDFLAGS should be set to @executable_path/extern/install/gmp/lib/libgmp.la instead of ${abs_builddir}/extern/install/gmp/lib/libgmp.la in the GNUmakefile??

### Expected behaviour
GAP should load, no matter where the gap folder is moved to.

### Copy and paste GAP banner (to tell us about your setup)
 ┌───────┐   GAP 4.9.1 of 05-May-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin16.7.0-default64

**Comment by fingolfin** [comment] 2018-05-15 23:09
I don't see a bug here -- this works as designed: you are supposed to either install e.g. GMP globally on your system, and link against that; or else you can use the fallback we provide, for a GMP usable locally in your build directory.

Building a *relocteable* library is highly non-portable, and was never explicitly supported by GAP, although in the past we may have linked against libgmp.a instead of the shared library, so this was not immediately noticeable. But now various packages also need GMP, and thus linking against it statically is not pragmatic anymore.

Indeed, it is not true at all that "the usual Unix way is to make a package in a user directory, then move to a system directory". Usually, the installation requires extra steps, e.g. to relink shared libraries. My plan is to eventually provide something like this via `make install`, hopefully in GAP 4.10. But let me stress again that we never provided such a functionality in the past.

I don't know what you mean with `sudo make` -- this sounds like something which is useless at best, dangerous at worst.

If you want to relocate the GAP binary, I recommend that you either static link it against GMP (if you want to use GAP's version of GMP, you'll have to patch `Makefile.rules` to pass `--disable-shared --enable-static` or so to GMP's `configure` script).
Or you need to manually patch the rpath of the `.dylib`. This can indeed be done using `install_name_tool` -- I wrote a script doing that in a comfortable way for my GAP OS X dmg distro, you can find it here: https://github.com/fingolfin/gap-osx-bundle/blob/master/fix_install_names.sh

But this only works if one uses an .app bundle, which GAP does not do (I know your GUI wrapper for it does, but it's not useful for GAP in general).

**Comment by RussWoodroofe** [comment] 2018-05-18 14:06
@fingolfin, I'm happy to talk about packaging GAP and packages.  I aim to be easy to work with, and hope that my tone didn't come across as otherwise in text.  I'll send you an email separately.

As far as libraries go, I see two issues:

1.  A user reasonably expects that if s/he moves a folder, then everything in it works the same way.  (Particularly on a Mac.)  This currently fails.
2.  For a user or system administrator on Linux (or Mac, or ...) who wants to install a system copy of GAP in /usr/local/lib, it's actually not clear to me how s/he should proceed.  The usual procedure would be "./configure; make; make install".  GAP doesn't support make install at the moment, however.  This is not addressed by INSTALL.md.

Since make install doesn't work, and since it looks to me that there might be problems in getting it to work with packages, it looks to me that fixing the library load, at least on major platforms like Linux, Mac, would be worthwhile.  Moreover, since gap is already sensitive to the location of its binary (determines the GAP root from it), the usual argument against relative library paths on Linux doesn't apply.

But maybe I'm missing something?

**Comment by RussWoodroofe** [comment] 2018-05-18 14:17
It looks to me like adding "-Wl,-R,'$$ORIGIN', then specifying library paths relative to GAP root would do the needed on most Unix-like platforms.  The following article is somewhat helpful:
https://web.archive.org/web/20130915172134/http://itee.uq.edu.au/~daniel/using_origin/

On macOS, a somewhat different approach is needed, as you know.  Specifying library paths relative to @executable_path at build time would handle most current cases, but might cause trouble if any packages use an executable that loads a library.  I guess it would be most correct to set rpath, and go relative to @rpath.

**Comment by RussWoodroofe** [comment] 2018-05-21 12:00
I spent some more time looking at it, and see that libtool doesn't support building libraries with relative paths.  So while I disagree that there's no bug, I agree that it's too hard and out-of-scope to fix the bug-or-no-bug in the general case.  This is too bad, as otherwise creating a "make install" would be much easier!

But I will record here a fairly robust way of fixing the problem on OS X, simpler than running `install_name_tool -change` on all build products.  I'll understand if you'd rather not complicate the GNUmakefile.

Specifically, after building gmp, issue the command
`install_name_tool -id @rpath/extern/install/gmp/lib/libgmp.10.dylib extern/install/gmp/lib/libgmp.10.dylib'
  Then, after building the gap executable, issue the command
`install_name_tool -add_rpath @executable_path gap`
(alternatively, add `-rpath @executable_path` to the arguments when linking).

The first command tells all executables and libraries loading libgmp to load it relative to an rpath specified in the executable.  The 2nd command specifies this rpath.

For someone building on a vanilla OS X install, this will fix it so that packages will find libgmp correctly, with no additional steps required.  All included packages then build correctly, with the sole exception of the semigroups package.  (And the problem with the semigroups package is easy to fix by marking libsemigroups as a convenience library, which would be a sensible thing to do anyway.)  Of course, if additional external libraries are included, then a similar fix applies to each library.

It would be better if it were possible to tell libtool to issue the 1st install_name_tool as a postprocessing step to building a library.  (But I didn't figure out how to do that.)

**Comment by james-d-mitchell** [comment] 2018-05-21 12:35
@RussWoodroofe could you possibly raise an issue on the Semigroups package issue tracker indicating what the problem is with building it, and also perhaps indicating your suggested fix? This would be really helpful:

https://github.com/gap-packages/Semigroups/issues

**Comment by james-d-mitchell** [comment] 2018-05-21 13:30
@RussWoodroofe great thanks

**Comment by fingolfin** [comment] 2019-03-26 17:03
Closing this, as the code works as designed, and we no intention to implement support for (necessarily non-portable!) modifying the GMP build system to produce arbitrary reloctable binaries. Nor is this necessary for `make install`.

**Closed by fingolfin** 2019-03-26 17:03 UTC
Labels: os: macos, topic: build system
