### ISSUE TITLE
Document bootstrapping

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#5] opened 2015-03-02 16:01 UTC
Document how to make a checked out copy of the GAP repository even usable. It requires downloading of a selection of packaes, at the very least GAPDoc.

Using a symlink to a directory outside of the GAP tree is probably more suited for GAP development.

**Comment by alex-konovalov** [comment] 2015-03-02 17:06
Yes. Some initial text is already at [How to obtain GAP?](https://github.com/gap-system/gap/blob/master/README.md) of README.md, one could start from revising what's there.

**Comment by alex-konovalov** [comment] 2015-03-02 17:42
Another topic that should be covered here is (optionally) building GAP manuals by calling `make manuals` in the GAP root directory (some links may be unresolved if GAP packages referenced from the main manual are missing).

**Comment by fingolfin** [comment] 2015-03-04 16:02
"A selection of packages"? I am pretty sure only GAPDoc is required (and I am somewhat unhappy about this state).

Other than that, here is how I just bootstrapped:
```
git clone https://github.com/gap-system/gap gap.github
cd gap.github
./configure --with-gmp=system   # yes, I always use my own GMP
make -j8
mkdir -p pkg
cd pkg
ln -s /path/to/GAPDoc-1.5.1
cd ..
./bin/gap.sh
``

**Comment by markuspf** [comment] 2015-03-04 16:06
What makes you "somewhat unhappy"? The fact that GAPDoc is required, or that it is not part of the GAP repository itself?

Even documenting that it is a good idea to keep a package tree outside of the GAP source tree, and symlinking it to the GAP source tree is something I'd like to see happen...

**Comment by fingolfin** [comment] 2015-03-04 16:17
What bothers me is that it is required and not part of GAP. We should IMHO require it if and only if we ship it -- see issue #10.

As to documenting that having an external package tree is probably a good idea: Sure, all for that, but I think its easier to get people started if we don't need to tell them about packages and package trees before they even managed to bootstrap GAP :). And of course we should also make it easier to run with external pkg trees (I'll open more issues on that).

**Comment by alex-konovalov** [comment] 2015-03-04 20:35
@fingolfin : just to tell where the wording "selection of packages" comes from:

1) There is GAPDoc which is required to start GAP

2) There are calls to `LoadPackages` in the library (autpgrp, factint, tomblib). They are accompanied with checks whether the package ls loadable, but having them missing may cause diffs in regression tests.

3) There are calls to `LoadPackages` in the test files from `tst`(autpgrp, anupq, crisp, cvec, ctbllib, grpconst, tomlib). Some of them are exercised there heavily, like e.g. grpconst while some of them only needed to construct a test case. If some of them are missing, you will see diffs in regression tests, especially in the bugfix.tst. 

In our regression tests, we test GAP with a composite archive of all currently redistributed packages and their updates waiting in the queue for the next release, so this does not cause essential problems, but surely this would cause a lot of confusion to contributors which will be observing diffs not caused by their changes.

This is something to keep in mind to clean the `tst` directory and establish a set of recommended tests classified into at least three grades:
- for contributors to check on their machines without extra surprises;
- for travis to be used for continuos integration (constrained by runtime and test output to keep the travis job alive);
- most comprehensive Jenkins tests for release candidates.

**Comment by alex-konovalov** [comment] 2015-03-04 21:33
Having package development versions sitting in the main development repositories prior to GAP 4.5 release caused many difficulties, and that's exactly what we aimed to avoid migrating from CVS to Mercurial with the GAP 4.5 release. 

Perhaps bootstrapping could be addressed at a different level, with update/package manager, which could check at startup whether the version of GAP and packages is the latest one and suggest their downloading and installing. A first prototype could do this for GAPDoc only. Perhaps we may create a new issue for this idea and discuss further specification. E.g. one could point to the version of package to download, in case the stable release and development version of GAP require different ones, etc...

**Comment by alex-konovalov** [comment] 2015-04-08 22:42
Shall we close this issue now? It looks to me that it's largely duplicated by issue #10.

**Closed** 2015-04-10 11:04 UTC
