### ISSUE TITLE
Poll for future of StructureDescription

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#979] opened 2016-12-04 23:08 UTC
Sorry if this is not the correct way to ask these questions, but I already sent a message early this year to gap@gap-system.org, and nobody commented, so maybe this catches more interest. 

The main question is what do people expect when they call ````StructureDescription````? What would they want to see? 

What currently happens in the master branch is almost what is in the manual for stable: 
1. abelian groups (force abelian check) are decomposed as product of cyclic groups in elementary divisors style, then
2. a finiteness check is forced just to make sure we are not dealing with infinite groups, then 
3. check for alternating, symmetric, dihedral, quaternion, quasidihedral, PSL, SL, GL groups, then 
4. checking for simple groups, then 
5. factorize into direct product and call recursively on the factors, then 
6. factorize into semidirect products and call recursively on the factors (without the option "nice" it stops at the first decomposition found, with the option "nice" it checks _all_ semidirect decompositions and chooses one according to some guidelines listed in the manual). If no semidirect decomposition exists then
7. write G as Z(G).G/Z(G)=G'.G/G', or if both Z(G)=1 and G=G', then
8. write G as Phi(G).G/Phi(G), or if even Phi(G)=1, then
9. find G in the perfect group library, or if it cannot be found there, then return some text saying that.

Some arguments were already made that maybe for p-groups this is not the best way to describe the group. Of course for solvable groups one could always call (in theory) some commands explaining the polycyclic series of the group, which is kind of a description, as well. Maybe there already is a command displaying such information, and we could print it before/after the currect description?

Anyway, any thoughts on the matter? 

As a follow-up question, I would be interested in the coding style. The above code is one method installed for all groups, no method selection is applied, actually all the above checks are forced in the particular order I just described. Now, this code could be split into several smaller methods (for finite, abelian, simple, perfect, etc groups) with appropriate redispatches as @hulpke suggested in #968. I am unsure, though, if the code would be more or less understandable that way, and I am not sure if there is any point because there are no other existing methods (except for nice monomorphisms, which is indeed called earlier if ````IsHandledByNiceMonomorphism```` is true). I would be happy to cut it up, though, if that way it would be faster or the community prefers that rather than what it is currently. 

Update: I stand corrected, I found that some packages have methods installed for ````StructureDescription````.

**Comment by markuspf** [comment] 2016-12-05 10:57
My random thoughts on this this morning were as follows (this is my opinion):

For me the current output of `StructureDescription(G)` is of very little value (and the documentation even admits to that). If I know a group is "(C5 x C5) : C4" that is all fine and well, but I don't even know how that `C4` in the semidirect product (is it a semidirect product?) acts. Radom case in point:

```
gap> StructureDescription(SmallGroup(100,11));
"(C5 x C5) : C4"
gap> StructureDescription(SmallGroup(100,10));
"(C5 x C5) : C4"
```
I don't know the `StructureDescription` code, but I  would think that much more useful information is computed in it, like for example the action homomorphism of that `C4` on `C5 x C5`.

What I'd really like is something that is probably akin to the group recognition code: If we know the structure of the group, why not make it into a GAP object, possibly together with an isomorphism from (or to) my original group? Is this much more expensive to do? So as a starting point, I'd want GAP to give me the following(-ish)

```
gap> G := Group(GeneratorsOfGroup(Range(IsomorphismPermGroup(SmallGroup(100,11)))));
<permutation group with 4 generators>
gap> StructureDescription(G);
SemidirectProduct(DirectProduct(CyclicGroup(5), CyclicGroup(5)), CyclicGroup(4),...)
```

Along with this information one can always still give a string that give a "high level" overview of the structure.

Maybe this is deemed too complicated, or veering too much into the group recognition code, in particular the documentation of `StructureDescription` claims it is an educational tool rather than a research tool. I might interject and say that it gives the false impressions about problems in CGT, for instance that there is far more than one isomorphic copy of `CyclicGroup(5)` around, and actually finding it inside a heap of permutations might not even be entirely trivial, so I think making more information available would make it a *better* educational tool, and maybe a useful research tool, too.

**Comment by hungaborhorvath** [comment] 2016-12-05 13:48
@markuspf Thank you for your thoughts. Currently there exists an undocumented command called ````DecompositionTypes````, which does something _similar_, but you would still not get the actions. The actions are currently not computed at all, but can be computed with a bit of work on my part. I will take a note of it, thanks.

Just a question: how would you want a description for a group that is not a direct- or semidirect product? That is, how would you want e.g. an G'.G/G' extension to be described (if at all)?

**Comment by markuspf** [comment] 2016-12-05 13:56
I think, if it can be (or is) computed (reasonably cheaply?), it should be returned.

If it can't, one returns whatever one can return or has computed. My memory on group extensions is really quite fuzzy unfortunately. 

How difficult would it be to compute the short exact sequence? I should really look at how structure description works before I comment further ;).

**Comment by markuspf** [comment] 2016-12-05 14:07
Another thought (that somewhat contradicts what I said earlier) is of course that, if one can *detect* a group to be a semidirect product without computing the action, it is (also educationally) useful to say that (and provide this functionality).

**Comment by hungaborhorvath** [comment] 2016-12-05 14:09
@markuspf No, you should not (feel the need to). :). Te whole point of this issue is what people would _prefer_ instead of what exists currently.

So what you are saying with short exact sequences is that maybe have some chain of subgroups with morphisms between them and possibly some isomorphisms from these subgroups (or their factors) to building blocks? Is it not what ````ChiefSeries```` already does? With direct factors and semidirect factors I see how your proposed idea would work nicely as all factors are subgroups, as well. With non-split extensions I am not so sure. 

As for semidirect products, the function exists already, it is just not yet documented into the manual. Try ````SemidirectDecompositions````. I always wanted to add a function computing the action (it is three lines basically), so now I have the excuse to do so. :)

**Comment by fingolfin** [comment] 2016-12-05 19:34
First off: A "poll" here has no binding value; writing to the mailing list was and is the right approach for this.

As to why there were no replies to your email: I can only guess that many people felt like me: I simply have no wishes in regards to `StructureDescription`. It's a little tool which can give some quick & dirty help during debugging, or in very simple cases. But for my actual research work, and for actual algorithms, it is completly useless, by design (i.e. that's not a crictiscm of it; I am simply saying that it was not made nor meant for anything else).

For real structural work, there is group recognition, as @markuspf hints at, and I don't think `StructureDescription` could (nor should) compete with that.

**Comment by hulpke** [comment] 2016-12-07 17:15
Since there is an explicit question:

<rant>
I think `StructureDescription`, as a function for arbitrary groups, is a fundamentally flawed concept. One can make this work for a fixed set of particular examples, but offering such a function actually betrays a serious misunderstanding of what a ``typical group'' is. (Admittedly, a lot of undergraduate textbooks run in the same trap, and Analysis spends a lot of time getting students to understand that a "function" is not just (exp(sin(t-1))^2.   )

When working with users of GAP, misuse of this function ("I have this group of order 17^25, but `StructureDescription` does not terminate") is one of the more frequent traps. (To be frank: If there was one function I was given the option to remove from GAP, it would be `StructureDescription`)

What `StructureDescription` mixes up are at least three kinds of functionality that ought to be separated:

1) Does the group happen to be a particular group from a given pool (say small order, geometrically nice, a given name known in the literature)? This is basically testing for a fixes set of properties, and should be happy to give up in most cases. It might look cute to have a function that identifies a permutation group of degree 100 as HS:2, but I think it has actually minimal benefit.

2) Can the group be written as a product of smaller groups, and if so how? This is useful functionality but probably would need more information than "split", maybe an isomorphism to a formal product structure. Part of this overlaps with recognition, where we want to decomposition to be geometrically nice.

3) A function that tries to build a "human-readable" presentation for a given group: Try to use product structure, name generators coming from different parts appropriately. Do not split elements of composite order into p-order relative orders, unless this is unavoidable. It probably would be fed a decomposition (coming from concept 2) to avoid having to make a choice, and would not aim to produce anything unique, it also might indicate in which way certain actions are ``outer''.
However thinking about it this looks to me still a task that is more for a human than for a computer.

</rant>

**Comment by Stefan-Kohl** [comment] 2017-02-01 11:28
@hulpke `StructureDescription' is actually used quite a lot -- e.g. there are presently [65 posts on MathStackExchange which mention it](http://math.stackexchange.com/search?tab=relevance&pagesize=50&q=structuredescription) -- and a Google search of course yields a lot more elsewhere on the internet, and a couple of instances even in printed books. Even though it cannot be ideal in any way, I'd say it definitely is useful in practice.

**Comment by alex-konovalov** [comment] 2017-02-01 23:51
At least the manual does says that it describes it "to some extent" and "is intended primarily for small groups (order less than 100) or groups with few normal subgroups" and can be expensive in other cases,  and also that the string is often not the most useful way to describe a group.

**Comment by fingolfin** [comment] 2024-01-10 00:26
I don't think this will lead anywhere these days, so closing.

**Closed by fingolfin** 2024-01-10 00:26 UTC
Labels: kind: discussion
