### ISSUE TITLE
`make cygwin` target is confusing

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#346] opened 2015-11-08 09:29 UTC
On windows, I can run the traditional:

`./configure; make`, and get a working GAP. However, that resulting copy won't let me build any packages (for example IO(

I can run `./configure; make cygwin`, and also get a working GAP, which does let me build packages.

I'm guessing there is no reason for anyone to run plain `make` on windows, and we should just make `make` do `make cygwin` (and leave `make cygwin` in, just for backwards compatibility). Is that true?

**Comment by hungaborhorvath** [comment] 2015-11-08 09:38
I also had this problem with compiling the io package on windows, and this was the final push for me to migrate to linux. 

Whatever decision will be made on this, I think it should be properly documented at some easily accessible place. I remember that I  was very frustrated that I did not find any information about this even though I was looking for hours. I did not find "make cygwin" anywhere. Further, the README file was even misleading, because it was referencing files that did not exist, like gap.bat... This almost made me stop trying to contribute to GAP completely.

**Comment by ChrisJefferson** [comment] 2015-11-08 09:41
Looking harder at `make cygwin`, it's worse that I suspected, as it is mixing up make sure we get a working package, with (I assume) preparing for making a distributed release, copying a whole bunch of cygwin-related files into GAP's bin directory.

**Comment by alex-konovalov** [comment] 2015-11-08 09:45
I thought that `make` is to be used in Cygwin if you want to run GAP from Cygwin shell, and expect that packages should be compilable in this scenario. OTOH, `make cygwin` builds GAP to be started using `gap.bat` and if you built it this way, you may (perhaps - could you check?) lose the ability to start it from Cygin shell.

**Comment by ChrisJefferson** [comment] 2015-11-08 09:47
@alex-konovalov : Yep, after `make cygwin` you can't run from the cygwin shell anymore (slightly weird naming there...). However, it seems that many packages also won't build after a `make`

**Comment by alex-konovalov** [comment] 2015-11-08 09:53
@ChrisJefferson: so we need to keep both `make` and `make cygwin` (could be renamed to `make windows` if this will sound less confusing). 

FYI, below is a fragment from the script to build GAP distribution for Windows - this works. Are packages from this list also failing to build? Maybe you're trying to build packages which never were expected to work under Windows?

```
./configure
make cygwin

# BUILDING PACKAGES
cd pkg/Browse
./configure
make
cd ..
cd io-*
./configure
make
cd ..
cd cvec-*
./configure
make
cd ..
cd edim
./configure
make
cd ..
cd orb-*
./configure
make
cd ../..
# END OF BUILDING PACKAGES
```

**Comment by ChrisJefferson** [comment] 2015-11-08 09:54
@alex-konovalov , that does work fine. But if you just run `make` instead of `make cygwin`, then it doesn't work.

**Comment by alex-konovalov** [comment] 2015-11-08 09:56
@ChrisJefferson yes, that was exactly my question. I think this should be fixed and one should be able to build packages both with `make` and `make cygwin`. Do you have an example of what exactly happens?

**Comment by ChrisJefferson** [comment] 2015-11-08 10:04
Building IO:
```
$ make
  CC       src/io_la-io.lo
  CCLD     io.la
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/../../../../x86_64-pc-cygwin/bin/ld: cannot find /home/caj/gap/bin/x86_64-unknown-cygwin-gcc-default64/gap.dll: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:455: recipe for target 'io.la' failed
make: *** [io.la] Error 1
```

cvec:
```
$ make
  CC       src/cvec_la-cvec.lo
  CCLD     cvec.la
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/../../../../x86_64-pc-cygwin/bin/ld: cannot find /home/caj/gap/bin/x86_64-unknown-cygwin-gcc-default64/gap.dll: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:455: recipe for target 'cvec.la' failed
make: *** [cvec.la] Error 1
```

edim looks different
```
if test ! -d bin;  then mkdir bin;  fi
if test ! -d bin/x86_64-unknown-cygwin-gcc-default64;  then mkdir -p bin/x86_64-unknown-cygwin-gcc-default64;  fi
../../bin/x86_64-unknown-cygwin-gcc-default64/gac -d -o bin/x86_64-unknown-cygwin-gcc-default64/ediv.so src/ediv.c
gcc -fPIC -Wall -O2 -I/home/caj/gap/bin/x86_64-unknown-cygwin-gcc-default64/extern/gmp/include -o /tmp/gac4236/4236_ediv.o -I/home/caj/gap/bin/x86_64-unknown-cygwin-gcc-default64/../.. -I/home/caj/gap/bin/x86_64-unknown-cygwin-gcc-default64 -DCONFIG_H -c src/ediv.c
src/ediv.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /***************************************************************************
 ^
gcc -shared -g -o bin/x86_64-unknown-cygwin-gcc-default64/ediv.so /tmp/gac4236/4236_ediv.o
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x9d): undefined reference to `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x9d): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x12e): undefined reference to `ModInt'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x12e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ModInt'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x1c6): undefined reference to `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x1c6): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x1e8): undefined reference to `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x1e8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x202): undefined reference to `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x202): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x21c): undefined reference to `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x21c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `NewBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x7b5): undefined reference to `RetypeBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x7b5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `RetypeBag'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x7cc): undefined reference to `InitGVarFuncsFromTable'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x7cc): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `InitGVarFuncsFromTable'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x7ec): undefined reference to `InitHdlrFuncsFromTable'
/tmp/gac4236/4236_ediv.o:ediv.c:(.text+0x7ec): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `InitHdlrFuncsFromTable'
/tmp/gac4236/4236_ediv.o:ediv.c:(.rdata$.refptr.Fail[.refptr.Fail]+0x0): undefined reference to `Fail'
/tmp/gac4236/4236_ediv.o:ediv.c:(.rdata$.refptr.False[.refptr.False]+0x0): undefined reference to `False'
/tmp/gac4236/4236_ediv.o:ediv.c:(.rdata$.refptr.True[.refptr.True]+0x0): undefined reference to `True'
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'bin/x86_64-unknown-cygwin-gcc-default64/ediv.so' failed
make: *** [bin/x86_64-unknown-cygwin-gcc-default64/ediv.so] Error 1
```

**Comment by alex-konovalov** [comment] 2015-11-08 15:02
Thanks. I can reproduce this e.g. for IO package on the VM where we build GAP distribution for Windows. I am not sure at the moment if this is a problem in the core system or in the package or in both... I presume, packages with stand-alone binaries like grape or kbmag could be built, and this affects only those with kernel modules?

**Comment by ChrisJefferson** [comment] 2015-11-08 15:46
My feeling is that we shouldn't have two ways of building (building a DLL and a single executable), as Windows already doesn't get enough love. However, I don't know if there is a good historical reason for having two methods of building.

**Comment by alex-konovalov** [comment] 2015-11-08 18:01
My version of events leading to this (IIRC) is that formerly the process contained three steps `./configure; make; make cygwin`, then when a DLL version was introduced, it was reduced to two-step `./configure; make cygwin`.

It's convenient to have both options available in our regression tests and release workflow, where we do test both ways of building GAP in cygwin:
* with `make` in the test which compiles GAP with `-Werror` option and fails if there are compiler warning. That test also called `gap.sh -r -A tst/testinstall.g` and was running 100% fine until last Friday Oct 30th inclusive. Problems there appeared after the recent merge of `dir.tst` (though I think they existed there before, and only became exposed by that merge).
* with `make cygwin` in the other tests.

Thus, as you see, though we somehow test `make` version, it gets less attention than `make cygwin` one. Perhaps the outcome of this issue should be not changing anything in the build system, but document `make cygwin` in the `INSTALL` file (may now be converted to `INSTALL.md` in Markdown format) and other documentation for developers. We know that packages with stand-alone binaries also may work when GAP is started with `gap.bat` under Windows (Grape is an example), so is a way to get working system with both kernel modules and standalone binaries.

**Comment by alex-konovalov** [comment] 2015-11-17 22:53
This is cleaned up by @ChrisJefferson in #349. As soon as that PR will be merged, this issue may be closed.

**Comment by alex-konovalov** [comment] 2015-11-20 20:30
Closing this now, since #349 is merged.

**Closed by alex-konovalov** 2015-11-20 20:30 UTC
