### ISSUE TITLE
Lack of clear error message in helpsys.tst with missing manuals

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#443] opened 2016-01-10 19:30 UTC
In current master. As far as I can see the problem is in chapter 2 of the changes manual. I'm not sure whether its a problem in the markup of the manual or in GAPDOC (or even something underlying).

    gap> Test("~/GIT/gap/tst/teststandard/helpsys.tst");
    ########> Diff in ~/GIT/gap/tst/teststandard/helpsys.tst, line 24:
    # Input is:
    for i in [1..Length(HELP_LAST.TOPICS)] do HELP(String(i)); od; 
    # Expected output:
    # But found:
    Error, no method found! For debugging hints type ?Recovery from NoMethodFound
    Error, no 1st choice method found for `+' on 2 arguments 
    ########

The error comes from a failed `PositionSublist` search for a terminator while rewriting some bit of markup.

**Comment by alex-konovalov** [comment] 2016-01-10 19:36
I am almost 100% sure that this is just a signal that manuals are not built and this will disappear after `make manuals`.

Perhaps there should be a way to detect this e.g. with `IsExistingFile` and produce a clear error message.

**Comment by stevelinton** [comment] 2016-01-10 20:02
Yes. Thanks. I'll leave the issue for a bit to see if anyone can see a nice way to make this clearer.

**Comment by alex-konovalov** [comment] 2016-01-10 20:15
Thanks - I've renamed it to describe the actual problem.

**Comment by alex-konovalov** [comment] 2016-01-14 16:22
I have no better idea then checking for 
```
IsExistingFile( Filename( DirectoriesLibrary("doc")[1], "ref/chap0.html" ) );
```
(and similarly for `tut` and `changes` directories returning `true` and producing a meaningful message otherwise. 

Of course, this is not testing whether the version of the manual that is there is actually the one that builds from the current working state, but `helpsys.tst` doesn't do it either. It just checks that every manual section is loadable (but in our regression tests, we always start from a clean workspace and build manuals). 

If no one suggests anything better, I will submit a PR.

**Comment by frankluebeck** [comment] 2016-01-14 16:43
Can you describe which problem you are trying to solve here?

When I clone the current master branch, call configure and make, create `pkg` and clone a copy of GAPDoc, then this installation of GAP starts without problems.
Now I get:
```
gap> Test("tst/teststandard/helpsys.tst");
########> Diff in tst/teststandard/helpsys.tst, line 23:
# Input is:
HELP(":?");
# Expected output:
# But found:
Help: no matching entry found
########
helpsys.tst
GAP4stones: 108944000
false
```
This is fine because there is no help section at all.
When I now compile the manual of that clone of GAPDoc I get:
```
gap> Test("tst/teststandard/helpsys.tst");
helpsys.tst
GAP4stones: 198513
true
```
(although none of the main manuals is available).

So, I cannot reproduce the problem reported in the first message of this thread.

**Comment by alex-konovalov** [comment] 2016-01-14 20:11
@frankluebeck thanks for checking - I think now that even though the problem described by @stevelinton disappeared after rebuilding the manuals, that was not necessarily the case of the missing manual. 

Today I've incidentally hit a similar problem in the setting when Jenkins test was trying current master branch with freshly picked up package updates and was surprised to see this:
```
gap> Test("tst/teststandard/helpsys.tst");
########> Diff in tst/teststandard/helpsys.tst, line 24:
# Input is:
for i in [1..Length(HELP_LAST.TOPICS)] do HELP(String(i)); od;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `PositionStream' on 1 arguments
########
helpsys.tst
GAP4stones: 4699
false
```
Nevertheless, my suggestion would not spot anything wrong here:
```
gap> IsExistingFile( Filename( DirectoriesLibrary("doc")[1], "ref/chap0.html" ) );
true
gap> IsExistingFile( Filename( DirectoriesLibrary("doc")[1], "tut/chap0.html" ) );
true
gap> IsExistingFile( Filename( DirectoriesLibrary("doc")[1], "changes/chap0.html" ) );
true
```
Rerunning this and looking at the break loop, I had a suspicion that this is the new version of cohomolo package, which failed to build in this particular installation. I am looking at this further...

**Comment by alex-konovalov** [comment] 2016-01-14 21:15
Debugging this further:

* recreate the test environment:
```
gap> START_TEST("helpsys.tst");
gap> SetUserPreference("Browse", "SelectHelpMatches", false); # needed only for compatibility with the Browse package
gap> SetHelpViewer("screen");;
gap> savepagerprefs:=UserPreference("Pager");;
gap> SetUserPreference("Pager",0);
gap> savepager:=PAGER_EXTERNAL;;
gap> MakeReadWriteGlobal("PAGER_EXTERNAL");
gap> PAGER_EXTERNAL:=function(lines)end;
function( lines ) ... end
gap> HELP(":?");
```
* now wait for the trouble:
```
gap> for i in [1..Length(HELP_LAST.TOPICS)] do HELP(String(i)); od;
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `PositionStream' on 1 arguments called from
PositionStream( stream 
 ) at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/lib/helpde\
f.gi:310 called from
HELP_CHAPTER_INFO( book, chapter 
 ) at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/lib/helpt2\
t.gi:220 called from
HELP_PRINT_SECTION_TEXT( info, chnr, secnr 
 ) at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/lib/helpde\
f.gi:675 called from
HELP_BOOK_HANDLER.(book.handler).HelpData( book, entrynr, type 
 ) at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/lib/helpba\
se.gi:807 called from
HELP_PRINT_MATCH( HELP_LAST.TOPICS[nr] 
 ); at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/lib/helpb\
ase.gi:1047 called from
...  at line 10 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```
* why cohomology package is relevant:
```
brk> HELP_LAST.TOPICS[nr];
[ rec( bookname := "cohomolo (not loaded)", chappos := [  ], chapters := [ "Cohomology" ], 
      directories := dir("/home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master\
-snapshot/pkg/cohomolo-1.6.1/doc/"), entries := [ [ "CHR", "chr", "S", 1, 1 ], [ "SchurMultiplier", "schurmultiplier", "S", 1, 2 ], 
          [ "CoveringGroup", "coveringgroup", "S", 1, 3 ], [ "FirstCohomologyDimension", "firstcohomologydimension", "S", 1, 4 ], 
          [ "SecondCohomologyDimension", "secondcohomologydimension", "S", 1, 5 ], [ "SplitExtensionCHR", "splitextensionchr", "S", 1, 6 ], 
          [ "NonsplitExtension", "nonsplitextension", "S", 1, 7 ], [ "CalcPres", "calcpres", "S", 1, 8 ], [ "PermRep", "permrep", "S", 1, 9 ], 
          [ "Further Information", "further information", "S", 1, 10 ], [ "Cohomology", "cohomology", "C", 1, 0 ], [ "Cohomology!", "cohomology", "I", 1, 0 ], 
          [ "CHR", "chr", "F", 1, 1 ], [ "SchurMultiplier", "schurmultiplier", "F", 1, 2 ], [ "CoveringGroup", "coveringgroup", "F", 1, 3 ], 
          [ "FirstCohomologyDimension", "firstcohomologydimension", "F", 1, 4 ], [ "SecondCohomologyDimension", "secondcohomologydimension", "F", 1, 5 ], 
          [ "SplitExtensionCHR", "splitextensionchr", "F", 1, 6 ], [ "NonsplitExtension", "nonsplitextension", "F", 1, 7 ], [ "CalcPres", "calcpres", "F", 1, 8 ], 
          [ "PermRep", "permrep", "F", 1, 9 ] ], filenames := [ "cohomolo.tex" ], formats := [ "text", "url", "macurl" ], handler := "default", secposs := [  ], 
      sections := [ [ "CHR", "SchurMultiplier", "CoveringGroup", "FirstCohomologyDimension", "SecondCohomologyDimension", "SplitExtensionCHR", "NonsplitExtension", 
              "CalcPres", "PermRep", "Further Information" ] ] ), 1 ]
```
*  inspect some variables:
```
brk> ShowArguments();
[ fail ]
brk> stream;
fail
brk> filename;
"/home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/pkg/cohomolo-1.6.1/doc/cohomolo.tex"
brk> info.filenames[chapter];
"cohomolo.tex"
brk> info.directories;
dir("/home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/pkg/cohomo\
lo-1.6.1/doc/")
brk> StringStreamInputTextFile(filename);
fail
brk> 
```
* So here we are in this code from `HELP_CHAPTER_INFO` in `helpdef.gi`:
```
     filename := Filename( info.directories, info.filenames[chapter] );
        if filename = fail  then
            return fail;
        fi;
        stream := StringStreamInputTextFile(filename);
```
What happened is that `filename` is not `fail`, but `stream` equals to `fail`. Why this is happening? 

The manual says:

"If the first argument is a directory object dir, Filename returns the (system dependent) filename as a string for the file with name name in the directory dir. Filename returns the filename regardless of whether the directory contains a file with name name or not.

If the first argument is a list list-of-dirs (possibly of length 1) of directory objects, then Filename searches the directories in order, and returns the filename for the file name in the first directory which contains a file name or fail if no directory contains a file name."

Ok, so the 1st argument is
```
brk> info.directories;
dir("/home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snapshot/pkg/cohomo\
lo-1.6.1/doc/")
```
and this is not a **list** so the filename is returned regardless of whether the directory contains a file with name name or not.  `info.directories` sounds like it meant to be a list - it would be likely useful to add a check for this in `HELP_CHAPTER_INFO`. But why it is not a list in this case? Comparing PackageInfo.g file for cohomolo and e.g. ModIsom package which also used gapmacro.tex-based manual does not give any insights...

**Comment by alex-konovalov** [comment] 2016-01-14 21:28
My conjecture is that the `.directories` component is set up in `helpdef.gi` in `HELP_BOOK_HANDLER.default.ReadSix` here:
```
  res.directories := Directory(fname{[1..Length(fname)-10]}); 
```
(with some convention that the last 10 characters of `fname` are the filename?). So it never was a list. The only reason why this worked was that packages were providing original manual sources in .tex or, for those using GAPDoc, .tex files produced from the original .xml source. 

Because the .directories component is also used in `lib/helpt2t.gi`, I suggest to not to change it, but call
```
filename := Filename( [ info.directories ], info.filenames[chapter] );
```
in `HELP_CHAPTER_INFO` - in this case it will return `fail` if the file does not exist. Maybe it should also print a warning in this case.

**Comment by frankluebeck** [comment] 2016-01-14 22:35
@alex-konovalov: thanks for the analysis.

In your example the `doc` directory of `cohomolo` seems severely broken. There should only be a `manual.six` file if it contains valid information (maybe it is accidentally in the package repository, although it should only be produced when building the manual?). 

But I think it would be correct to change the line
```
    res.directories := Directory(fname{[1..Length(fname)-10]});
```
in `helpdef.gi` to 
```
    res.directories := [ Directory(fname{[1..Length(fname)-10]}) ];
```
After that change you will run into a  somewhat _nicer error_.

I could also propose a change to `helpt2t.gi` to avoid a break loop in this example, but maybe it is appropriate  to run into an error when a doc-directory is broken.

**Comment by alex-konovalov** [comment] 2016-01-14 22:58
@frankluebeck, the .six file is not there incidentally - this is the new release of cohomolo that @fingolfin made today (http://gap-packages.github.io/cohomolo/), and it has .pdf and .html versions of the manual. 

If it should be OK to make `res.directories` a list in the first instance, it's good. I was not sure about its other usage - thanks for the tip.

**Comment by frankluebeck** [comment] 2016-01-14 23:46
@alex-konovalov: no, there is a `manual.six` file in that `cohomolo` archive, but the file `cohomolo.tex` which is mentioned in the first line of `manual.six` is missing (and also `manual.tex` so that the `make_doc` script does not work).

**Comment by alex-konovalov** [comment] 2016-01-14 23:49
@frankluebeck yes - exactly what I've reported earlier at https://github.com/gap-packages/cohomolo/issues/2 and https://github.com/gap-packages/kbmag/issues/3. Sorry I forgot to mention this more explicitly here.

**Comment by alex-konovalov** [comment] 2016-01-15 12:51
Just for the record, after #461 the error is happening here:
```
gap> for i in [1..Length(HELP_LAST.TOPICS)] do HELP(String(i)); od;

Error, Function Calls: <func> must return a value in
  return HELP_PRINT_SECTION_TEXT( info, chnr, secnr )
 ; at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/6\
4build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snap\
shot/lib/helpdef.gi:675 called from 
HELP_BOOK_HANDLER.(book.handler).HelpData( book, entrynr, type 
 ) at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/6\
4build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-snap\
shot/lib/helpbase.gi:807 called from
HELP_PRINT_MATCH( HELP_LAST.TOPICS[nr] 
 ); at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/\
64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-sna\
pshot/lib/helpbase.gi:1047 called from
HELP_SHOW_FROM_LAST_TOPICS( Int( str ) 
 ); at /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktest/GAPCOPTS/\
64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update-master-sna\
pshot/lib/helpbase.gi:1228 called from
HELP( String( i ) )
```

**Comment by alex-konovalov** [comment] 2016-01-20 13:47
I suggest to close this for now, though similar "surprises" may still happen in the future.

**Closed** 2016-01-22 10:50 UTC
