### ISSUE TITLE
Make "./configure; make" suffice for installing GAP

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#794] opened 2016-05-16 13:35 UTC
Presently "./configure; make" compiles only the GAP kernel, such that packages which require additional installation steps like compiling C code remain unavailable. However these packages provide important functionality. As of now, in order to use this functionality one has to manually figure out and perform the installation procedure of each of these packages which one needs. 

To make GAP installation somewhat more contemporary, I think each package which needs installation steps other than mere extraction from the archive file should be required to provide a standardized installation procedure which is then called when doing "./configure; make" in the GAP root directory, and refer to it in its PackageInfo.g file.

(There is a script [InstPackages.sh](http://www.gap-system.org/Download/InstPackages.sh) which works for some packages on some machines and for others not, so certainly is not a solution to the problem. -- The script itself says: "Note, that this isn't and is not intended to be a sophisticated script. Even if it doesn't work completely automatically for you, you may get an idea what to do for a complete installation of GAP.").

**Comment by alex-konovalov** [comment] 2016-05-16 14:31
Just to give an update on this issue: things are actually going to improve in GAP 4.8.4. There is already the script https://github.com/gap-system/gap/blob/master/bin/BuildPackages.sh, which is used in all regression tests of the stable-4.8 and master branches. The latest issue related to that script is #737. So after GAP 4.8.4 `InstPackages.sh` will no longer be needed.

`bin/BuildPackages.sh` assumes `./configure; make` as default way of building packages, so if any new package that builds this way should be built seamlessly without any modifications of the build script. For older packages that do not comply with this procedure, it has several special cases.

The `bin/BuildPackages.sh` script will be included in the GAP distribution, so there will be no need to download it. One will have only to change to the `pkg` directory and call `../bin/BuildPackages.sh` from there.

**Comment by alex-konovalov** [comment] 2016-06-29 17:23
I suggest now to close this issue as GAP 4.8.4 is now out and installation instructions have been updated to suggest calling `bin/BuildPackages.sh`. The old `InstPackages.sh` script is available at its location, but the content has been changed: in will now fail with an error message explaining the changes. This is done in case it is used in some automated installations.

I agree that the feature request by @Stefan-Kohl asks for more, but at the moment we are not yet anywhere close to get there.

**Comment by Stefan-Kohl** [comment] 2016-06-29 20:41
I think the issue should only be closed once either the requested features have been implemented or the feature request has been declined. In particular I don't see any harm in leaving this issue open for a long time.

**Comment by fingolfin** [comment] 2019-02-13 22:33
I am not sure how exactly the request would be "declined", other than by us closing it? In any case, I am and always was against this approach. In my opinion, the only viable way to make it easy to install GAP and all GAP share packages is to provide precompiled binaries (in various forms and for as many platforms as possible), and have as many Linux distros as possible to package GAP, so that people can use `apt install gap`, `yum install gap` etc. etc. 

But building packages is an iffy and difficult problem, and hard to fully automate. Compilation of each individual package can fail for a plethora of reasons; at the same time, it's difficult for us to test if any given package was not yet compiled; was already successfully compiled cannot be compiled due to a permanent failure (like some dependency missing; note that of course this could change at any time without us knowing about it). This in turn means that it is next to impossible to have `make`  be idempotent -- instead, each time `make` is entered, we'd have to try to recompile all packages. Or use crude tricks (like touching a file to mark a package as compiled) that break quickly (e.g. because a file in the package was modified, so it should be recompiled; or because a previously missing dependency was reinstalled, etc.).

This is why `bin/BuildPackages.sh` is a separate script. We leave it up to the user to decide whether and when to (re)run it. If you want, you can now of course install GAP "in one step" by doing

    ./configure && make && cd pkg && ../bin/BuildPackages.sh

All in all, I think we should reject this feature request.

**Comment by ChrisJefferson** [comment] 2019-02-13 23:02
I agree. If in future we ended up in a state where we could clean, build and rebuild all packages, this would arise easily, but we can't do it for the foreseeable future.

**Closed** 2019-02-26 14:37 UTC
Labels: kind: enhancement, topic: build system, topic: packages
