### ISSUE TITLE
Error in testbugfix with fr loaded

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#3496] opened 2019-06-11 19:11 UTC
```
########> Diff in /home/gap/inst/gap-master/tst/testbugfix/2019-04-09-Lattice.\
tst:3
# Input is:
StructureDescription(g);;t:=TableOfMarks(g);;
# Expected output:
# But found:
Error, List Element: <list>[11] must have an assigned value
########
```

https://travis-ci.org/gap-infra/gap-docker-master-testsuite/builds/543426798
It also hangs `gap-master/tst/teststandard/twocohom.tst`

**Comment by ChrisJefferson** [comment] 2019-06-11 19:12
This only happens when rcwa is loaded

**Comment by ChrisJefferson** [comment] 2019-06-11 19:40
False alarm, it seems to be `fr`.

**Comment by ChrisJefferson** [comment] 2019-06-11 20:16
I tried tracing this, but didn't have any great success, I think the code just ends up taking a different route, due to slightly different priorities of various functions.

**Comment by ChrisJefferson** [comment] 2019-06-12 13:11
Pinging @hulpke , as I think this is related to a previous bug he fixed, maybe there is another way of triggering the same problem?

If you can't figure out what's going wrong when we load FR, I'm happy to take another pass at trying to figure out where the deviate in behaviour.

**Comment by alex-konovalov** [comment] 2019-06-12 18:00
There are also three more failures that I observe in Jenkins in the master branch when GAP started with `-r -A` options: it hangs forever on
-  `tst/teststandard/twocohom.tst`
- `tst/testextra/perfect.tst`
- testing manual examples from Chapter 47

**Comment by hulpke** [comment] 2019-06-15 15:38
@ChrisJefferson 
I have resolved the issues when it is hanging, alas I have been unable to reproduce the error when loading fr (and have no idea what the problem could be, just from the error message).

**Comment by alex-konovalov** [comment] 2019-06-15 16:43
@ChrisJefferson to add further details, @hulpke means #3494, which is still under review, and extract from it in #3501, which is also under review and requires one manual example update before it could be merged.

**Comment by ChrisJefferson** [comment] 2019-06-15 18:45
@hulpke : I tried starting from a blank directory and it seems to happen. I ran the following script and it got me to the break loop:

```
git clone --depth=1 https://www.github.com/gap-system/gap && cd gap && ./autogen.sh && ./configure && make bootstrap-pkg-full && make && (cd pkg/io* && ./configure && make) && echo 'LoadPackage("fr"); l:=AllSmallGroups(960,IsSolvableGroup,false);;g:=l[5];;StructureDescription(g);;' > input.g && ./gap input.g
```

produces the following (eventually).

```
Error, List Element: <list>[11] must have an assigned value in
  if H.translabels[img[i]] = depth then
    if mode = 'd' then
        return depth - 1;
    fi;
    e := RelativeOrders( pcgs )[depth - 1];
    i := img[i];
    repeat
        e := e - 1;
        i := i ^ gen;
    until H.translabels[i] <> depth;
    if mode = 'l' then
        return e;
    elif mode = 's' then
        return [ depth - 1, e ];
    fi;
    exp[depth - mindepth] := e;
    g := LeftQuotient( gen ^ e, g );
    bimg := OnTuples( base, g );
fi; at /home/caj/temp/gap/lib/pcgsperm.gi:843 called from 
ExponentsOfPcElementPermGroup( pcgs, g, 1, Length( pcgs ), 'e' 
 ) at /home/caj/temp/gap/lib/pcgsperm.gi:1254 called from
ExponentsOfPcElement( ocr.modulePcgs, x 
 ) at /home/caj/temp/gap/lib/onecohom.gi:264 called from
ocr.moduleMap( n ) at /home/caj/temp/gap/lib/onecohom.gi:1037 called from
OCEquationVector( ocr, rels[i] ) at /home/caj/temp/gap/lib/onecohom.gi:1247 called from
OCOneCocycles( ocr, true ); at /home/caj/temp/gap/lib/grpcompl.gi:142 called from
```

**Comment by hulpke** [comment] 2019-06-15 23:08
@ChrisJefferson Thank you so much. With this, I found the bug. `fr` is only influencing it by how it sets a homomorphism, there is a buggy assumption on generators in the library. I know how to fix it.

**Closed** 2019-06-25 18:47 UTC
Labels: topic: tests
