### ISSUE TITLE
Segmentation fault on Macbook M2 Pro

### ISSUE THREAD

**Issue by davistem** [gap-system/gap#5465] opened 2023-06-22 12:30 UTC
On my new Macbook M2 Pro, the following code consistently crashes GAP, which reports segmentation faults; typically this happens around the 7th iteration. It runs fine on non-ARM processors, to my knowledge. It would be good if someone could reproduce it, to start with. Obviously any suggestions about what to do about it would also be great. 

I do not feel qualified to advance any hypothesis on what is wrong.

```
g:=SimpleLieAlgebra("E",8,Rationals);;
B:=Basis(g);;
e:=Sum(B{[1..8]});;
mat0:=AdjointMatrix(B,e);;
mat:=AdjointMatrix(B,e);;
r:=RankMat(mat);;
i:=1;;
while r>0 do
 Print("iteration ",i,"\n");
 ElementaryDivisorsMat(mat);;
 mat:=mat*mat0;;
 r:=RankMat(mat);;
 i:=i+1;;
od;
```

**Comment by davistem** [comment] 2023-06-22 14:03
Hi Max,

ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Homebrew 4.0.24
xcode-select version 2397.
total 0
drwxr-xr-x   4 root      wheel   128 15 May 15:11 AAU
drwxrwx---   8 root      admin   256  3 Oct  2019 DefaultUser
drwxr-xr-x   3 root      wheel    96 25 May 14:48 Installomator
drwxrwxr-x   5 root      wheel   160 15 May 15:10 MAV
drwxrwxr-x   3 root      wheel    96 15 May 15:09 MDMApproval
drwxr-x---   4 root      wheel   128 15 May 15:09 MicroMDM
drwxrwx---   2 root      Virex    64 15 May 15:10 Quarantine
drwxrwxr-x   3 root      wheel    96 15 May 15:09 UoM Notifications
drwxr-xr-x  41 root      wheel  1312 15 Jun 09:52 bin
drwxrwxr-x@ 44 userds  staff  1408  6 Jun 10:02 gap-4.12.2
drwxr-xr-x   4 root      wheel   128  1 Jun 12:02 lib
drwxr-xr-x  25 root      wheel   800 15 May 15:08 munki
drwxr-xr-x   9 root      wheel   288 15 May 15:01 munkireport
drwxr-xr-x   5 root      wheel   160 22 Sep  2022 share
drwxr-xr-x   5 root      wheel   160 26 May 16:41 sicstus4.8.0
drwxr-xr-x@  4 userds  wheel   128 13 Jun 12:53 texlive

Best,
David

**Comment by fingolfin** [comment] 2023-06-27 16:11
So where is your GAP binary located, in `/usr/local/gap-4.12.2`, as `/usr/local/gap-4.12.2` ?

Then it might be helpful to know the output of `otool -L `/usr/local/gap-4.12.2/gap`


(Just FYI many people regularly use GAP on M1 macs, myself included, but so far I have no reports on M2. That said, I'd be surprised if something M2 specific would be the cause; I suspect something else is going on, e.g. maybe GAP is linked against a "bad" version of some shared library. Hard to say without debugging it...

Another potentially helpful thing is to get a crash report. Perhaps this works:

1. Open the Console app, from Applications > Utilities in Finder.
2. Select Crash Reports.
3. Locate crash reports for your app in the list. Logs are listed by the app’s binary name.
4. Left-click the desired log’s file name.
5. Click into the bottom part of the window, which should be showing a lot of text starting with "Translated Report  (Full Report Below)
" or so
6. Press Cmd-A to select all text, then Cmd-C to copy
7. paste the result into a reply here on the GAP issue tracker

**Comment by davistem** [comment] 2023-07-13 07:28
Hi Max,

Sorry for radio silence.

1. GAP binary is /usr/local/gap-4.12.2/gap

2. Output of otool and crash report below.

3. NEW DEVELOPMENT. It appears that GAP runs the code without segmentation errors if I start gap in iTerm rather than the default Terminal. Which is very odd.

Best,
David

❯ otool -L /usr/local/gap-4.12.2/gap
/usr/local/gap-4.12.2/gap:
	/usr/local/gap-4.12.2/extern/install/gmp/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)


-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               gap [47163]
Path:                  /usr/local/gap-4.12.2/gap
Identifier:            gap
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [47030]
Responsible:           Terminal [47027]
User ID:               502

Date/Time:             2023-07-13 08:22:07.1408 +0100
OS Version:            macOS 13.4.1 (22F82)
Report Version:        12
Anonymous UUID:        EF999367-1780-55C0-43A5-9D2AAF7FB966

Sleep/Wake UUID:       581F481E-5057-4945-966C-D2551ABF8328

Time Awake Since Boot: 120000 seconds
Time Since Wake:       1613 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000016fb7c000
Exception Codes:       0x0000000000000001, 0x000000016fb7c000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [47163]

VM Region Info: 0x16fb7c000 is not in any region.  Bytes after previous region: 1  Bytes before following region: 555761664
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                       16f380000-16fb7c000    [ 8176K] rw-/rwx SM=PRV  thread 0
--->  GAP OF 0x21204000 BYTES
      unused __TEXT               190d80000-190ddc000    [  368K] r-x/r-x SM=COW  ...ed lib __TEXT

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libgmp.10.dylib               	       0x10122490c __gmpn_rshift + 188
1   libgmp.10.dylib               	       0x101217104 __gmpz_gcd + 608


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000100006a57468   x2: 0x0000000000000000   x3: 0x0000000000000004
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0xfffffffffffffffc   x9: 0x000000016fb59df0  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000001  x15: 0x3b92a1e5abebe003
   x16: 0x000000016fb7bfe8  x17: 0x56c687e41810e6e7  x18: 0xfffffffffffffa00  x19: 0x000000016fb59e98
   x20: 0x0000000000000006  x21: 0x000000016fb59dc0  x22: 0x0000000000000006  x23: 0x000000016fb59df0
   x24: 0x0000000000000000  x25: 0x0000000000000004  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000065   fp: 0x000000016fb59e80   lr: 0x0000000101217104
    sp: 0x000000016fb59dc0   pc: 0x000000010122490c cpsr: 0x20001000
   far: 0x000000016fb7c000  esr: 0x92000047 (Data Abort) byte write Translation fault

Binary Images:
       0x100284000 -        0x100423fff gap (*) <ba7cf6dd-83c3-3b26-b857-17a116b47603> /usr/local/gap-4.12.2/gap
       0x101208000 -        0x101263fff libgmp.10.dylib (*) <4796fdea-49d8-354d-b8de-b97133f1e7c4> /usr/local/gap-4.12.2/extern/install/gmp/lib/libgmp.10.dylib
       0x10127c000 -        0x101287fff io.so (*) <7c499166-b23e-39a9-b1c5-4fe5b09b523a> /usr/local/gap-4.12.2/pkg/io/bin/aarch64-apple-darwin22-default64-kv8/io.so
       0x101294000 -        0x10129bfff ncurses.so (*) <e455b67f-cbda-34d7-9e0c-b42098fd6dd5> /usr/local/gap-4.12.2/pkg/browse/bin/aarch64-apple-darwin22-default64-kv8/ncurses.so
       0x1012ac000 -        0x1012affff curl.so (*) <e1b2b429-84e9-321f-be21-6b6c328681b3> /usr/local/gap-4.12.2/pkg/curlinterface/bin/aarch64-apple-darwin22-default64-kv8/curl.so
       0x1012bc000 -        0x1012c3fff orb.so (*) <d6ef1f79-2ef6-3ae2-a688-1f76f4f73061> /usr/local/gap-4.12.2/pkg/orb/bin/aarch64-apple-darwin22-default64-kv8/orb.so
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=919.1M resident=0K(0%) swapped_out_or_unallocated=919.1M(100%)
Writable regions: Total=4.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=4.7G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           155.2M       15 
MALLOC guard page                   96K        5 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                      128.0M        1 
VM_ALLOCATE (reserved)             3.9G        1         reserved VM address space (unallocated)
__AUTH                             325K       67 
__AUTH_CONST                      3811K      155 
__DATA                            14.1M      153 
__DATA_CONST                      4372K      162 
__DATA_DIRTY                       361K       58 
__LINKEDIT                       802.6M        7 
__OBJC_RO                         66.3M        1 
__OBJC_RW                         2011K        1 
__TEXT                           116.5M      170 
dyld private memory                272K        2 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                              5.7G      806 
TOTAL, minus reserved VM space     1.3G      806 



-----------
Full Report
-----------

{"app_name":"gap","timestamp":"2023-07-13 08:22:08.00 +0100","app_version":"","slice_uuid":"ba7cf6dd-83c3-3b26-b857-17a116b47603","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 13.4.1 (22F82)","roots_installed":0,"incident_id":"FE0D3B92-7249-42F7-BAA4-45292576C67B","name":"gap"}
{
  "uptime" : 120000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "Mac14,10",
  "coalitionID" : 13507,
  "osVersion" : {
    "train" : "macOS 13.4.1",
    "build" : "22F82",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-13 08:22:07.1408 +0100",
  "incident" : "FE0D3B92-7249-42F7-BAA4-45292576C67B",
  "pid" : 47163,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-07-13 08:22:00.0359 +0100",
  "procStartAbsTime" : 3058354117939,
  "procExitAbsTime" : 3058523748797,
  "procName" : "gap",
  "procPath" : "\/usr\/local\/gap-4.12.2\/gap",
  "parentProc" : "zsh",
  "parentPid" : 47030,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "EF999367-1780-55C0-43A5-9D2AAF7FB966",
  "responsiblePid" : 47027,
  "responsibleProc" : "Terminal",
  "codeSigningID" : "gap",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570556929,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 1613,
  "sleepWakeUUID" : "581F481E-5057-4945-966C-D2551ABF8328",
  "sip" : "enabled",
  "vmRegionInfo" : "0x16fb7c000 is not in any region.  Bytes after previous region: 1  Bytes before following region: 555761664\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      Stack                       16f380000-16fb7c000    [ 8176K] rw-\/rwx SM=PRV  thread 0\n--->  GAP OF 0x21204000 BYTES\n      unused __TEXT               190d80000-190ddc000    [  368K] r-x\/r-x SM=COW  ...ed lib __TEXT",
  "exception" : {"codes":"0x0000000000000001, 0x000000016fb7c000","rawCodes":[1,6169280512],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x000000016fb7c000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":47163},
  "vmregioninfo" : "0x16fb7c000 is not in any region.  Bytes after previous region: 1  Bytes before following region: 555761664\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      Stack                       16f380000-16fb7c000    [ 8176K] rw-\/rwx SM=PRV  thread 0\n--->  GAP OF 0x21204000 BYTES\n      unused __TEXT               190d80000-190ddc000    [  368K] r-x\/r-x SM=COW  ...ed lib __TEXT",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1076471,"threadState":{"x":[{"value":0},{"value":17592297550952},{"value":0},{"value":4},{"value":0},{"value":0},{"value":0},{"value":0},{"value":18446744073709551612},{"value":6169140720},{"value":0},{"value":0},{"value":0},{"value":0},{"value":1},{"value":4292671402641448963},{"value":6169280488},{"value":6252834546376566503},{"value":18446744073709550080},{"value":6169140888},{"value":6},{"value":6169140672},{"value":6},{"value":6169140720},{"value":0},{"value":4},{"value":0},{"value":0},{"value":101}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4313936132},"cpsr":{"value":536875008},"fp":{"value":6169140864},"sp":{"value":6169140672},"esr":{"value":2449473607,"description":"(Data Abort) byte write Translation fault"},"pc":{"value":4313991436,"matchesCrashFrame":1},"far":{"value":6169280512}},"queue":"com.apple.main-thread","frames":[{"imageOffset":117004,"symbol":"__gmpn_rshift","symbolLocation":188,"imageIndex":1},{"imageOffset":61700,"symbol":"__gmpz_gcd","symbolLocation":608,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4297605120,
    "size" : 1703936,
    "uuid" : "ba7cf6dd-83c3-3b26-b857-17a116b47603",
    "path" : "\/usr\/local\/gap-4.12.2\/gap",
    "name" : "gap"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4313874432,
    "size" : 376832,
    "uuid" : "4796fdea-49d8-354d-b8de-b97133f1e7c4",
    "path" : "\/usr\/local\/gap-4.12.2\/extern\/install\/gmp\/lib\/libgmp.10.dylib",
    "name" : "libgmp.10.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4314349568,
    "size" : 49152,
    "uuid" : "7c499166-b23e-39a9-b1c5-4fe5b09b523a",
    "path" : "\/usr\/local\/gap-4.12.2\/pkg\/io\/bin\/aarch64-apple-darwin22-default64-kv8\/io.so",
    "name" : "io.so"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4314447872,
    "size" : 32768,
    "uuid" : "e455b67f-cbda-34d7-9e0c-b42098fd6dd5",
    "path" : "\/usr\/local\/gap-4.12.2\/pkg\/browse\/bin\/aarch64-apple-darwin22-default64-kv8\/ncurses.so",
    "name" : "ncurses.so"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4314546176,
    "size" : 16384,
    "uuid" : "e1b2b429-84e9-321f-be21-6b6c328681b3",
    "path" : "\/usr\/local\/gap-4.12.2\/pkg\/curlinterface\/bin\/aarch64-apple-darwin22-default64-kv8\/curl.so",
    "name" : "curl.so"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4314611712,
    "size" : 32768,
    "uuid" : "d6ef1f79-2ef6-3ae2-a688-1f76f4f73061",
    "path" : "\/usr\/local\/gap-4.12.2\/pkg\/orb\/bin\/aarch64-apple-darwin22-default64-kv8\/orb.so",
    "name" : "orb.so"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6725042176,
  "size" : 3551641600,
  "uuid" : "be59bb71-7b69-3efc-86a8-5625a077ae2e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=919.1M resident=0K(0%) swapped_out_or_unallocated=919.1M(100%)\nWritable regions: Total=4.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=4.7G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           155.2M       15 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                      128.0M        1 \nVM_ALLOCATE (reserved)             3.9G        1         reserved VM address space (unallocated)\n__AUTH                             325K       67 \n__AUTH_CONST                      3811K      155 \n__DATA                            14.1M      153 \n__DATA_CONST                      4372K      162 \n__DATA_DIRTY                       361K       58 \n__LINKEDIT                       802.6M        7 \n__OBJC_RO                         66.3M        1 \n__OBJC_RW                         2011K        1 \n__TEXT                           116.5M      170 \ndyld private memory                272K        2 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                              5.7G      806 \nTOTAL, minus reserved VM space     1.3G      806 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "2ee4b5fb07c8ae8159a4f324468deb4a517578c9",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000055
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    },
    {
      "treatmentId" : "8ca8349c-e2bc-482c-9ca7-3907b48a5341",
      "experimentId" : "648b5a581b04c12d4127bbb6",
      "deploymentId" : 400000001
    }
  ]
}
}

**Comment by fingolfin** [comment] 2023-09-01 12:15
The bit about iTerm vs. Terminal is odd. Only guess I have is that perhaps different shells are started in each, with different environments. E.g. maybe in one a `DYLD_...something...` environment variable is set which affects things for better or worse?


That said, I also see that your are using the copy of GMP bundled with GAP. That suggest to me that you did not fully follow the instructions in `INSTALL.md` for building GAP on macOS (no offense intended and also not meant as an "accusation", just an observation). So perhaps try this: go to the gap source directory, then do

    brew install autoconf libtool gmp readline
    ./configure --with-gmp=$(brew --prefix) --with-readline=$(brew --prefix)/opt/readline
    make clean && make -j10

to recompile GAP. That should help. Perhaps also run `otool -L gap` again and report the output of that.

If that doesn't help, I am out of ideas. All I can say is that your test code works great on my M1 Mac, and I know multiple people using GAP on M1 and M2 macs without any problem. That doesn't mean there is no bug in GAP, it just makes me suspect that there is some issue with your machine (the software, not the hardware), but that's just an educated guess. Regardless: without further clues, I am afraid there is nothing we can do :-(.

**Comment by fingolfin** [comment] 2024-01-09 12:58
There is nothing we can do here right now, with the information we have; plus it works for other people on M2 and M3 macs, so I'll assume for now this was caused by some problematic files somewhere at some point. Or perhaps also caused by the GMP version in 4.12.2? Dunno...

So closing for now, as we can't really do anything and had no other similar reports.

**Closed by fingolfin** 2024-01-09 12:58 UTC
