### ISSUE TITLE
New function ErrorMayQuit -- like Error but can't return.

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#79] opened 2015-03-18 10:35 UTC
This function is like `Error`, except users cannot return and continue the function. I'm putting this here for discussion / testing, before I make a proper pull request

```
ErrorMayQuit := function ( arg )
    ErrorInner( rec(
         context := ParentLVars( GetCurrentLVars(  ) ),
         mayReturnVoid := false, mayReturnObj := false,
         lateMessage := "type 'quit;' to quit to outer loop",
         printThisStatement := false), arg);
 return;
 end;
```

**Comment by wilfwilson** [comment] 2015-03-18 11:05
This seems to work as intended, and does what I would like.

**Comment by stevelinton** [comment] 2015-03-18 13:18
I suspect that most of the 2300 or so uses of Error in the library should be changed to this. An alternative is to make this the behaviour of the Error function and introduce a new name "BreakPoint" for instance, for the current behaviour of Error. Maybe the best solution is to change the library calls to ErrorMayQuit except for the handful that don't AND introduce Break or BreakPoint as a synonym for the current behaviour of Error.  Then we think of Error per se as a backwards compatibility synonym for Break.

**Comment by ChrisJefferson** [comment] 2015-04-27 14:19
Now a pull request at #163 . Not made any changes to any calls to "Error" yet.

**Comment by markuspf** [comment] 2015-09-16 21:42
#163 has been merged.

**Closed by markuspf** 2015-09-16 21:42 UTC
Labels: gapdays2015
