### ISSUE TITLE
Unable to create `MatrixObj` from `Float` matrix

### ISSUE THREAD

**Issue by mihalova** [gap-system/gap#5164] opened 2022-10-21 12:40 UTC
I tried to create MatrixObj from matrix that has Floats in it. The Matrix() command was unable to create such matrix. It also didn't print any error, it just looked like it is still looking for it. I needed to end it on my own.
I think the problem is with the function DefaultScalarDomainOfMatrixList() that's called to obtain the BaseDomain.

### Observed behaviour
```
gap> Matrix([[1.2, 2.2]]);
^CError, user interrupt in
  new := elm + gen; at /Users/dominika/gap-4.12.0/lib/ring.gi:634 called from 
Enumerator( D ) at /Users/dominika/gap-4.12.0/lib/domain.gi:285 called from
k in f at /Users/dominika/gap-4.12.0/lib/matrix.gi:4237 called from
DefaultScalarDomainOfMatrixList( [ list ] ) at /Users/dominika/gap-4.12.0/lib/matobj.gi:353 called from
<function "Matrix method">( <arguments> )
 called from read-eval loop at *stdin*:44
you can 'return;'
```

**Comment by fingolfin** [comment] 2022-10-21 15:02
Thank you for this report, but I think it is a duplicate of #5134 , and a fix for that is "in the pipeline".

**Closed by fingolfin** 2022-10-21 15:02 UTC
