### ISSUE TITLE
Errors in teststandard.g: grpauto, grplatt, grpperm and others

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1152] opened 2017-02-17 12:39 UTC
This seen in Jenkins and I can reproduce it on my laptop too. Happens in the master branch.
```
$ gapdev -r -A tst/teststandard.g 
 ┌───────┐   GAP v4.8.6-1322-gcb6d4d1 of 2017-02-17 10:57:11 (GMT)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin15.6.0-gcc-6-default64
 Libs used:  gmp 6.0.0, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
 Packages:   GAPDoc 1.5.1
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
You should start GAP4 using `gap -A -x 80 -r -m 100m -o 1g -K 2g'.

Architecture: x86_64-apple-darwin15.6.0-gcc-6-default64

testing: /Users/alexk/GITREPS/gap/tst/test64bit/randlist.tst
      44 msec for randlist.tst
testing: /Users/alexk/GITREPS/gap/tst/test64bit/range.tst
       0 msec for range.tst
testing: /Users/alexk/GITREPS/gap/tst/testextra/grpauto.tst
########> Diff in /Users/alexk/GITREPS/gap/tst/testextra/grpauto.tst:152
# Input is:
IsomorphismGroups(gp1,gp2)<>fail;
# Expected output:
true
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ExponentsOfPcElement' on 2 arguments
########
 1371074 msec for grpauto.tst
```

**Comment by alex-konovalov** [comment] 2017-02-17 12:42
More diffs:
```
testing: /Users/alexk/GITREPS/gap/tst/testextra/grplatt.tst
########> Diff in /Users/alexk/GITREPS/gap/tst/testextra/grplatt.tst:63
# Input is:
l:=SubgroupsTrivialFitting(g);;    
# Expected output:
# But found:
Error, List Element: <list>[42] must have an assigned value
########
```
and
```
########> Diff in /Users/alexk/GITREPS/gap/tst/testextra/grpperm.tst:80
# Input is:
Length(ConjugacyClassesSubgroups(g));
# Expected output:
2048
# But found:
Error, List Element: <list>[14] must have an assigned value
########
```
and
```
########> Diff in /Users/alexk/GITREPS/gap/tst/testextra/grpperm.tst:190
# Input is:
List([1..7],x->Size(Normalizer(s,PrimitiveGroup(56,x))));
# Expected output:
[ 80640, 80640, 80640, 80640, 80640, 40320, 40320 ]
# But found:
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
[ 80640, 80640, 80640, 80640, 80640, 40320, 40320 ]
########
```

**Comment by alex-konovalov** [comment] 2017-02-17 17:33
More diffs in other tests:
```
########> Diff in /Users/alexk/GITREPS/gap/tst/testinstall/grpmat.tst:30
# Input is:
Size( AutomorphismGroup( G ) );
# Expected output:
24
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ExponentsOfPcElement' on 2 arguments
########
```
and
```
########> Diff in /Users/alexk/GITREPS/gap/tst/testinstall/morpheus.tst:12
# Input is:
a:=AutomorphismGroup(g);;
# Expected output:
# But found:
Error, List Element: <list>[23] must have an assigned value
########
```
and subsequent lines in `morpheus.tst`, and also
```
testing: /Users/alexk/GITREPS/gap/tst/teststandard/grpconst.tst
########> Diff in /Users/alexk/GITREPS/gap/tst/teststandard/grpconst.tst:30
# Input is:
ConstructAndTestAllGroups( 96 );;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ClosureGroup' on 2 arguments
########
########> Diff in /Users/alexk/GITREPS/gap/tst/teststandard/grpconst.tst:31
# Input is:
ConstructAndTestAllGroups( 648 );;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ExponentsOfPcElement' on 2 arguments
########
########> Diff in /Users/alexk/GITREPS/gap/tst/teststandard/grpconst.tst:32
# Input is:
ConstructAndTestAllGroups( 840 );;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ClosureGroup' on 2 arguments
########
########> Diff in /Users/alexk/GITREPS/gap/tst/teststandard/grpconst.tst:33
# Input is:
ConstructAndTestAllGroups( 1560 );;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ClosureGroup' on 2 arguments
########
########> Diff in /Users/alexk/GITREPS/gap/tst/teststandard/grpconst.tst:34
# Input is:
ConstructAndTestAllGroups( 1800 );;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ExponentsOfPcElement' on 2 arguments
########
```

**Comment by hulpke** [comment] 2017-02-18 01:41
I have a fix for the first (which must have been there before) issue,

I cannot reproduce the others.

**Comment by alex-konovalov** [comment] 2017-02-18 11:24
@hulpke thanks - let's fix them one step at a time, if you have the fix please submit it!

**Comment by hulpke** [comment] 2017-02-20 02:06
@alex-konovalov 
I have merged a fix for the first.

**Comment by alex-konovalov** [comment] 2017-02-20 09:40
@hulpke Thanks - I will see how it goes. Just to add that:
- it's always useful to put cross-references e.g. "I have merge a fix for the first in #1158" or "I've committed a fix in commit e09a7302a39c17b8c27bbd38c48e49dc4bab4f00".
- for such one-commit pull requests, you can use `rebase and merge` button, then this will put your commit on top of the current master branch, keeping the history linear. Thus, even for trivial commits you can use pull request to pipe it through continuous integration and code coverage tools, and still have linearised history of commits.

**Comment by alex-konovalov** [comment] 2017-02-21 13:08
@hulpke yes, it seems like the rest of issues are not relevant, except this one:

```
########> Diff in /Users/alexk/GITREPS/gap/tst/testextra/grpperm.tst:1
# Input is:
List([1..7],x->Size(Normalizer(s,PrimitiveGroup(56,x))));
# Expected output:
[ 80640, 80640, 80640, 80640, 80640, 40320, 40320 ]
# But found:
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
#I  Using Primitive Groups Library
[ 80640, 80640, 80640, 80640, 80640, 40320, 40320 ]
########
```

The info message is produced by `InfoPerformance` and it is set to zero by `START_TEST`. It looks like you increase it deliberately in the test file to check two different ways of computing the normaliser, what's fine. Would it be OK if I will insert `SetInfoLevel(InfoPerformance,0);` after that as below?

```
# test of data library use
gap> SetInfoLevel(InfoPerformance,2);
gap> Size(Normalizer(SymmetricGroup(12),PrimitiveGroup(12,2)));
#I  Using Primitive Groups Library
95040
gap> Size(Normalizer(SymmetricGroup(12),
> PrimitiveGroup(12,2):NoPrecomputedData));
95040
gap> SetInfoLevel(InfoPerformance,0);
gap> s:=SymmetricGroup(56);;
gap> List([1..7],x->Size(Normalizer(s,PrimitiveGroup(56,x))));
[ 80640, 80640, 80640, 80640, 80640, 40320, 40320 ]
```

After the test, `STOP_TEST` will restore `InfoPerformance` level to its value prior to the test.

**Comment by hulpke** [comment] 2017-02-28 18:32
@alex-konovalov 
Thank you, yes, this would be fine (and apologies fopr not replying earlier).

**Closed** 2017-03-02 11:23 UTC
