### ISSUE TITLE
Some futher warnings on a different supercomputer

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#1348] opened 2017-05-21 09:58 UTC
I have the following warngins (the compilation succeeds, GAP starts normally). 
````
   C       src/gap.c => obj/gap.lo
In file included from src/gap.c:81:
./src/stats.h: In function ‘EXEC_STAT’:
./src/stats.h:56: warning: declaration of ‘stat’ shadows a global declaration
/usr/include/sys/stat.h:455: warning: shadowed declaration is here
In file included from src/gap.c:96:
./src/hookintrprtr.h: In function ‘VisitStatIfHooked’:
./src/hookintrprtr.h:150: warning: declaration of ‘stat’ shadows a global declaration
/usr/include/sys/stat.h:455: warning: shadowed declaration is here
At top level:
cc1: warning: unrecognized command line option "-Wno-unknown-warning-option"
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"
   SED     src/gap_version.c.in => gen/gap_version.c
````
then
````
   C       src/gmpints.c => obj/gmpints.lo
src/gmpints.c: In function ‘PowInt’:
src/gmpints.c:1376: warning: declaration of ‘pow’ shadows a global declaration
/usr/include/bits/mathcalls.h:154: warning: shadowed declaration is here
src/gmpints.c: In function ‘PowerModInt’:
src/gmpints.c:2130: warning: declaration of ‘exp’ shadows a global declaration
/usr/include/bits/mathcalls.h:101: warning: shadowed declaration is here
src/gmpints.c: In function ‘FuncPOWERMODINT’:
src/gmpints.c:2169: warning: declaration of ‘exp’ shadows a global declaration
/usr/include/bits/mathcalls.h:101: warning: shadowed declaration is here
src/gmpints.c: In function ‘FuncRandomIntegerMT’:
src/gmpints.c:2242: warning: declaration of ‘rand’ shadows a global declaration
/usr/include/stdlib.h:380: warning: shadowed declaration is here
At top level:
cc1: warning: unrecognized command line option "-Wno-unknown-warning-option"
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"
   C       src/gvars.c => obj/gvars.lo
````
then
````
   C       src/objset.c => obj/objset.lo
src/objset.c: In function ‘LookupObjMap’:
src/objset.c:437: warning: declaration of ‘index’ shadows a global declaration
/usr/include/string.h:489: warning: shadowed declaration is here
At top level:
cc1: warning: unrecognized command line option "-Wno-unknown-warning-option"
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"
   C       src/opers.c => obj/opers.lo
````
and finally 
````
   C       src/trans.c => obj/trans.lo
src/trans.c: In function ‘FuncCOMPONENT_REPS_TRANS’:
src/trans.c:2390: warning: declaration of ‘index’ shadows a global declaration
/usr/include/string.h:489: warning: shadowed declaration is here
src/trans.c: In function ‘FuncCOMPONENTS_TRANS’:
src/trans.c:2573: warning: declaration of ‘index’ shadows a global declaration
/usr/include/string.h:489: warning: shadowed declaration is here
At top level:
cc1: warning: unrecognized command line option "-Wno-unknown-warning-option"
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"
   C       src/vars.c => obj/vars.lo
````
The output of ````cc -v```` is 
````
DEBRECEN2[visual] ~/bin/gap (0)$ cc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
````
This is a different supercomputer than the one in #1346

**Comment by fingolfin** [comment] 2017-07-03 10:30
This is essentially a duplicate of #1346

**Closed by fingolfin** 2017-07-03 10:30 UTC
Labels: build system
