### ISSUE TITLE
Unwanted side effect: GAP converts an interval to a list

### ISSUE THREAD

**Issue by laurentbartholdi** [gap-system/gap#1179] opened 2017-03-07 11:09 UTC
Observed behaviour (in the latest branch) is:

```
gap> D := [1..10];
[ 1 .. 10 ]
gap> G := Group(());
Group(())
gap> IsTransitive(G,D);
false
gap> D;
[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
```

And D should remain an interval.

**Comment by Stefan-Kohl** [comment] 2017-03-09 11:07
The underlying problem is the following:
```
gap> D := [1..10];           
[ 1 .. 10 ]
gap> IsSubset([1],D);    
false
gap> D;
[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

**Comment by fingolfin** [comment] 2017-03-09 11:59
So this is a duplicate of issue #815.

**Closed by fingolfin** 2017-03-09 11:59 UTC
Labels: bug, duplicate
