### ISSUE TITLE
Inconsistent behavior of equality of AllSmallGroup

### ISSUE THREAD

**Issue by ChoiwahChow** [gap-system/gap#3275] opened 2019-02-07 00:44 UTC
gap> AllSmallGroups(10) = AllSmallGroups(10);
false

I would expect it returns true, e.g. SymmetricGroup(5) = SymmetricGroup(5) returns true.
```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP        │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2018.09.20, AutPGrp 1.10, Carat 2.2.2, CRISP 1.4.4, 
             Cryst 4.1.18, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, IO 4.5.4, IRREDSOL 1.4, 
             LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, 
             Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, TransGrp 2.0.4, utils 0.59

```

**Comment by markuspf** [comment] 2019-02-07 11:46
Equality tests are notoriously difficult to get "right". I suppose you want to think of "equal" as in "actually equal as objects", which is not the case for the objects in the list returned by `AllSmallGroups`.

There is a twist in GAP, unfortunately. The way GAP tries to compare (finite) groups is by 

 * comparing their generating sets: if they are the same, the groups are the same. If they are not, the groups are not the same
 * if they both have known generators, and are both the same size, check that all generators of one of the groups are in the other.

The observed behaviour occurs because the generators of the pc-groups returned by the first call to `AllSmallGroups` are *not* elements of the ones returned by the other.

For permutation groups GAP treats all permutations as elements of the symmetric group on the naturals, so even if you give `SymmetricGroup(10)` by some more obscure generating set than the default the comparison `=` will give you `true`.

If you want to compare up to isomorphism you can of course use `IsomorphismGroups`, but beware that this operation is very expensive in general.

**Comment by hulpke** [comment] 2019-02-08 02:35
Just trying to emphasize the relevant point in @markuspf 's answer: Equality comparison is by testing equality of the sets of elements. Permutations that move points the same way are always equal, thus the result for (e.g.) symmetric groups.

(Most) Groups created by the small group library (more generally: PcGroups) are -- by design -- only ever equal to elements  of *the same group*. That is, if you create a group (with the same pc presentation) twice, their elements will always be different. You would have to set up appropriate isomorphisms to connect two such groups.

This design decision makes the criterion for equalityy clear and avoids any ambiguity -- say if two groups are isomorphic with slightly different relator sets.

I suggest we close this issue.

**Closed** 2019-02-08 09:09 UTC
Labels: status: invalid
