### ISSUE TITLE
Warning message from GRAPE 4.8.1 about variable `Stabiliser' on startup

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#2996] opened 2018-11-12 17:44 UTC
In GAP 4.10.0, when GRAPE is loaded on startup, a warning message is displayed about the variable 'Stabiliser'. The remedy for this appears to be to replace 'Stabiliser' by `Stabilizer' in line 3963 in gap-4.10.0/pkg/grape-4.8.1/lib/grape.g.

**Comment by alex-konovalov** [comment] 2018-11-12 20:54
No such warnings is seen in GRAPE's tests https://travis-ci.org/gap-system/gap-docker-pkg-tests/jobs/453290410 - likely because the tests load it at a later stage. Which exactly setup do you use to make it being loaded on startup?

Anyhow, GRAPE has a repository on GitHub and I will now test the new GitHub beta-feature to transfer this issue there.

**Comment by alex-konovalov** [comment] 2018-11-12 20:56
... and it does not work across different organisations. So, you can suggest the change to @lhsoicher by submitting a pull request to https://github.com/gap-packages/grape/.

**Comment by wilfwilson** [comment] 2018-11-16 10:20
Thanks for the report @Stefan-Kohl. This is a duplicate of an issue that I raised two months ago: https://github.com/gap-system/gap/issues/2828

Although this particular issue could be resolved by adding a workaround to GRAPE (changing the `Stabiliser` to `Stabilizer`; roughly, changing from the British spelling to American), I don't feel like this is the proper solution. I feel like this is instead a problem with GAP or its documentation.

It seems like the problem is: when a package is autoloaded via the `gap.ini` file, and that package uses synonyms defined in the `lib/transatl.g` file, then an `unbound global variable` warning occurs. Presumably, the `lib/transatl.g` file is being read *after* packages are autoloaded from `gap.ini`. And so at the point that GRAPE is autoloaded, `Stabiliser` has not yet been declared as a synonym to `Stabilizer`.

I see several more proper solutions.

Best solution to this issue:
* `lib/transatl.g` should be read earlier in the GAP loading process, in particular, before reading the `gap.ini` file.

If that is not possible for some good reason:
* It should be documented that autoloading of packages should be done via the `gaprc` file rather than the `gap.ini` file. As things stand, I feel like loading GRAPE by setting it to autoload in my `gap.ini` file is appropriate behaviour.

Or (I don't like this idea):
* It should be documented that packages cannot use synonyms declared in `lib/translat.g`. If this decision is made, then the behaviour in GRAPE is a bug.

I will attempt to experiment with the first solution.

**Closed** 2018-11-17 09:11 UTC
Labels: status: duplicate
