### ISSUE TITLE
gap4r8/tst/testinstall/timeout.tst hangs when GAP 4.8.2 is called with option --cover

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#656] opened 2016-03-05 16:50 UTC
I have observed that gap4r8/tst/testinstall/timeout.tst hangs when GAP is called with option --cover.
More precisely, GAP 4.8.2 appears to run into an infinite loop in the line

`gap> CallWithTimeout(5000,spinFor,50000);`

**Comment by alex-konovalov** [comment] 2016-03-05 21:00
This option is regularly used to generate [code coverage reports](http://gap-coverage.northeurope.cloudapp.azure.com/coverage-total/) and the test runs there without problems. We may need to know more details on how exactly do you run it and on which machine...

**Comment by Stefan-Kohl** [comment] 2016-03-05 22:32
Details are (after the last line GAP hangs):

```
stefan@stefan-Lenovo-G70-35:/user/GAP/gap4r8$ bin/gap.sh --cover /user/GAP/log/Profile-TestInstall.gz -A
 ┌───────┐   GAP 4.8.2, 20-Feb-2016, build of 2016-02-21 15:40:20 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   GAPDoc 1.5.1
 Try '?help' for help. See also  '?copyright' and  '?authors'
gap> Read( Filename( DirectoriesLibrary( "tst" ), "testinstall.g" ) );
You should start GAP4 using `gap -A -x 80 -r -m 100m -o 1g'.
The more GAP4stones you get, the faster your system is.
The runtime of the following tests (in general) increases.
You should expect the test to take about one minute and show about
100000 GAP4stones on an Intel Core 2 Duo / 2.53 GHz machine.
The `next' time is an approximation of the running time for the next file.

Architecture: x86_64-pc-linux-gnu-gcc-default64

test file         GAP4stones     time(msec)
-------------------------------------------
testing: /user/GAP/gap4r8/tst/testinstall/flush.tst
flush.tst                  0            116
testing: /user/GAP/gap4r8/tst/testinstall/break.tst
break.tst                  0             84
testing: /user/GAP/gap4r8/tst/testinstall/dir.tst
dir.tst                    0             76
testing: /user/GAP/gap4r8/tst/testinstall/varargs.tst
varargs.tst                0             84
testing: /user/GAP/gap4r8/tst/testinstall/trace.tst
trace.tst                  0             72
testing: /user/GAP/gap4r8/tst/testinstall/bound.tst
bound.tst                  0             80
testing: /user/GAP/gap4r8/tst/testinstall/infinity.tst
infinity.tst               0             80
testing: /user/GAP/gap4r8/tst/testinstall/switch.tst
switch.tst                 0             76
testing: /user/GAP/gap4r8/tst/testinstall/zlattice.tst
zlattice.tst               0             76
testing: /user/GAP/gap4r8/tst/testinstall/longnumber.tst
longnumber.tst             0             72
testing: /user/GAP/gap4r8/tst/testinstall/gaussian.tst
gaussian.tst               0             80
testing: /user/GAP/gap4r8/tst/testinstall/atomic_basic.tst
atomic_basic.tst           0             80
testing: /user/GAP/gap4r8/tst/testinstall/recordname.tst
recordname.tst             0             76
testing: /user/GAP/gap4r8/tst/testinstall/unknown.tst
unknown.tst                0             76
testing: /user/GAP/gap4r8/tst/testinstall/boolean.tst
boolean.tst                0             76
testing: /user/GAP/gap4r8/tst/testinstall/eigen.tst
eigen.tst               2962            108   ( next ~0 sec )
testing: /user/GAP/gap4r8/tst/testinstall/listindex.tst
listindex.tst              0             88   ( next ~0 sec )
testing: /user/GAP/gap4r8/tst/testinstall/read.tst
read.tst                   0             84   ( next ~0 sec )
testing: /user/GAP/gap4r8/tst/testinstall/intarith.tst
intarith.tst               0             76   ( next ~0 sec )
testing: /user/GAP/gap4r8/tst/testinstall/log2.tst
log2.tst                   0             72   ( next ~0 sec )
testing: /user/GAP/gap4r8/tst/testinstall/timeout.tst

**Comment by alex-konovalov** [comment] 2016-03-05 22:35
Thanks. Does it hang if you will start it like this?
```
bin/gap.sh -r -A --cover /user/GAP/log/Profile-TestInstall.gz tst/testinstall.g
```

**Comment by Stefan-Kohl** [comment] 2016-03-05 22:41
Yes, just the same.

**Comment by ChrisJefferson** [comment] 2016-03-05 22:46
I'll try grabbing the latest dev version and run it on ubuntu, see what happens.

**Comment by alex-konovalov** [comment] 2016-03-05 22:49
I can reproduce the same on OS X with 4.8.2 - will try latest master branch now. Waited for 10 minutes - I know that it may be slower, but not to that extent...

**Comment by alex-konovalov** [comment] 2016-03-05 22:59
@ChrisJefferson yes, it passes instantly for me in the master branch. Good catch @Stefan-Kohl.

Indeed, code coverage reports are performed in the master branch, not in stable.

**Comment by ChrisJefferson** [comment] 2016-03-05 23:03
This is due to commit #bf73043cf6f9fcd04284e928fc1347a0fa7282b8 not being in stable-4.8.

**Comment by alex-konovalov** [comment] 2016-03-05 23:06
Ah, so should cherry pick it fix that?

**Comment by ChrisJefferson** [comment] 2016-03-05 23:10
yup, it's just a rename to avoid us having two global variables with the same name.

**Comment by Stefan-Kohl** [comment] 2016-03-06 10:51
In another situation, I reproducibly get a segfault when I run GAP 4.8.2 with option --cover,
but maybe this is just another symptom of the same problem and will go away with your fix.

**Comment by ChrisJefferson** [comment] 2016-03-06 12:21
If the problem is caused by timers, or pressing ctrl+c, then it probably is (basically, different bits of code that want to control the general dispatch loop were fighting with each other). If it's something else, then it might not be :)

**Comment by Stefan-Kohl** [comment] 2016-03-06 13:02
I'm not sure it is related to timers -- it happens when reading some larger data files, but I don't know whether that's really the reason. In any case, no CallWithTimeout and no pressing of ctrl+c is involved.

**Comment by alex-konovalov** [comment] 2016-03-07 12:36
@ChrisJefferson: I've cherry picked bf73043cf6f9fcd04284e928fc1347a0fa7282b8 onto stable-4.8

@Stefan-Kohl: I will close this issue now, but if you will further investigate that other problem with --cover and it will not disappear after this, please report it too.

**Closed by alex-konovalov** 2016-03-07 12:36 UTC
