### ISSUE TITLE
Problem with builtin_smull_overflow

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1859] opened 2017-11-06 15:12 UTC
Several packages fail to build in the master branch on Linux with gcc 4.8.5:
```
In file included from /circa/scratch/gap-jenkins/workspace/GAP-major-release-test/GAPCOPTS/64build/GAPTARGET/packagesload/label/kovacs/gap4r9/src/objects.h:21:0,
from /circa/scratch/gap-jenkins/workspace/GAP-major-release-test/GAPCOPTS/64build/GAPTARGET/packagesload/label/kovacs/gap4r9/src/compiled.h:20,
from src/rnams.h:24,
from src/pkg.h:30,
from src/pkg.cc:23:
/circa/scratch/gap-jenkins/workspace/GAP-major-release-test/GAPCOPTS/64build/GAPTARGET/packagesload/label/kovacs/gap4r9/src/intobj.h: In function ���UInt** prod_intobjs(long int, long int)���:
/circa/scratch/gap-jenkins/workspace/GAP-major-release-test/GAPCOPTS/64build/GAPTARGET/packagesload/label/kovacs/gap4r9/src/intobj.h:223:54: error: ���__builtin_smull_overflow��� was not declared in this scope
if (__builtin_smull_overflow(l >> 1, r ^ 1, &prod))
^
gmake: *** [src/semigroups_la-pkg.lo] Error 1

WARNING: Failed to build semigroups-3.0.7
```

**Comment by fingolfin** [comment] 2017-11-07 14:20
AFAIK this was caused by a mismatch between the C and C++ compilers (i.e. the C compiler supports `__builtin_smull_overflow`, hence GAP uses it, but the C++ compiler doesn't).

I assume @alex-konovalov resolved this by now, closing. Reopen if I am mistaken on this.

**Closed by fingolfin** 2017-11-07 14:20 UTC
Labels: build system

**Comment by alex-konovalov** [comment] 2017-11-14 22:42
@fingolfin yes, fine - I am not observing this any more.
