### ISSUE TITLE
File/folder access in GAP

### ISSUE THREAD

**Issue by mohammadfarrokhi** [gap-system/gap#3324] opened 2019-03-04 13:22 UTC
It seems that commands like IsReadableFile("abcd") does not return correct value when the access to the file or folder "abcd" is denied by operating system. This, in particular, makes problem when we are searching a whole drive, say.

Here is a typical example.

```
gap> IsReadableFile("C:/System Volume Information/");
true
gap> DirectoryContents("C:/System Volume Information/");
Error, Could not open C:/System Volume Information/ as directory,
see LastSystemError(); at /proc/cygdrive/C/gap/lib/files.gi:185 called from
<function "DirectoryContents">( <arguments> )
 called from read-eval loop at *stdin*:7
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
gap> LastSystemError().message;
"Permission denied"
```

```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i686-pc-cygwin-default32
 Configuration:  gmp 6.0.0, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2018.09.20, AutPGrp 1.10, Browse 1.8.8, CRISP 1.4.4, Cryst 4.1.18, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2,
             IO 4.5.4, IRREDSOL 1.4, LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, TransGrp 2.0.4,
             utils 0.59
```

**Comment by ChrisJefferson** [comment] 2019-03-04 14:41
While this isn't helpful to you, this seems to be a bug in cygwin's implementation of the `access` function.

If I write: `IsReadableFile("/cygdrive/c/System Volume Information")`, I get the correct answer (false), if I write `IsReadableFile("c:/System Volume Information")`, I (incorrectly) get true.

**Comment by ChrisJefferson** [comment] 2019-03-04 15:07
I've reported this to cygwin, I'll see if they agree it's is a bug in cygwin. If it is, they'll fix it, if not, I can think of some ways of working around it.

**Comment by ChrisJefferson** [comment] 2019-03-04 15:23
So, it looks like this is "by design", I'll think about the best long term (if any) solution.

This may or may not be useful to you, if you write:

`IsReadableFile(/proc/cygdrive/C/System Volume Information)` you'll get the right answer. In general if you look inside `/proc/cygdrive/C/` you'll find a copy of your C drive where things work "properly".

**Comment by mohammadfarrokhi** [comment] 2019-03-06 06:09
Thanks for the useful comments.

**Comment by fingolfin** [comment] 2019-05-03 12:22
It seems this issue has been resolved, so I am closing this ticket.

**Closed by fingolfin** 2019-05-03 12:22 UTC
Labels: kind: support request, os: windows
