### ISSUE TITLE
GAP 4.12.0 package test for `curlInterface` runs into infinite loop

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#5019] opened 2022-08-22 17:09 UTC
### Observed behaviour
The test for the package `curlInterface` hangs indefinitely.
It hangs in line 139 of the file `pkg/curlinterface/tst/basic.tst`, the command is
```
CurlRequest("www.google.com", "HEAD" , "");
```
### Expected behaviour
The mentioned command should return almost instantly.

**Comment by fingolfin** [comment] 2022-09-03 02:22
I can't reproduce this. In any case, this seems to be an issue in curlInterface, and you already opened an issue there, so we can close this one.

**Closed by fingolfin** 2022-09-03 02:22 UTC
