### ISSUE TITLE
The default `Sortex` methods are  not stable.

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#2634] opened 2018-07-09 08:14 UTC
Sorting a list with `Sortex` is in general not stable:
```
gap> ll:= [ 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2 ];;
gap> Sortex( ll );
(2,24)(3,21)(5,19)(7,17)(9,16)(11,15)
```
(The `2` keys at positions 2 and 3 get swapped by applying the returned permutation.)

As far as I see, this happens since commit 1d7361e29633f07c34dfdbfc6579cda4ae4b4169,
and the aim was to make the code faster.

The stability of `Sortex` was not guaranteed by the manual entry for `Sortex`,
but the old code (before the commit) contained the comment
`# Sort the new list according to the first item (stable).`,
and the header in `lib/list.gi` still contains the line
`#M  Sortex( <list> ) . . sort a list (stable), return the applied permutation`.

The point is that several pieces of GAP library code (written by me) assume stability for `Sortex`.
In fact, the only reason to call `Sortex` in these cases is the stability.
In this sense, the change has made the code at the same time much more efficient
and completely useless.

How shall we proceed?
I tend to the following strategy:

- Keep `Sortex` as it is now, and remove the erroneous comment.
- Introduce a new operation `SortexStable` that is guaranteed to be stable,
  and install methods for it.
- Change the library code in the relevant places to use `SortexStable` instead of `Sortex`.

What do you think?

**Comment by fingolfin** [comment] 2018-07-09 12:00
From a pragmatic point of view, I am fine with either strategy, i.e. the one described by @ThomasBreuer, or also the one by @ChrisJefferson (simply switching `Sortex` back to a stable sort; though in that case, we should also document the stability explicitly in the user documentation).

However, several packages use `Sortex`, so I wonder if they also implicitly rely on stability? While strictly speaking that would be a bug, we also have to be realistic and wonder about possible impact on correctness of their results... So from that POV, I'd prefer to follow @ChrisJefferson proposal.

Ignoring that, I'd slightly prefer what @ThomasBreuer said, because it fits better into the family of `Sort` vs. `StableSort` functions...

Packages using `Sortex` include:
* atlasrep
* automgrp
* browse
* corelg
* ctbllib
* cvec
* digraphs
* loops
* modisom
* orb
* PatternClass
* recog
* Semigroups
* YangBaxter

**Comment by ChrisJefferson** [comment] 2018-07-09 12:59
The following is from gap 4.7.8 (the oldest version I have lying around, and before I made any recent sort changes I think).

```
gap>  l := Concatenation(ListWithIdenticalEntries(500,[1,0]));
gap> p := Sortex(l);;
gap> List([1..1000], x -> x^p);
[501,2,502,4,503,6]
```

You can see that the first few elements aren't stably sorted.

I think (but please do let me know if I'm wrong, or which versions of GAP you are looking at) the old sort was more often stable, which led some people to think it was stable, but there are fairly small lists which are not stably sorted.

**Comment by ChrisJefferson** [comment] 2018-07-09 13:01
Note that `Sortex` only ever called `SortParallel` with `[1..n]` as the second argument, which then is just basically the same as calling sort (which is a shell sort) where a second list is sorted at the same time, so there was (that I can find) no reason for `Sortex` to be stable if `Sort` wasn't (at least in 4.7.8, which is the earliest GAP I can get to build on my machine).

**Comment by fingolfin** [comment] 2018-07-09 13:04
Indeed, I can reproduce this in GAP 4.6 and 4.4, too. Which makes sense, given that it used `SortParallel`.

So, I think we should proceed with @ThomasBreuer plan.

**Comment by fingolfin** [comment] 2018-07-09 13:07
(and perhaps also warn people that they may want to switch to `StableSortex`, if this kind of behavior is relevant for them?)

Finally, I notice that there is also an attribute `SortingPerm`, which is similar to `Sortex` but actually *does* seem to perform a stable sort.

**Comment by fingolfin** [comment] 2018-07-09 13:50
My mistake, I misread the output of GAP 4.4 :-/. Here is a version of the tests which is easier to verify:
```gap
l := Concatenation(ListWithIdenticalEntries(500,[1,0]));;
p := Sortex(l);;
IsSet(List([1..1000], x -> x^p){[1,3..999]}) and IsSet(List([1..1000], x -> x^p){[2,4..1000]});
```

The change of behavior was introduced 2013-05-16 by @stevelinton. Looking at the changes manual, we see that it was actually introduced in GAP 4.6.5 (July 2013), one of the versions I tested with. (I don't have a working GAP 4.5.x, and for GAP 4.N with N in 4,6,7,8,9 I only have the very latest version for testing sitting around).

So, in GAP 4.4.12 this works, and presumably also in all versions <= 4.6.4, but not in 4.6.5 and later.

**Comment by ChrisJefferson** [comment] 2018-07-09 14:19
`StableSortParallel` is usually between 2 and 3 times slower as `SortParallel`, so the cost of making `Sortex` stable isn't excessive, particularly if some people are relying on it.

**Comment by ChrisJefferson** [comment] 2018-07-13 15:55
So, I think we should make sortingperm and sortex both be (a) stable, and (b) efficient. In practice this means they will both be implemented using stablesortparallel (probably sortingperm will just call sortex). I'll write up a patch, including doc cleanup.

**Comment by ChrisJefferson** [comment] 2018-07-19 09:57
#2654 makes `SortEx` stable, and also speeds up `SortingPerm` while at it.

**Comment by ChrisJefferson** [comment] 2018-07-26 20:44
now fixed

**Closed by ChrisJefferson** 2018-07-26 20:44 UTC
