### ISSUE TITLE
Create `MatrixObj` with wrong `BaseDomain`

### ISSUE THREAD

**Issue by mihalova** [gap-system/gap#5133] opened 2022-10-19 14:12 UTC
### Observed behaviour
MatrixObj allows creating a matrix with BaseDomain which is different from the domain of values inside the list.
I used the command `Matrix( R, list )`.
I tried to create the MatrixObj with the parameter `Integers` as `R` and I put a matrix with `Rationals` for the second parameter `list`, e.g. 1/4, 1.5. The GAP created the MatrixObj without checking the domains of the parameters.

### GAP example
```
gap> mat:=Matrix(Integers, [[1.2,1/3,1.4]]);  
<1x3-matrix over Integers>
gap> Print(Matrix(Integers, [[1.2,1/3,1.4]]));
NewMatrix(IsPlistMatrixRep,Integers,3,[ [ 1.2, 1/3, 1.4 ] ])
```

**Comment by ThomasBreuer** [comment] 2022-10-20 14:39
This had been observed already in #4884.

**Comment by fingolfin** [comment] 2023-01-18 12:55
Thanks for the report! We are closing this as a duplicate of #4884.

**Closed by fingolfin** 2023-01-18 12:55 UTC
Labels: kind: bug, gapdays2022-summer
