### ISSUE TITLE
access.tst is broken

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#139] opened 2015-03-30 15:59 UTC
Jenkins tests of HPC-GAP are running out of time on all Jenkins slaves since Friday morning after the following three commits by @ChrisJefferson :
* Clean up GAP signalling
* Add atomic handling to compiler, and alter thread local variable in type1.g
* Use VAL_GVAR/ASS_GVAR in random.g, so we can compile it correctly

I can reproduce this on my machine, but @markuspf can not. Could anyone else reproduce this?
```
gap> Test("tst/access.tst");
Error, Attempt to read object 4324496608 of type list (string) without having r\
ead access in
  <compiled or corrupted statement>  called from 
<compiled or corrupted statement>  called from
<compiled or corrupted statement>  called from
NewType( Fam, IsZmodpZObjSmall and IsModulusRep 
 ) on line 84 of file /Users/alexk/GITREPS/hpcgap/lib/zmodnz.gi called f\
rom
ZmodnZObj( F, 1 
 ) on line 1002 of file /Users/alexk/GITREPS/hpcgap/lib/zmodnz.gi called\
 from
ZmodpZNC( n 
 ) on line 1038 of file /Users/alexk/GITREPS/hpcgap/lib/zmodnz.gi called\
 from
...  at line 0 of *defin*
brk> 
```

**Comment by ChrisJefferson** [comment] 2015-03-30 17:56
Can you see if you can produce the bug with `gap -M`? This should give a better backtrace if it still breaks, and blame the compiler if it doesn't.

**Comment by alex-konovalov** [comment] 2015-03-30 18:10
Yes, I can reproduce it, with a more informative backtrace:
```
gap> Test("tst/access.tst");
Error, Attempt to read object 4324614880 of type list (string) without having r\
ead access in
  if VAL_GVAR( _NEW_TYPE_READONLY )  then
    MakeReadOnlyObj( type );
fi; on line 279 of file /Users/alexk/GITREPS/hpcgap/lib/type1.g called from 
NEW_TYPE( typeOfTypes, family, 
 WITH_IMPS_FLAGS( AND_FLAGS( family!.IMP_FLAGS, FLAGS_FILTER( filter ) 
     ) ), fail 
 ) on line 301 of file /Users/alexk/GITREPS/hpcgap/lib/type1.g called fr\
om
NewType3( TypeOfTypes, arg[1], arg[2] 
 ) on line 344 of file /Users/alexk/GITREPS/hpcgap/lib/type1.g called fr\
om
NewType( Fam, IsZmodpZObjSmall and IsModulusRep 
 ) on line 84 of file /Users/alexk/GITREPS/hpcgap/lib/zmodnz.gi called f\
rom
ZmodnZObj( F, 1 
 ) on line 1002 of file /Users/alexk/GITREPS/hpcgap/lib/zmodnz.gi called\
 from
ZmodpZNC( n 
 ) on line 1038 of file /Users/alexk/GITREPS/hpcgap/lib/zmodnz.gi called\
 from
...  at line 0 of *defin*
brk> 
```

**Comment by stevelinton** [comment] 2015-03-30 18:18
Looks like some missing ` before a string constant. There are a few other examples in *.g, Will fix.

**Comment by ChrisJefferson** [comment] 2015-03-30 18:20
My fault, made a pull request #129 . However, there may well be a whole bunch of other fixes, so I'll let steve go through and make general changes and reject that pull request if he does.

**Comment by stevelinton** [comment] 2015-03-30 18:50
I think this should be fixed in commit 2e19e2c

**Comment by alex-konovalov** [comment] 2015-03-30 19:53
Yes, I've restarted the tests and they are now returning back to normal (no diffs in `testinstall.g` in the main and in a backgound thread). I will close this issue once all tests will complete.

@markuspf, do you think we may add `access.tst` to `testtravis.g` in HPC-GAP?

**Comment by markuspf** [comment] 2015-03-30 20:17
On Mon, Mar 30, 2015 at 12:53:46PM -0700, Alexander Konovalov wrote:
> Yes, I've restarted the tests and they are now returning back to normal (no
> diffs in testinstall.g in the main and in a backgound thread). I will close
> this issue once all tests will complete.
> 
> @markuspf, do you think we may add access.tst to testtravis.g in HPC-GAP?
> 

I don't see why not.

The other thing I don't understand is why I was not able to reproduce this
error on my computer at all.

**Comment by alex-konovalov** [comment] 2015-03-30 22:49
Are you sure that you've recompiled the kernel before trying to reproduce it? If you still have that state of the repository clone around, can you try to start GAP with `-M` and see if it now happens?

**Closed** 2015-03-31 09:01 UTC
Labels: HPC-GAP
