### ISSUE TITLE
CTRL-Z crashes the GAP session

### ISSUE THREAD

**Issue by BNasmith** [gap-system/gap#2879] opened 2018-09-28 00:50 UTC
I have a bad habit of hitting CTRL-Z when I make a mistake typing something. When I do this in a GAP session, it seems to freeze the session. I can't even close the window by clicking the top right corner. I have to find another way to close the GAP session window and start again.

I'd expect that CTRL-Z might do nothing, if it isn't going to undo a mistake. 

Here's my setup, thanks! 
```
 ┌───────┐   GAP 4.9.3 of 05-Sep-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i686-pc-cygwin-default32
 Configuration:  gmp 6.0.0, readline
 Loaded workspace: default
 Packages:   AClib 1.3, Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.10, Browse 1.8.8, CRISP 1.4.4, Cryst 4.1.17,
             CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.1, IO 4.5.2, IRREDSOL 1.4,
             LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.1, RadiRoot 2.8, ResClasses 4.7.1,
             SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, TomLib 1.2.6, TransGrp 2.0.4, utils 0.57
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment] 2018-09-28 13:30
My best guess is that this is something Windows specific -- I constantly use ctrl-Z on Mac OS X to put my GAP session into the background, then resume it using `fg`.

How did you start GAP? From a terminal? Or from a start menu entry or so? In the latter case, perhaps (as somebody who almost never uses Windows, I am merely wildly guessing) the problem might be that there is no underlying shell in which GAP runs -- so of course if one suspends it, there is no other process that could come to the foreground, resulting into the problem...

Anyway, hopefully @ChrisJefferson or @alex-konovalov know more.

**Comment by BNasmith** [comment] 2018-09-28 18:38
I have git install on Windows and load GAP by typing `$ gap.bat` in bash.

**Comment by alex-konovalov** [comment] 2018-09-28 23:35
If you compiled it yourself, then you should be able to start it with `gap.sh` instead of `gap.bat` - could you please try that and check what happens when you press ctrl-Z?

**Comment by alex-konovalov** [comment] 2018-09-29 08:56
@BNasmith thanks for clarifying - you wrote "git install on Windows" so I've assumed that you've compiled it yourself. If this is not the case, then `gap.sh` can not be used to start GAP. 

However, both `gap.bat` and `gapcmd.bat` can be started in Command Prompt - there is no limitation that the former has to be started only in bash. Also, you can navigate to the directory in the graphical file explorer and then double-click on `gap.bat` to start it. It will be interesting to see if it will react differently on ctrl-Z in this case.

**Comment by alex-konovalov** [comment] 2018-09-29 09:07
P.S. I've logged in into a remote Windows VM and can reproduce this, starting GAP by double-clicking on the file in the GUI. It freezes, and does not respond on attempts to close it. I've only managed to close it by closing the auxiliary window hidden beneath it.

**Comment by BNasmith** [comment] 2018-09-29 20:43
That’s all helpful, thanks. (I just mentioned having installed git to explain why I’m using bash, that’s all). I’ll check out mintty and am happy using gapcmd until then. I appreciate it.

**Comment by ChrisJefferson** [comment] 2018-09-30 12:12
We could fairly easily disable ctrl+z, but users who run GAP through bash often use ctrl+z to pause GAP. I don't know if/how we can detect the special case of GAP being run from a .bat file.

I think I have an idea how to fix this, but it won't get fixed until 4.11.

**Comment by ChrisJefferson** [comment] 2022-08-17 11:45
This still happens -- but will be looked at after 4.12 is released as I don't want to break anything so close to the release.

**Comment by fingolfin** [comment] 2023-10-17 07:17
@ChrisJefferson did you ever have a chance to look into this?

**Comment by fingolfin** [comment] 2023-10-17 07:22
As I understand it, the problem is that if GAP is launched via a certain Windows shortcut we install, then there is no bash running "under" GAP -- so pressing ctrl-z, which normally temporarily returns one to the shell from which one launched GAP cannot do that, because, well, GAP was not launched from a shell. As a result, it just freezes.

This sounds to me as if ideally the "shortcut" which starts GAP should be modified in a way to ensure that ctrl-z is ignored -- be it by passing an argument to GAP to tell it to do that, or by some other means -- e.g. I think in a bash script, you can also disable certain signals, so perhaps this can be done this way...

Either way, the idea is that if a "power user" starts GAP from a terminal, they should of course still be able to use ctrl-z.

**Comment by ChrisJefferson** [comment] 2023-10-24 05:10
There is a fix for this over on the windows packaging -- I just disable ctrl+z when GAP is run from the default script

https://github.com/gap-system/gap-windows/pull/6

**Comment by fingolfin** [comment] 2024-01-10 09:29
Should be resolved by https://github.com/gap-system/gap-windows/pull/6

**Closed by fingolfin** 2024-01-10 09:29 UTC
Labels: os: windows, kind: support request
