### ISSUE TITLE
ConjugacyClassesSubgroups fails for SmallGroup(1344,11293)

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#4854] opened 2022-04-07 14:25 UTC
### Observed behaviour
```
gap> ConjugacyClassesSubgroups(SmallGroup(1344,11293));
Error, List Element: <list>[17] must have an assigned value in
  depth > maxdepth at /user/GAP/gap-4.11.1/lib/pcgsperm.gi:814 called from 
ExponentsOfPcElementPermGroup( pcgs, g, 1, Maximum( poss ), 'e' 
 ) at /user/GAP/gap-4.11.1/lib/pcgsperm.gi:1262 called from
ExponentsOfPcElement( ParentPcgs( pcgs ), elm, pcgs!.depthsInParent 
 ) at /user/GAP/gap-4.11.1/lib/pcgsind.gi:1472 called from
ExponentsOfPcElement( ocr.modulePcgs, x 
 ) at /user/GAP/gap-4.11.1/lib/onecohom.gi:264 called from
ocr.moduleMap( n ) at /user/GAP/gap-4.11.1/lib/onecohom.gi:1037 called from
OCEquationVector( ocr, rels[i] ) at /user/GAP/gap-4.11.1/lib/onecohom.gi:1247 called from
...  at *stdin*:1
type 'quit;' to quit to outer loop
```
### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.11.1 of 2021-03-02
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 5.1.3, GASMAN
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.4, PrimGrp 3.4.1, SmallGrp 1.4.2, TransGrp 3.0
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment] 2022-04-07 17:29
Works fine in master

**Comment by hulpke** [comment] 2022-04-09 14:13
Since this is already fixed in master, I close

**Comment by fingolfin** [comment] 2022-07-28 16:44
I can confirm this:
```
$ ./gap -A
 ┌───────┐   GAP 4.12dev-1388-g3ef5404-dirty built on 2022-07-28 15:57:10+0200
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: aarch64-apple-darwin21-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.5, PrimGrp 3.4.2, SmallGrp 1.5, TransGrp 3.6.2
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> ConjugacyClassesSubgroups(SmallGroup(1344,11293));
Error, List Element: <list>[17] must have an assigned value in
  depth > maxdepth at GAPROOT/lib/pcgsperm.gi:816 called from
ExponentsOfPcElementPermGroup( pcgs, g, 1, Maximum( poss ), 'e'
 ) at GAPROOT/lib/pcgsperm.gi:1264 called from
ExponentsOfPcElement( ParentPcgs( pcgs ), elm, pcgs!.depthsInParent
 ) at GAPROOT/lib/pcgsind.gi:1475 called from
ExponentsOfPcElement( ocr.modulePcgs, x
 ) at GAPROOT/lib/onecohom.gi:264 called from
ocr.moduleMap( n ) at GAPROOT/lib/onecohom.gi:1037 called from
OCEquationVector( ocr, rels[i]
 ) at GAPROOT/lib/onecohom.gi:1247 called from
...  at *stdin*:1
type 'quit;' to quit to outer loop
brk>
```

**Comment by fingolfin** [comment] 2022-07-28 16:49
With assertions turned up a bit:
```
gap> SetAssertionLevel(1);
gap> ConjugacyClassesSubgroups(SmallGroup(1344,11293));
Error, Assertion failure in
  KernelOfMultiplicativeGeneralMapping( fphom ) = nts[j] at GAPROOT/lib/grplatt.gi:1192 called from
LatticeSubgroups( G ) at GAPROOT/lib/grplatt.gi:208 called from
<function "ConjugacyClassesSubgroups group">( <arguments> )
 called from read-eval loop at *stdin*:2
you may 'return;'
brk>
```

**Closed** 2022-09-07 12:41 UTC
Labels: kind: bug, kind: bug: unexpected error
