### ISSUE TITLE
libgap: what data in the libgap-calling functions must be declared volatile? other pitfalls?

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#2893] opened 2018-10-04 08:46 UTC
My libgap-calling code manages to cause infinite recursion in `PRINT_OR_APPEND_TO_STREAM`: it cannot [open `stream`](https://github.com/dimpase/gap/blob/5858540994c8a1df9dacbc2a5125fc5a8051e4bb/src/streams.c#L859), tries to `ErrorQuit` few lines later, `ErrorQuit` in turns call `PRINT_OR_APPEND_TO_STREAM`, again it cannot open the stream, etc etc.

The (long) code causing this is [here](https://trac.sagemath.org/ticket/22626) - I probably can produce a reasonably short C code illustrating this (by design, it does call libgap with quite a few invalid inputs, causing errors and processing them in a callback), but I'd rather try to fix things first...

While this potential infinite recursion in itself is a sort of bug in (lib)gap, could it be that my code violates some unwritten rules, e.g. does not use `volatile` for some data that needs it? Other pitfalls of this sort?  

Would it matter if the caller is multi-threaded (which is the case for me) and calls libgap in different threads?

**Comment by fingolfin** [comment] 2018-10-04 10:21
If you call GAP from multithreaded code, then you as caller must take care that no two such calls can run simultaneoulsy, e.g. via a lock, else all hell will break loose.

**Comment by fingolfin** [comment] 2020-10-13 12:19
The issue you describe at the start sounds like a duplicate of #3028 which should be fixed in GAP 4.11. There are no other API considerations to mention, but keep in mind that GAP is strictly single threaded, and hence so is libgap. Callers have to take care to call it from at most one thread at a time (or possibly even restrict all calls to it to a single thread).

**Closed by fingolfin** 2020-10-13 12:19 UTC
Labels: kind: discussion, topic: libgap
