### ISSUE TITLE
Cleanup of DirectoryTemporary() after being called from a function?

### ISSUE THREAD

**Issue by becky82** [gap-system/gap#194] opened 2015-07-24 12:22 UTC
Consider the function:

    f:=function()
      local tmpdir;
      tmpdir := DirectoryTemporary();
      return 1;
    end;;

Every time it is called, it creates a new temporary directory in my /tmp directory (I'm on Ubuntu).  These temporary directories remain until we quit GAP (assuming we can do so cleanly).  As far as I know, tmpdir is no longer usable after the function exits.  Can we delete these directories upon the function exiting?

With a repeatedly called function, I ended up with 1 million+ of these temporary directories.  [Yes, in hindsight, I realize I should have made a single global tmpdir.]

**Comment by ChrisJefferson** [comment] 2015-07-24 12:42
Unfortunately, this is impossible (or at least, almost impossible). We can't know in general if there are no more references to the result of `DirectoryTemporary()`, as someone could take a copy of it. Also we can't just clean up one temporary directory when another is made, as some libraries make a `DirectoryTemporary` to keep their own data in.

However, there are two changes I can think of that could help:

1) We could provide a function to allow early clean up of a directory returned by `DirectoryTemporary`, so users can manually clean up after themselves.

2) Produce a warning if too many (> 10,000? ) temporary directories are made, as the user (or a library they are using) is probably doing something wrong.

**Comment by alex-konovalov** [comment] 2015-07-24 23:24
@becky82 could you please say a bit more about the purpose of these temporary directories? Is this, by any chance, GAP interacting with some external software?

**Comment by becky82** [comment] 2015-07-24 23:49
@alex-konovalov That's right, I call an external program: dreadnaut, for isomorphism testing (via nauty).

I'm studying the autotopism groups of partial Latin rectangles up to isomorphism.  I wrote a function that returns this group by (a) generating a graph whose automorphism group is isomorphic to the autotopism group of the partial Latin rectangle, (b) calling dreadnaut via Process(...) to give me the generators of the graphs's automorphism group.  I then use StructureDescription to classify these groups.  The problem is that I had 1,000,000+ partial Latin rectangles I wanted to classify.

Switching to the global variable fixed all the problems, and it runs much faster too.

One problem with generating so many temporary directories, is that Ubuntu (which I use) deletes them on startup (by default).  This takes a very long time, and led me to believe that Ubuntu was failing to reboot (and I ended up reinstalling the operating system as a result).  [Ordinarily, GAP deletes the directories on exit, but my computer became unstable (I think as a result of all these directories), so I had to force-quit GAP.]

**Comment by alex-konovalov** [comment] 2015-07-31 21:02
@becky82 thanks for further details - glad that it now works better. So, may this issue be now closed as resolved?

**Comment by becky82** [comment] 2015-08-01 00:55
The problem is resolved _for me_, as I'm now aware of how it arises.  But it took me months to work out what was going on (when my computer crashed and wouldn't restart, I thought the problem was with Ubuntu), and I wasted a lot of time on trying to fix this.  What if it happens to someone else?

The suggestion by @ChrisJefferson (that it produces a warning if too many temporary directories are created) seems reasonable to me.  It at least gives the user something to work with.

**Comment by stevelinton** [comment] 2015-09-05 07:32
PR #203 adds a warning. In implementing this I noticed that RemoveDir doesn't handle directory objects. I'll raise that as a separate issue.

**Comment by markuspf** [comment] 2015-09-20 15:23
I'll close this as the issue is resolved.

**Closed by markuspf** 2015-09-20 15:23 UTC
