### ISSUE TITLE
Successive Calls to `Stabilizer` Yield Different, Incorrect Results

### ISSUE THREAD

**Issue by pietroglyph** [gap-system/gap#5474] opened 2023-07-14 02:13 UTC
### Observed behaviour
I have the following minimal[^1] example of a finitely-presented group and an action on the set $`\{-1, 1\}`$:
```gap
F := FreeGroup("r", "f", "h", "v"); AssignGeneratorVariables(F);
G := F / [r^2, f^2, (r*f)^2, h^2, v*h*(h*v)^-1, h*f*(f*h)^-1, v*f*v*f^-1, (r^-1)*h*r*v, (r^-1)*v*r*h^-1];

action := function(s, g)
    local phi, w, lrs, lr, sgn;

    # Decompose g into a list of generator indices; negative indices correspond inverses of generators
    phi := EpimorphismFromFreeGroup(G : surjective);
    w := PreImagesRepresentative(phi, g);
    lrs := LetterRepAssocWord(w);

    for lr in lrs do
        lr := AbsInt(lr);

        if lr = 1 then # r
            s := -s;
        elif lr = 4 then # v and v^-1
            s := -s;
        fi;
    od;
    return s;
end;

# The element we're stabilizing sometimes seems to matter for larger G-sets, but this breaks for everything in S = [1, -1]
S := [-1, 1];
s := 1;
```

1. If I compute the stabilizer of the same element twice _and_ I call `Elements` after[^2] each call, then I get different subgroups. I.e., the following code prints `false`:
    ```gap
    stab_1 := Stabilizer(G, S, s, action); Elements(stab_1);
    stab_2 := Stabilizer(G, S, s, action); Elements(stab_2);
    Print(stab_1 = stab_2, "\n");
    ```

2. The call to `Elements` doesn't seem to be the only thing that causes this behavior. If call `Stabilizer`, then `Index`, and then `Stabilizer`[^3], then the subgroup returned the second time (and on every call after the second call) has an incorrect index in $G$, and the two subgroups are not equal. I.e., the following code prints `true, false, false`:
    ```gap
    # If you ran the previous block, clear your environment and run the first code block and then this
    stab_1 := Stabilizer(G, S, s, action);
    Print(Index(G, stab_1) = Order(G) / Order(stab_1), ", ");
    stab_2 := Stabilizer(G, S, s, action);
    Print(Index(G, stab_2) = Order(G) / Order(stab_2), ", ");
    Print(stab_1 = stab_2, "\n");
    ```
    The incorrect index behavior seems to be caused by calling `EpimorphismFromFreeGroup` on every group element! In particular, this prints `false`:
    ```gap
    # If you ran the previous blocks, clear your environment and run the first code block and then this
    phi := EpimorphismFromFreeGroup(G : surjective); List(G, g -> PreImagesRepresentative(phi, g));
    stab := Stabilizer(G, S, s, action);
    Print(Index(G, stab) = Order(G) / Order(stab), "\n");
    ```

3. Finally, it's worth noting that none these stabilizers aren't even correct if I run `Stabilizer` more than once:
    ```gap
    # If you ran the previous blocks, clear your environment and run the first code block and then this
    Print(-s in List(Stabilizer(G, S, s, action), g -> action(s, g)), ", ");
    Print(-s in List(Stabilizer(G, S, s, action), g -> action(s, g)), "\n");
    ```
    Once again, this seems to be caused by running `EpimorphismFromFreeGroup` on all the group elements before the call to `Stabilizer`! For example, this prints `true`:
    ```gap
    # If you ran the previous blocks, clear your environment and run the first code block and then this
    phi := EpimorphismFromFreeGroup(G : surjective); List(G, g -> PreImagesRepresentative(phi, g));
    Print(-s in List(Stabilizer(G, S, s, action), g -> action(s, g)), "\n");
    ```

### Expected behaviour
I have checked that my action is well-defined by running the following code:
```gap
Assert(0, not false in ListX(S, G, G, {x, g, h} -> action(action(x, g), h) = action(x, g*h)));
```
Given this, I would expect to get a correct stabilizer, and I would expect `Stabilizer` to be well-defined as a function, and for repeated calls to `Stabilizer` to yield the same results and have correct properties (e.g. correct index in $G$).

I suspect that there's some underlying global state, or that `action` has side effects on something mutable (I suspected `G` to be the culprit, but I can't seem to work around this issue with `StructuralCopy`), but I don't really know the GAP internals well enough to go any farther. I hope someone else can make some more sense of this.

### Copy and paste GAP banner
```
 ┌───────┐   GAP 4.12.2 of 2022-12-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.6, AutPGrp 1.11, Browse 1.8.19, CRISP 1.4.6, Cryst 4.1.25,
             CrystCat 1.1.10, CTblLib 1.3.4, curlInterface 2.3.1, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.9,
             GAPDoc 1.6.6, genss 1.6.8, IO 4.8.0, IRREDSOL 1.4.4, LAGUNA 3.9.5, orb 4.9.0, Polenta 1.3.10,
             Polycyclic 2.16, PrimGrp 3.4.3, RadiRoot 2.9, recog 1.4.2, ResClasses 4.7.3, SmallGrp 1.5.1,
             Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.3, utils 0.81
```

[^1]: I successfully simplified the set being acted upon, but I could not further simplify the presentation―i.e., if I use an equivalent, simpler presentation like $\langle r, f \mid r^2, f^2, (rf)^2 \rangle$, then I cannot reproduce this issue.
[^2]: If I don't call `Elements`, or I call it after _both_ calls to `Stablizer` then this doesn't happen!
[^3]: Once again, the order of the calls seems to be very important; if I move these print statements to after all the `Stabilizer` calls then I get `true, true, true` (but the stabilizer is still wrong).

**Comment by fingolfin** [comment] 2023-07-18 16:05
I can reproduce the bug in GAP 4.12.2, but this is fixed in `master` (and so will be fixed in the upcoming GAP 4.13.0 release).

I don't know right now which change fixed it.

**Comment by pietroglyph** [comment] 2023-07-27 18:58
@fingolfin I just built GAP from `master` (commit `fc03bf2ccfc8273ec201be99739073eb0d634771`), and the issue seems to persist. This is my GAP banner:

```
 ┌───────┐   GAP 4.13dev built on 2023-07-27 14:05:33-0400
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv9
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.6, AutPGrp 1.11, Browse 1.8.21, CaratInterface 2.3.5, CRISP 1.4.6, Cryst 4.1.26, CrystCat 1.1.10,
             CTblLib 1.3.6, curlInterface 2.3.2, FactInt 1.6.3, FGA 1.5.0, Forms 1.2.9, GAPDoc 1.6.6, genss 1.6.8, IO 4.8.1, IRREDSOL 1.4.4, LAGUNA 3.9.6,
             orb 4.9.0, Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.4, RadiRoot 2.9, recog 1.4.2, ResClasses 4.7.3, SmallGrp 1.5.3, Sophus 1.27,
             SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.4, utils 0.82
```

Am I missing something?

**Comment by fingolfin** [comment] 2023-07-28 00:41
@pietroglyph my apologies, you are right; I must have screwed up somehow when I originally run the test. But yes, I can now also reproduce it with `master`.

The problem is that you action is not well-defined... which took me some time to understand. I first run my standard test, which it passed.
```
gap> SetX([1,-1], G, G, {s,g,h} -> action(action(s,g),h)=action(s,g*h));
[ true ]
```
Then I eliminated use of `EpimorphismFromFreeGroup` by replacing
```
    phi := EpimorphismFromFreeGroup(G : surjective);
    w := PreImagesRepresentative(phi, g);
```
in your action with
```
    w := UnderlyingElement(g);
```
Then I started playing around and thinking, and realized your action is not well-defined after all: you are relying on some word representing the group elements, but those are of course not unique. So let's evaluate your action on the relators of the group -- those all represent the identity in the group and hence should act trivial, but they don't:
```
gap> AssignGeneratorVariables(G);
#I  Global variable `r' is already defined and will be overwritten
#I  Global variable `f' is already defined and will be overwritten
#I  Global variable `h' is already defined and will be overwritten
#I  Global variable `v' is already defined and will be overwritten
#I  Assigned the global variables [ r, f, h, v ]
gap> rels:=[r^2, f^2, (r*f)^2, h^2, v*h*(h*v)^-1, h*f*(f*h)^-1, v*f*v*f^-1, (r^-1)*h*r*v, (r^-1)*v*r*h^-1];
[ r^2, f^2, (r*f)^2, h^2, v*h*v^-1*h^-1, h*f*h^-1*f^-1, v*f*v*f^-1, r^-1*h*r*v, r^-1*v*r*h^-1 ]
gap> List(rels, g -> action(1,g));
[ 1, 1, 1, 1, 1, 1, 1, -1, -1 ]
```

Your last two relations are not compatible with the action (or the other way around). Indeed, they both contain the generators `r` and `v` three times, this should be an even number for the action to be well-defined.

**Closed** 2023-07-31 17:13 UTC
Labels: status: invalid
