### ISSUE TITLE
clang on OSX 10.9.5 (clang-600.0.54) crashes while compiling opers.c (gap 4.10.2)

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#3762] opened 2019-11-26 09:15 UTC
from report to support@gap 2019/11/25 by Heinrich Schutze:
`clang: error: unable to execute command: Floating point exception: 8`
in more details:

```
C src/objset.c  obj/src/objset.lo\
C src/opers.c  obj/src/opers.lo\
Stack dump:\
0. Program arguments:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-cc1 -triple x86\_64-apple-macosx10.9.0 -emit-obj -disable-free
-disable-llvm-verifier -main-file-name opers.c -mrelocation-model pic
-pic-level 2 -mdisable-fp-elim -relaxed-aliasing -masm-verbose
-munwind-tables -target-cpu core2 -target-linker-version 241.9 -gdwarf-2
-coverage-file
/Users/heinrichschutze/Downloads/gap-4.10.2/obj/src/.libs/opers.o
-resource-dir
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0
-dependency-file obj/src/.deps/opers.d -MP -MT obj/src/opers.lo
-isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
-D HAVE\_CONFIG\_H -D PIC -I ./gen -I ./src -I
/Users/heinrichschutze/Downloads/gap-4.10.2/extern/install/gmp/include
-O2 -Wall -Wextra -Wundef -Wwrite-strings -Wpointer-arith
-Wredundant-decls -Wno-unused-parameter -Wmissing-field-initializers
-Wformat=2 -Wold-style-definition -Wformat-nonliteral -Wformat-security
-Wno-sign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked
-Wmissing-format-attribute -Winit-self -Wmissing-include-dirs
-Warray-bounds -Wreturn-type -Wno-implicit-fallthrough -Wno-inline
-Wnested-externs -Wimplicit-function-declaration
-Wno-error=unused-parameter -Wno-error=sign-compare
-Wno-error=implicit-fallthrough -Wno-error=inline -fconst-strings
-fdebug-compilation-dir /Users/heinrichschutze/Downloads/gap-4.10.2
-ferror-limit 19 -fmessage-length 150 -stack-protector 1 -mstackrealign
-fblocks -fobjc-runtime=macosx-10.9.0 -fencode-extended-block-signature
-fno-common -fdiagnostics-show-option -fcolor-diagnostics
-vectorize-loops -vectorize-slp -o obj/src/.libs/opers.o -x c
src/opers.c\
1. <eof> parser at end of file\
2. Per-module optimization passes\
3. Running pass 'CallGraph Pass Manager' on module 'src/opers.c'.\
clang: error: unable to execute command: Floating point exception: 8\
clang: error: clang frontend command failed due to signal (use -v to see
invocation)\
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)\
Target: x86\_64-apple-darwin13.4.0\
Thread model: posix\
```

**Comment by ChrisJefferson** [comment] 2019-11-26 09:44
While this is a harsh answer, my initial thought is this is an old compiler which I guess has a bug in it (which are often hard to fix), and I'm not sure we want to put serious work into trying to fix compiling on an OS which has been unsupported for 3 years. Is the bug only occuring there (that we know of)?

**Comment by fingolfin** [comment] 2019-11-26 09:45
This error means you hit upon a bug in the compiler.

According to <https://trac.macports.org/wiki/XcodeVersionInfo> and <https://gist.github.com/yamaya/2924292>, `clang-600.0.54` is part of Xcode 6.1. However, two updates for this exist that work on macOS 10.9.5, namely Xcode 6.1.1 (with `clang-600.0.56`) and Xcode 6.2 (with `clang-600.0.57`).

So the first thing I would recommend is to try and update to the latest Xcode available for your system. To be honest, I am not sure how the best way for this is on 10.9, I never used 10.9 (I skipped from 10.8 to 10.11). Perhaps it already was installed via the App Store, then updating could be as simple as going there and updating Xcode.

If Xcode was installed manually, you can update it manually as follows:
1. Go to <https://download.developer.apple.com/>
2. Log in with your Apple ID
3. Download the file from <https://download.developer.apple.com/Developer_Tools/Xcode_6.2/Xcode_6.2.dmg>
4. Open the dmg, run the installer
5. Start Xcode, and install the command line tools. (this is vital to get the newer compiler)

**Comment by fingolfin** [comment] 2019-11-26 09:46
@ChrisJefferson lots of people have older hardware that doesn't allow installing a newer OS. That said, yeah, I wouldn't consider this bug a top priority. Doesn't mean we can't at least *try* to help...

**Comment by fingolfin** [comment] 2019-11-26 09:49
Anyway, if installing a newer Xcode and newer compiler doesn't help, then there are several other avenues one can try:
1. If your hardware permits, consider upgrading  to a newer macOS version (it's free), and then an even newer Xcode (10.9 and 10.10 were rather buggy, which is why I skipped them, and used 10.11 for a long time, which I can recommend; I later skipped 10.12 and 10.13 and am now on 10.14. And hope I can skip 10.15, which is buggy as hell... *sigh*)
2. Perhaps the issue is fixed in GAP 4.11.0 "by chance" (as the code changed), so you could try that (it'll be released "soon" -- right, @alex-konovalov ?)
3. You could use Homebrew, MacPorts, Fink, ... to install a different compiler, and then instruct GAP to use that; but this requires quite some knowledge about using the command line.

**Comment by dimpase** [comment] 2019-11-26 09:53
> lots of people have older hardware that doesn't allow installing a newer OS

yep, e.g. my Macbook Air is stuck on MacOS 10.13. Newer MacOS versions don't work on it.

**Comment by ChrisJefferson** [comment] 2019-11-26 09:55
Sorry yes, trying different compilers is a sensible choice, but I don't really want to try to find a copy of the OS/compiler to fix the actual problem

**Comment by fingolfin** [comment] 2019-11-26 10:34
@ChrisJefferson I agree that it doesn't make sense for us to try to find a workaround for this compiler bug.

**Comment by fingolfin** [comment] 2019-12-16 09:47
Closing this, as we agreed that we don't intend to spend effort for looking into workarounds for this bug in an outdated compiler. The discussion will of course stay around, so that we can point any other people here who might run into this.

**Closed** 2020-01-06 08:36 UTC
Labels: priority: low, topic: build system
