### ISSUE TITLE
ConstructAllSolvableNonNilpotentGroups inconsistent result

### ISSUE THREAD

**Issue by BrauerSuzuki** [gap-system/gap#5379] opened 2023-02-13 18:46 UTC
The following email was sent to the GAP Forum without getting a response so far:

CG:=ConstructAllSolvableNonNilpotentGroups(5184);;

returns a list of PcGroup codes (as far as I understand). Some groups could not be distinguished, so CG contains some lists of numbers. In any event the total number of non-isomorphic solvable non-nilpotent groups of order 5184 cannot be bigger than
Size(Flat(CG));
292238

However, on Max Horn's homepage the number is given as 292308. Which number is correct?
I'm using GAP 4.12.0 and GrpConst 2.6.3

**Comment by fingolfin** [comment] 2023-02-14 15:24
Thanks, I missed that mail on the list it seems.

Of course it is possible both numbers are wrong *shrug*.

I just dug out my old datafiles, and they really report 292308 solvable non-nilpotent groups of order 5184. It is of course conceivable that there is/was a bug in GAP or grpconst that affected either your computation or mine. It was done in 2016 (I'll have to dig a bit more to see which precise GAP and grpconst versions).

I'll look more into this, and will in particular also re-run `ConstructAllSolvableNonNilpotentGroups` both with current GAP and the old GAP version to see what went one. This may take me a few days.

**Comment by fingolfin** [comment] 2023-02-15 23:43
I have now re-run `ConstructAllSolvableNonNilpotentGroups(5184);` with the current GAP master and GrpConst 2.6.3, and after about 30 hours I got this:
```
gap> Length(CG);
291996
gap> Length(Flat(CG));
292308
```
suggesting that the real number is between 291996 and 292308 -- note that the latter number is consistent with what I report on my website.

I will repeat this with GAP 4.12.0 and 4.12.2 and perhaps some older versions.

I will also dig out my code which resolved the undecided isomorphisms (IIRC it does so by checking a few more invariants and then calling `IsomorphismGroups`). This can take a lot of time, too. I just tried this with a few random pairs, it took 2-5 seconds on the computer I do this. There are ~300 unresolved pairs and so half an hours work should resolve them, hopefully confirming my original result
```
gap> Collected(List(Filtered(CG,IsList),Length));
[ [ 2, 274 ], [ 3, 13 ], [ 4, 4 ] ]
```

This leaves the question why you got different numbers... This is why I say I'll repeat the experiment with stock GAP 4.12.0, just in case there is a bug in some component of that GAP version that causes this, it'd be good to know that.

In the meantime you may wish to redo the computation with GAP 4.12.2

And I will look into publishing my data collection...

**Comment by fingolfin** [comment] 2023-02-15 23:44
@BrauerSuzuki BTW can you please also tell me more about the computer on which you performed the experiment? In particular:
- Which OS?
- What kind of CPU?
- Which compiler was used to compile GAP?
- How much RAM does it have?
- Did you run memcheck or a similar tool on it to exclude the possibility of faulty RAM?

**Comment by BrauerSuzuki** [comment] 2023-02-16 06:12
Thanks! I'm using Ubuntu 20.04 with kernel 5.4.0. CPU is i5-8500 and 8GB RAM. The compiler was probably gcc 9.4.0. I have never done a memcheck (it's my office machine). I will do a rerun (or a memcheck), but at the moment the machine is busy with another computation.

**Comment by fingolfin** [comment] 2023-02-17 11:02
I have now completed yet another run with GAP master, on a different machine, which also confirms my old results.

Two more machines are re-running the computation with stock GAP 4.12.0 (to match your setup), and two are re-running it with stock GAP 4.9.1, which is reasonably close to what I used in November 2016. Well, technically, the current GAP release at that point was GAP 4.8.6; but it shipped with GrpConst 2.5.0, which did not yet have `ConstructAllSolvableNonNilpotentGroups`; I only added that in 2.6.0. Most likely I was using a dev version of GAP and of GrpConst at that point. Perhaps I can set up a run with that config, too.

**Comment by fingolfin** [comment] 2023-02-17 11:29
I've started two more runs with GAP 4.8.6 plus GrpConst 2.6.0

**Comment by BrauerSuzuki** [comment] 2023-02-17 17:39
Thanks again for your effort. So it seems my system is screwed. Did you apply Alex Hulpke's recent patches? If I remember correctly, I applied the one on IsomorphismGroups (around Christmas), but not the last one from January. This shouldn't be relevant I think.

**Comment by fingolfin** [comment] 2023-02-18 22:02
All 6 additional machines confirmed 292308 as upper bound for the correct result.

I will now run the code to resolve the tuples of potentially isomorphic groups.

**Comment by fingolfin** [comment] 2023-02-18 22:47
OK, all six computations now also confirmed 292308 as the exact count. The one with 4.8.6 is much slower (Alexander Hulpke back then improve the isomorphism testing code for our computations, and 4.8.6 does not have those improvements, and it shows).

Just to mention some timings (just because I greatly enjoy how much @hulpke made things faster): I resolved all tuples with invariants, except for three pairs, for which I resort to `IsomorphismGroups`. Time taken with GAP 4.12.0: ~19 seconds; with 4.9.1: ~40 seconds; with GAP 4.8.6: ~700 seconds resp. ~1700 seconds (!! due to a differing random number seed I accidentally introduced in one 4.8.6 session).

Regarding patches: I did not apply any "patches", but rather I either used the stock versions I indicated, or (for the first two computations) the `master` branch (so any of Alexander's patches that were merged by then were in effect). However, that particular patch fix an "unexpected break loop", so the bug it fixed can't ever lead to wrong results, just to aborted calculations.

**Comment by hulpke** [comment] 2023-02-19 04:04
Thank you, @fingolfin for going all the way back to check.

**Comment by hulpke** [comment] 2023-02-19 14:44
Oh, and just for curiosity, who is @BrauerSuzuki -- the account has no real name attached?

**Comment by BrauerSuzuki** [comment] 2023-02-19 18:49
Benjamin Sambale. I created this account for other reasons, but I'm not (yet) really active on github.

**Comment by BrauerSuzuki** [comment] 2023-02-19 19:06
Now I have rerun my computation and this time I get indeed the numbers Max got. Not sure what happened the first time. Sorry for the noise!

**Comment by hulpke** [comment] 2023-02-19 20:32
Danke @BrauerSuzuki

**Closed** 2023-02-19 21:21 UTC
