### ISSUE TITLE
MemoryUsage just returns a constant if the argument is a word

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#897] opened 2016-09-21 19:42 UTC
### Observed behaviour

gap> F := FreeGroup(3);;
gap> w := One(F);;
gap> for i in [1..10000] do w := w \* Random(GeneratorsOfGroup(F)); od;
gap> MemoryUsage(w);
40
gap> MemoryUsage(ExtRepOfObj(w));
120248
### Expected behaviour

gap> F := FreeGroup(3);;
gap> w := One(F);;
gap> for i in [1..10000] do w := w \* Random(GeneratorsOfGroup(F)); od;
gap> MemoryUsage(w); # approximately!
120248
### Copy and paste GAP banner (to tell us about your setup)

 ┌───────┐   GAP 4.8.4, 04-Jun-2016, build of 2016-06-10 15:51:35 (CEST)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small\* 1.0, id\* 1.0
 Packages:   GAPDoc 1.5.1

**Comment by ChrisJefferson** [comment] 2016-09-21 20:06
The problem is that the object isn't a `IsPositionalObjectRep`, but is really (the data is stored in `![1]`). I'm not sure what exactly is going wrong, and where this should be fixed.

**Comment by frankluebeck** [comment] 2016-09-22 08:39
According to section `?NewRepresentation`  it seems to be a bug that the representation `IsBLetterAssocWordRep` is not a subrepresentation of `IsPositionalObjectRep`. After changing the declaration (in `wordass.gd`) to
```
DeclareRepresentation( "IsBLetterAssocWordRep", 
                        IsLetterAssocWordRep and IsPositionalObjectRep, [] );
```
`MemoryUsage` works as expected in the above example.

There are probably other similar bugs in that file. It would be good if someone could have a look who knows more about these various representations than me.

**Comment by stevelinton** [comment] 2016-10-27 09:28
We should be able to scan for representations that are not descended from IsInternalRep, IsPositionalObjectRep, IsComponentObjectRep or IsDataObjectRep.

**Comment by markuspf** [comment] 2016-10-27 11:58
We have: 
 - `IsSyllableAssocWordRep`
 - `IsLetterAssocWordRep`
 - `IsBLetterAssocWordRep`
 - `IsWLetterAssocWordRep` 
 - `IsPermGroupGeneralMapping`
 - `IsSubgroupOfWholeGroupByQuotientRep`
 - `IsGenericCharacterTableRep`
 - `IsNullMapMatrix` 
 - `IsDefaultGeneralMappingRep`
 - `IsInverseGeneralMappingRep`
 - `IsMemberPcSeriesPermGroup`
 - `IsSlicedPerm`
 - `IsSlicedPermInv`
 - `IsFromTheLeftCollectorRep`
 - `IsGroupClassByListRep`
 - `IsNilpotentLieAutomorphismRep`

(Found by filtering `AllRepresentations()` by not having any of the four Reps above in their IMPL_FLAGS, `AllRepresentations()` being a function I just added to the library).

**Comment by fingolfin** [comment] 2016-12-28 11:48
I was bitten by this yesterday, as polycyclic's `IsFromTheLeftCollectorRep` suffers from the same problem (and thus a collector was shown to use 300 bytes of RAM when it really are 300,000 bytes...)

So all in all, it seems that `IsPositionalObjectRep` serves no useful purpose, other than perhaps to increase some ranks a little bit. It is not well-documented either: entering `?IsPositionalObjectRep` gives nothing, though it is mentioned in section 79.11 "Positional Objects".

So, what to do? Some random ideas (without consideration how easy and/or efficient it would be to implement them)

1. Change GAP to automatically add set `IsInternalRep`, `IsPositionalObjectRep`, `IsComponentObjectRep`, `IsDataObjectRep` for objects based on their TNUMs.
2. Change `NewRepresentation` to enforce that every newly declared representation sets on of the four representation types
3. Phase out those four types *as filters*, instead add replacement functions which inspect the TNUMs (or something like that) to give an appropriate answer.
4. A combination of the above.
5. ... other ideas?

Idea 1 might work by hooking into `Objectify` resp. `SetTypeObj`, which already has to look at the object in order to invoke `SET_TYPE_POSOBJ` or `SET_TYPE_COMOBJ`. So adding in the correct filters would be doable there. Some caveats: This would change some filter ranks and could thus lead to some indirect breakage (arguably caused by unsafe reliance on certain relative filter ranks, but breakage nevertheless). 
Moreover, this could require creating a new type object on the fly (?), again and again, which is inefficient.

Approach 2 would help to avoid that inefficiency, by inspecting the (currently unused, see issue #1042) `slots` argument to `NewRepresentation`. Alas, that does not always work, and since the argument has been unused so far, it is quite likely that somebody used it incorrectly, and thus this heuristic will fail :-(.

Approach 3 avoids all that mucking around with filters, and is fast and reliable. However, it would not allow for method dispatch. But then, I think few (if any things) rely on that with the exception perhaps of some very special things like `MemoryUsage` (a notable exception here is `IsFFE and IsInternalRep` which is used quite a bit in the library).

We could also combine these, say do approach 1, but instead of changing the type, print an InfoWarning to help us track down incorrect representation declarations and fix them. Or print the warning *and* change the type. Etc.

**Comment by fingolfin** [comment] 2016-12-28 11:51
In the meantime, we already have 3 in the form of the kernel functions `IS_COMOBJ`, `IS_POSOBJ`, `IS_DATOBJ`. I'll create a PR which improves MemoryUsage with the help of those.

**Comment by fingolfin** [comment] 2016-12-28 12:14
Note: I removed my last two comments in favor of a separate issue (see #1043). Should have done that from the start. Sorry for the noise.

**Closed** 2017-01-13 16:52 UTC
