### ISSUE TITLE
Problem with special characters when running a local html file with Exec()

### ISSUE THREAD

**Issue by mohammadfarrokhi** [gap-system/gap#3667] opened 2019-09-19 08:58 UTC
The command Exec() works well when running an online web page but it does not send special characters correctly when running a local html file.

Here is an example.

```
gap> Exec("C:/Opera/launcher.exe http://g.ivank.net/index.html#3:1-2,2-3"); 
gap> Exec("C:/Opera/launcher.exe C:/g.ivank.net/index.html#3:1-2,2-3"); 
```
The first line open the browser with link "http://g.ivank.net/index.html/#3:1-2,2-3"" correctly while the second line open the browser with the link "C:/g.ivank.net/index.html%233:1-2,2-3" with # replaced by %23. The local link works well when %23 is replaced with #. This happen for other special characters too like ? and ;.

```
C:\Users\Gunron>C:\gap\gap.exe -l /proc/cygdrive/C/gap
┌───────┐   GAP 4.10.2 of 19-Jun-2019
│  GAP  │   https://www.gap-system.org
└───────┘   Architecture: i686-pc-cygwin-default32-kv3
Configuration:  gmp 6.1.2, readline
```

**Comment by ChrisJefferson** [comment] 2019-09-19 10:44
This might be a case of "works as intended". What happens if you try typing your commands into a command shell (or whatever windows calls it nowadays. `cmd.exe`?). We should just be passing what you write to that. Could you check if this is cmd, or opera, doing something weird?

**Comment by mohammadfarrokhi** [comment] 2019-09-19 11:34
Any of the following command, including special characters, works correctly:

```
Exec("cmd /?");
Exec("cmd /c notepad c:/###.txt");
Exec("notepad c:/###.txt");
```

**Comment by ChrisJefferson** [comment] 2019-09-19 14:47
But do the opera lines you mention work if you type them straight into a windows command line, outside of GAP?

**Comment by mohammadfarrokhi** [comment] 2019-09-19 19:20
I have the same problem running the command "C:/Opera/launcher.exe C:/g.ivank.net/index.html#3:1-2,2-3" in cmd while the command "C:/Opera/launcher.exe http://g.ivank.net/index.html#3:1-2,2-3" works correctly in cmd. It seems the problem is cmd.

**Comment by ChrisJefferson** [comment] 2019-09-20 07:15
It would be good to have a better way to open webpages, where we could handle this.

I suspect the problem in this case is that `#` is a valid symbol in a filename, so the browser is trying to "helpfully" access a file with `#` in it's name, instead of opening index.html and going to a subsection.

**Comment by alex-konovalov** [comment] 2019-09-20 09:31
I know this problem - it also obstructs using GAP online help on Windows using browser, because it opens the right chapter, but does not navigate to the precise location on that page, specified by `#`.

**Comment by ChrisJefferson** [comment] 2019-09-20 09:48
This page ( https://stackoverflow.com/questions/13852867/how-to-open-html-file-with-anchor-in-c-sharp-with-default-browser ), suggests doing sticking `file://` on the start of the filename, like `file://C:/g.ivank.net/index.html#3:1-2,2-3`, should fix it, but i cant test it due to lack of windows install here.

**Comment by mohammadfarrokhi** [comment] 2019-09-20 09:53
In my case, the character # do not points to any location, it is used only to show the beginning of the argument, here it is a graph, in the address to be used by javascript codes inside the page.

As I've checked, adding **file://** to the beginning of the address **solves** the problem. Thanks! I think these should be documented somewhere.

**Comment by alex-konovalov** [comment] 2019-09-20 10:10
@ChrisJefferson thanks - that's a place to fix this:

https://github.com/gap-system/gap/blob/8aff4472a6b76afcb71b3a7bc0004ca29999c651/lib/helpview.gi#L68-L86

As one can see, now it just truncates the URL. This does not require compilation, so a change may be tested on any Windows GAP installation. Would be useful to try this quickly to get into GAP 4.11.

**Comment by fingolfin** [comment] 2019-09-26 16:11
To be honest, I am not sure what the actual issue here is, resp. whether there even is one; and what there is to "fix" here.

The function `Exec` is a rather crude high level wrapper around `Process`, with many limitations and pitfalls. About the only thing I'd consider it fit for is quick and dirty interactive experiments, otherwise, I'd avoid it: there is no way to find out whether it succeeded, output of the executed commands is printed w/o a way to redirect it, and it needs to perform fragile argument parsing.

Any attempts to "improve" it to me seem like putting lipstick on a pig.

**Comment by ChrisJefferson** [comment] 2019-09-26 17:56
The problem isn't to do with exec, or process. The problem (sorry, should have made clear) is that opera, given a standard windows filename, interprets any # as part of the file name, not as an anchor.

**Comment by fingolfin** [comment] 2019-09-27 13:30
So, is there any reason to leave this issue open (which reason?), or can we close it?

**Comment by alex-konovalov** [comment] 2019-09-27 14:11
Leave open - if there may be an easy fix in helpview.gi to make GAP online help work, that will be a very good improvement.

**Comment by fingolfin** [comment] 2020-01-08 15:07
@alex-konovalov I don't understand this reason for leaving this issue open. This issue is about the function `Exec`, which has a very limited scope. Your comments refers to a "fix" for `helpview.gi` on Windows. But that sounds like a separate issue, which should get its own issue. That other issue then might be resolved by changing `Exec` -- but perhaps also in a completely different way (I suspect the latter would be better on the long run, `Exec` is a crude tool for most purposes).

**Comment by alex-konovalov** [comment] 2020-01-08 15:16
@fingolfin fine if you want to create a new issue, please do it, happy to be assigned to it. But don't close this without a new issue for the other problem.

**Comment by alex-konovalov** [comment] 2020-02-07 15:06
I've tried to add `file://` does not work. Also, can't find the user confirmation, and not sure if that worked at all indeed. Hence, closing this.

**Closed by alex-konovalov** 2020-02-07 15:06 UTC
Labels: kind: support request, os: windows, topic: documentation
