### ISSUE TITLE
automatically finding GAP_ROOT

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#4734] opened 2022-01-14 13:56 UTC
Currently the only "automatic" way to find GAP_ROOT (to put in `--with-gaproot`, say) seems to be to parse the GAP start-up
script. Can this be provided somehow? 
Might also simply package installation, as then `--with-gaproot=` would become unnecessary (or at least its value could be obtained by calling GAP). 

One can also think of putting this info into something like pkg-config data.

Possibly related to #4731.

**Comment by fingolfin** [comment] 2022-01-17 00:13
What exactly do you want to achieve? Do you want to know what GAPROOT to point package build scripts at? Or something else? 

For the former, the directory to point them at is the one containing `sysinfo.gap`, which contains all the data needed for package build systems.

**Comment by dimpase** [comment] 2022-01-17 08:03
Yes, indeed, it is for building - libgap interfaces, and GAP packages.  

The question is how to do this in a system-agnostic way. 
Usually this is achieved by using a tool like pkg-config, or by a special script.

**Comment by fingolfin** [comment] 2022-01-17 08:12
Duplicate of issue #275

**Closed by fingolfin** 2022-01-17 08:12 UTC
