### ISSUE TITLE
Edge case for IndependentGeneratorExponents

### ISSUE THREAD

**Issue by roed314** [gap-system/gap#901] opened 2016-09-26 05:22 UTC
This example is an edge case, but it causes an algorithm I'm writing to crash.  I can work around it, but it seemed like a good idea to report the problem.

### Observed behaviour
``gap> G:=SmallGroup(432,520);``
``<pc group of size 432 with 7 generators>``
``gap> V:=PCore(G,3);``
``Group([ f5, f6, f7 ])``
``gap> W:=FactorGroupNC(V,PRump(V,3));``
``Group([ f1, f2, <identity> of ... ])``
``gap> IsAbelian(W);``
``true``
``gap> IndependentGeneratorsOfAbelianGroup(W);``
``[ f1, f2 ]``
``gap> GeneratorsOfGroup(W);``
``[ f1, f2, <identity> of ... ]``
``gap> IndependentGeneratorExponents(W,GeneratorsOfGroup(W)[1]);``
``[ 1, 0 ]``
``gap> IndependentGeneratorExponents(W,Identity(W));``
``Error, no method found! For debugging hints type ?Recovery from NoMethodFound``
``Error, no 1st choice method found for `IndependentGeneratorExponents' on 2 arguments``

### Expected behaviour
``gap> IndependentGeneratorExponents(W,Identity(W));``
``[0, 0]``
### Copy and paste GAP banner (to tell us about your setup)
`` ┌───────┐   GAP, Version 4.7.8 of 09-Jun-2015 (free software, GPL)``
`` │  GAP  │   http://www.gap-system.org``
`` └───────┘   Architecture: x86_64-unknown-linux-gnu-gcc-default64``
`` Libs used:  gmp, readline``
`` Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0``
`` Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, Carat 2.1.4, Congruence 1.1.1, CRISP 1.3.8, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, EDIM 1.3.2, FactInt 1.5.3, FGA 1.2.0, GAPDoc 1.5.1, gpd 1.34, HAP 1.10.15, HAPcryst 0.1.11,
             IRREDSOL 1.2.4, LAGUNA 3.7.0, Polenta 1.3.2, Polycyclic 2.11, polymaking 0.8.1, RadiRoot 2.7, ResClasses 3.4.0, singular 12.04.28, SONATA 2.6, Sophus 1.23, SpinSym 1.5, TomLib 1.2.5, XMod 2.41``

**Comment by markuspf** [comment] 2016-09-26 08:57
Hi,

thanks for the report! I cannot reproduce this bug on `gap-4.7.9`, `gap-4.8.4` or on the current release candidate for `gap-4.8.5` though. Are you sure the above is a minimal (non-)working example?

**Comment by roed314** [comment] 2016-09-26 17:35
Strange.  It seems unlikely that it would have been randomly resolved between ``gap-4.7.8`` and ``gap-4.7.9``.

I'm actually running on [cloud.sagemath.com](cloud.sagemath.com), so if you want to create an account there I can add you as a collaborator on the project so that you can see the problem in action.

**Comment by ChrisJefferson** [comment] 2016-09-26 18:49
I've never signed up for sage cloud before, but just signed up, as chris@bubblescope.net.

I tried spinning up a standard session, and starting GAP, but I ended up with 4.8.3, so I assume you are doing something different.

**Comment by roed314** [comment] 2016-09-26 19:01
I've added you as a collaborator on my ``p-adic Tori`` project.  If you open ``Main2.term`` you'll find a Gap session with the behavior I've described.  I've installed my own copy of Gap in the ``gap4r7`` folder so that I could add additional packages.

At this point, it seems like the problem may be peculiar to my setup. You're welcome to take a look if you like, but I'm also happy to close this issue as something that's not present in a normal GAP installation.

**Comment by hulpke** [comment] 2016-09-26 19:09
I had a 4.7.8 lying around, and in that it all works fine. Have you tried it in a freshly started GAP with minimum packages loaded?

**Comment by roed314** [comment] 2016-09-26 19:22
Yeah, I just tried starting GAP with ``gap -A`` and got the same result.  Here's my header:
``┌───────┐   GAP, Version 4.7.8 of 09-Jun-2015 (free software, GPL)``
`` │  GAP  │   http://www.gap-system.org``
`` └───────┘   Architecture: x86_64-unknown-linux-gnu-gcc-default64``
`` Libs used:  gmp, readline``
`` Loading the library and packages ...``
``#I  You are using an old /projects/8053a295-2cab-4fa1-b0b4-6f01839977f4/.gaprc file.``
``#I  See '?Ref: The former .gaprc file' for hints to upgrade.``
`` Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0``
`` Packages:   GAPDoc 1.5.1``

**Comment by roed314** [comment] 2016-09-26 19:23
(I deleted everything from my ``.gaprc`` file before starting gap, but still got the warning since the file was still present)

**Comment by markuspf** [comment] 2016-09-26 19:26
Out of curiosity: Why are you using such an ancient version of GAP?

**Comment by roed314** [comment] 2016-09-26 19:30
I took a break from working on this project and only recently got back into it.

**Comment by markuspf** [comment] 2016-09-26 19:33
Could it be that you change what `Identity(W)` does? Can you call `Identity(W)` by itself in your session?

**Comment by ChrisJefferson** [comment] 2016-09-26 19:40
I made a new terminal, went into the `rattori` directory (so the loads in `.gaprc` worked), typed `gap`, then ran the following:

```
gap> G:=SmallGroup(432,520);
<pc group of size 432 with 7 generators>
gap> V:=PCore(G,3);
Group([ f5, f6, f7 ])
gap> W:=FactorGroupNC(V,PRump(V,3));
Group([ f1, f2, <identity> of ... ])
gap> IsAbelian(W);
true
gap> IndependentGeneratorsOfAbelianGroup(W);
[ f1, f2 ]
gap> GeneratorsOfGroup(W);
[ f1, f2, <identity> of ... ]
gap> IndependentGeneratorExponents(W,GeneratorsOfGroup(W)[1]);
[ 1, 0 ]
gap> IndependentGeneratorExponents(W,Identity(W));
[ 0, 0 ]
```

**Comment by roed314** [comment] 2016-09-26 20:15
Very strange.  Well, I think it's pretty clearly not a problem in GAP, so closing the issue seems appropriate to me.  Thanks for all of your efforts!

**Comment by fingolfin** [comment] 2016-09-29 12:11
Well, one last thing to try: Perhaps some package you have modified some methods. Can you please execute the following (after setting up W as before), and paste the output?
```gap
ApplicableMethod(IndependentGeneratorExponents, [W,Identity(W)], 6);;
```

For me, the output is this:
```gap
gap> ApplicableMethod(IndependentGeneratorExponents, [W,Identity(W)], 6);;
#I  Searching Method for IndependentGeneratorExponents with 2 arguments:
#I  Total: 4 entries
#I  Method 1: ``IndependentGeneratorExponents: for groups of FFE'', value: 411
#I   - 1st argument needs [ "CategoryCollections(IsFFE)" ]
#I   - 2nd argument needs [ "IsFFE" ]
#I  Method 2: ``IndependentGeneratorExponents: for an abelian pcp group and an element'', value: 65
#I   - 1st argument needs [ "CategoryCollections(IsPcpElement)" ]
#I   - 2nd argument needs [ "IsPcpElement" ]
#I  Method 3: ``IndependentGeneratorExponents: for direct products'', value: 59
#I   - 1st argument needs [ "Tester(DirectProductInfo)" ]
#I   - 2nd argument needs [ "IsDirectProductElement" ]
#I  Method 4: ``IndependentGeneratorExponents'', value: 48
#I  Function Body:
function ( G, elm )
    local  ind, pcgs, primes, pos, p, i, e, f, a, j;
    if not IsBound( G!.indgenpcgs )  then
        ind := IndependentGeneratorsOfAbelianGroup( G );
        pcgs := [  ];
        primes := [  ];
        pos := [  ];
        for i  in ind  do
            Assert( 1, IsPrimePowerInt( Order( i ) ) );
            p := Factors( Order( i ) )[1];
            Add( primes, p );
            Add( pos, Length( pcgs ) + 1 );
            while not IsOne( i )  do
                Add( pcgs, i );
                i := i ^ p;
            od;
        od;
        Add( pos, Length( pcgs ) + 1 );
        pcgs := PcgsByPcSequence( FamilyObj( One( G ) ), pcgs );
        G!.indgenpcgs := rec(
            pcgs := pcgs,
            primes := primes,
            pos := pos,
            gens := ind );
    else
        pcgs := G!.indgenpcgs.pcgs;
        primes := G!.indgenpcgs.primes;
        pos := G!.indgenpcgs.pos;
        ind := G!.indgenpcgs.gens;
    fi;
    e := ExponentsOfPcElement( pcgs, elm );
    f := [  ];
    for i  in [ 1 .. Length( ind ) ]  do
        a := 0;
        for j  in [ pos[i + 1] - 1, pos[i + 1] - 2 .. pos[i] ]  do
            a := a * primes[i] + e[j];
        od;
        Add( f, a );
    od;
    return f;
end
```

**Comment by fingolfin** [comment] 2016-09-30 12:17
For the record, I also just tested with GAP 4.7.4, and it worked fine, too.

So I am now closing this.

**Closed by fingolfin** 2016-09-30 12:17 UTC
