### ISSUE TITLE
Non-readonly types in HPCGAP causing slowdowns

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#125] opened 2015-03-26 21:43 UTC
I've been looking at why `g:=WreathProduct(MathieuGroup(9),Group((1,2)));;ConjugacyClassesSubgroups(g);;` is still slower in HPC-GAP. I think I have an idea based on line-by-line profiling (now functional in HPC-GAP). The big remaining issue is that `NewType` keeps not using the cache, which in turn means method selection is much more expensive.

To give an idea, in `g:=WreathProduct(MathieuGroup(9),Group((1,2)));;ConjugacyClassesSubgroups(g);;`

On the first call in a GAP session, NewType is called 220,122 times and there are 3,784 cache misses.
On a second call of the same code, NewType is called 218,010 times and there are 1,517 cache misses.

In HPCGAP the times called are very similar, but on 166,014 calls we purposefully avoid the cache, leading to 166,294 cache misses. SImilarly, on the second call we again purposefully avoid the cache and get 164,018 cache misses.

**Comment by stevelinton** [comment] 2015-03-27 09:34
I’m working on this. I think it can be fixed by a little code reorganisation

Specifically adding an argument to NEW_TYPE which allows the post-processing done in Subtype* to be done
inside NEW_TYPE before the type is made readonly. 

S

**Comment by fingolfin** [comment] 2015-03-29 15:55
Actually, I cannot reproduce Chris' findings at all?! With master, I get this:
```
gap> NEW_TYPE_CACHE_HIT; NEW_TYPE_CACHE_MISS;
242
40
gap> g:=WreathProduct(MathieuGroup(9),Group((1,2)));; time;
7
gap> NEW_TYPE_CACHE_HIT; NEW_TYPE_CACHE_MISS;
243
51
gap> ConjugacyClassesSubgroups(g);; time;
3186
gap> NEW_TYPE_CACHE_HIT; NEW_TYPE_CACHE_MISS;
214162
2386
```

But with hpcgap-default rev 9ec2afe78e6 (so without Steve's PR), I get this:
```
gap> NEW_TYPE_CACHE_HIT; NEW_TYPE_CACHE_MISS;
71
13
gap> g:=WreathProduct(MathieuGroup(9),Group((1,2)));; time;
9
gap> NEW_TYPE_CACHE_HIT; NEW_TYPE_CACHE_MISS;
71
14
gap> ConjugacyClassesSubgroups(g);; time;
7537
gap> NEW_TYPE_CACHE_HIT; NEW_TYPE_CACHE_MISS;
52378
96
```

So there are overall a lot fewer NEW_TYPE calls to start with, and also considerably fewer cache misses. Considering that `Subtype` is so exotic, and certainly not used when computing in permutation groups, that's perhaps not very surprising... ?!

**Comment by ChrisJefferson** [comment] 2015-03-29 16:13
The problem is that in the troublesome case (`_NEW_TYPE_READONLY` is false), neither of those variables is incremented. Look at `NEW_TYPE_NEXT_ID` changes to see how many new types are actually being created.

**Comment by stevelinton** [comment] 2015-03-29 17:08
Subtype is not exotic. It is used whenever an object discovers that it has a new filter -- so whenever an attribute is computed.

**Comment by stevelinton** [comment] 2015-09-10 13:25
Send me a F#ckFriends request so we can hook up
My usename is Merlin610
my profile is here ONLINE NOW

**Comment by stevelinton** [comment] 2015-09-17 10:41
Send me a F#ckFriends request so we can hook up
My usename is SexyBear429
my profile is here TALK S00N

**Comment by stevelinton** [comment] 2015-09-17 11:02
Send me a F#ckFriends request so we can hook up
My usename is LittleKinky364
my profile is here :)

**Comment by stevelinton** [comment] 2015-09-17 15:02
Send me a F#ckFriends request so we can hook up
My usename is LittleMonkey208
my profile is here IM ONLINE

**Comment by stevelinton** [comment] 2015-10-01 06:21
From the time you first tried Viagra Soft you'll never forget these moments! Make up your mind now! Purchase now!
Viagra Soft - widely known in narrow circles. It's time for you to get one of them. 

You can buy in our online drugstore!

Viagra Soft � you can rely on our professional help. Purchase at our online shop now!
Your interest will grow as our prices are low! Purchase now! Viagra Soft at our online shop now!
Viagra Soft � softly sets you ready for a long action. 

Available on our online shop now!

**Comment by stevelinton** [comment] 2015-10-01 08:00
One of the bestsellers awaits for its lucky owner on our online shop. Viagra Professional might be yours! Buy now.
Cram more into your sex abilities list. Viagra Professional in our online shop is affordable like never before!

Greatest hit! Worth to admit. Viagra Professional for you in our online shop!

Get what you have been dreaming a long time and more with Viagra Professional. Buy in our online shop!
Be a professional in love! 
Buy Viagra Professional at our online shop!

**Comment by stevelinton** [comment] 2015-10-01 09:04
Shop now with us! Cialis Professional is popular like no other! Buy online!
Our price on Cialis Professional makes it is easy to figure out where to buy it!
You're up all night to get lucky! Cialis Professional you can't miss the moment! Try it now! 

Purchase in our online shop!

Cialis Professional - any remedy won't take care of your sex health better. Any drugstore will offer it cheeper!
Explore your love abilities! Believe they can be endless with Cialis Professional. 

You can purchase it in our online shop. It's easy!

**Comment by fingolfin** [comment] 2015-12-16 18:03
Note that PR #326 (and also #142, #291, #295) attempt to deal with this issue.

**Comment by fingolfin** [comment] 2016-02-18 14:19
We merged #326 some time ago. I now get these numbers (on the same laptop as with the previous ones, but with a new OS version, and of course the most recent GAP / HPC-GAP versions). I executed
```
gap> ConjugacyClassesSubgroups(WreathProduct(MathieuGroup(9),Group((1,2))));; time;
```
several tiems in each. In GAP, the time fluctuated around 3.4 seconds (so a bit slower than what I reported above), while in HPC-GAP, it varied around 5.25 seconds. While that is still quite a bit slower, it certainly is a noticable improvement compared to what I got earlier.

To get a somewhat more accurate idea of the impacte of #326, I also measured this in the merge commit  65763692221, and the commit 539383ef5b9646fb3801a3631b74d4beac1f90d3 right before the merge. Before the merge, I get times around 6.4 seconds, right after the merge it's about 5.3 seconds. 

Nice! But still some work left to be done.

**Comment by stevelinton** [comment] 2016-09-22 17:44
Online Pharmacy - Only 
quality drugs! | Canadian Cheap RX

**Comment by fingolfin** [comment] 2017-05-09 23:13
To update this, I now get these results, using this helper function recording the number of type cache hits/misses and types created:
```
stat:=function() return [NEW_TYPE_CACHE_HIT,NEW_TYPE_CACHE_MISS,NEW_TYPE_NEXT_ID]; end;
```

Results for GAP:
```
gap> old:=stat(); g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
3218
[ 218079, 997, 2532 ]
gap> old:=stat(); g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
3151
[ 216761, 812, 864 ]
```

Results for HPC-GAP:
```
gap> old:=stat(); g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
6579
[ 182171, 36834, 38436 ]
gap> old:=stat(); g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
6412
[ 181780, 35794, 35870 ]
```
As you can see, runtime in HPC-GAP regressed a bit again (and it takes 2x as long as GAP). The number of new types being generated is lower for both GAP and HPC-GAP, but it still is MUCH higher for HPC-GAP. So there is still room for improvement.

**Comment by fingolfin** [comment] 2017-08-17 08:17
Results as of today (with #1326 merged in May) for GAP (started with `-A`):
```
gap> stat:=function() return [NEW_TYPE_CACHE_HIT,NEW_TYPE_CACHE_MISS,NEW_TYPE_NEXT_ID]; end;;
gap> old:=stat();; g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
3326
[ 221451, 1826, 3392 ]
gap> old:=stat();; g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
3219
[ 220754, 1045, 1100 ]
gap> 3392+1100;
4492
```
For HPC-GAP:
```
gap> stat:=function() return [NEW_TYPE_CACHE_HIT,NEW_TYPE_CACHE_MISS,NEW_TYPE_NEXT_ID]; end;;
gap> old:=stat();; g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
5061
[ 220797, 2484, 4042 ]
gap> old:=stat();; g:=WreathProduct(MathieuGroup(9),Group((1,2)));; ConjugacyClassesSubgroups(g);; time; stat() - old;
5098
[ 221096, 718, 778 ]
gap> 4042+778;
4820
```
So the example is still considerably slower in HPC-GAP than in GAP, but it clearly is not due to type cache misses -- indeed, the numbers are slightly *better* in HPC-GAP than they are in GAP.

So while we still have a performance issue, I am pretty sure it's not due to non-readonly types anymore. Closing.

**Closed by fingolfin** 2017-08-17 08:17 UTC
Labels: enhancement, HPC-GAP, performance, regression
