### ISSUE TITLE
Documentation for `Reset` should state that it returns the previous RNG seed

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4109] opened 2020-09-04 12:13 UTC
Some code even seems to rely on that.

Might be a good idea to verify all implementations do this (I am aware of only one implementation outside of GAP itself, namely in the `io` package).

**Comment by jackschmidt** [comment] 2021-06-05 01:35
I believe this was fixed in #4438 

I checked through the packages on an installation of GAP 4.11.1 (ubuntu 20.10) and only found three instances:

* :+1: xgap defined a Reset operation on a different type of object (text selection user interface object)
* :+1: orb defined a Reset operation on a different type of object (product replacer)
* :shrug: io defines a Reset operation on a `IsRandomSource`, but it does not do anything since the random source is not meant to be reproducible. It does not return any value, but I don't think there is a sensible value to return.

None of them allow setting a "seed" or anything like that, so I don't think there is any danger of confusion.

**Closed** 2021-06-05 22:39 UTC
Labels: good first issue, topic: documentation
