### ISSUE TITLE
GAP tests are locale-dependent.

### ISSUE THREAD

**Issue by rbehrends** [gap-system/gap#3979] opened 2020-04-22 18:05 UTC
Several tests fail when run under the `C` locale.

Example:

```
LC_ALL=C LC_CTYPE=C ./gap tst/testinstall.g
```

This results in errors like this:

```
testing: /Users/behrends/develop/gap-dev/master/tst/testinstall/stringobj.tst
########> Diff in /Users/behrends/develop/gap-dev/master/tst/testinstall/strin\
gobj.tst:41
# Input is:
List("abcxyzABCXYZ\n\t !019?\377\000$", LowercaseChar);
# Expected output:
"abcxyzabcxyz\n\t !019?\377\000$"
# But found:
"abcxyzabcxyz\n\t !019?�\000$"
########
########> Diff in /Users/behrends/develop/gap-dev/master/tst/testinstall/strin\
gobj.tst:43
# Input is:
List("abcxyzABCXYZ\n\t !019?\377\000$", UppercaseChar);
# Expected output:
"ABCXYZABCXYZ\n\t !019?\377\000$"
# But found:
"ABCXYZABCXYZ\n\t !019?�\000$"
########
########> Diff in /Users/behrends/develop/gap-dev/master/tst/testinstall/strin\
gobj.tst:45
# Input is:
UppercaseString("abcxyzABCXYZ\n\t !019?\377\000$");
# Expected output:
"ABCXYZABCXYZ\n\t !019?\377\000$"
# But found:
"ABCXYZABCXYZ\n\t !019?�\000$"
########
########> Diff in /Users/behrends/develop/gap-dev/master/tst/testinstall/strin\
gobj.tst:47
# Input is:
LowercaseString("abcxyzABCXYZ\n\t !019?\377\000$");
# Expected output:
"abcxyzabcxyz\n\t !019?\377\000$"
# But found:
"abcxyzabcxyz\n\t !019?�\000$"
########
     372 ms (0 ms GC) and 24.4MB allocated for stringobj.tst
```

A similar problem could be [observed in the Homebrew tests](https://github.com/gap-system/homebrew-gap/issues/2).

**Comment by fingolfin** [comment] 2020-04-23 09:32
One way to fix this would be to explicitly compare the strings to the expect result strings. I.e. instead of
```
gap> LowercaseString("Foo");
foo
```
write
```
gap> LowercaseString("Foo") = "foo";
true
```

**Comment by fingolfin** [comment] 2020-04-23 09:33
I believe this might also be a duplicate of or at least related to issue #2194

**Comment by frankluebeck** [comment] 2020-04-30 14:20
A short explanation of this behaviour: GAP uses some heuristics (involving `LC_...` environment variables) to find out the encoding of its standard output (see the value of `GAPInfo.TermEncoding`). Unfortunately, there is no portable mechanism to achieve this.

Nowadays, GAP will usually find out that you want UTF-8 output; if GAP doesn't find an explicit setting of the encoding (for example because you have set  `LC_ALL =C`) it defaults to ISO-8859-1. 

So, in the example above, GAP assumes that "\377" is the printable character ÿ (for ISO-8859-1 output) and so writes out an invalid character sequence if your output expects UTF-8.

So, the errors in the first post could be avoided by setting explicitly `GAPInfo.TermEncoding := "UTF-8"` before the test. But the more robust solution for the tests would be to compare strings and to avoid the viewing of the resulting strings (which is intentionally locale dependend), as suggested by @fingolfin.

**Closed** 2020-05-13 12:47 UTC
Labels: kind: bug, topic: tests
