### ISSUE TITLE
Incorrect result from Union

### ISSUE THREAD

**Issue by sylvie-ln** [gap-system/gap#2234] opened 2018-03-02 20:30 UTC
Hello,
I am getting strange behaviour from Union. The error may be related to the Automata package. I am using Gap 4.8.10 on Windows 10.

### Observed behaviour
Applying Union to a list constructed from the transition matrix of an certain automaton produces an incorrect result. Copying and pasting the same list directly into Union produces the correct result.

```
gap> List([1..9],q->TransitionMatrixOfAutomaton(A)[3][q]);
[ [ 8 ], [ 2 ], [ 4 ], [ 1 ], [ 6 ], [ 7, 8 ], [ 3, 8 ], [ 5, 8 ], [ 8 ] ]
gap> Union(last);
[ 1, 2 ]
gap> Union([ [ 8 ], [ 2 ], [ 4 ], [ 1 ], [ 6 ], [ 7, 8 ], [ 3, 8 ], [ 5, 8 ], [ 8 ] ]);
[ 1, 2, 3, 4, 5, 6, 7, 8 ]
gap>
```

**Update:**
I can reproduce the incorrect behaviour without loading the Automata package, as follows:
```
gap> Union([[4],[1],[6],[7,8..8],[3,8..8],[5,8..8]]);
[ 1 ]
```
Maybe it is related to the strange use of range syntax in the lists [7,8..8], [3,8..8], [5,8..8]. This strange syntax also appears in the automaton A whose construction is described below.

### Expected behaviour
In the above snippet, Union(last) and Union([ [ 8 ], [ 2 ], [ 4 ], [ 1 ], [ 6 ], [ 7, 8 ], [ 3, 8 ], [ 5, 8 ], [ 8 ] ]) should produce the same result.

Here is how the automaton A is constructed, in case it is relevant:
```
gap> LoadPackage("automata");
----------------------------------------------------------------
Loading  Automata 1.13
For help, type: ?Automata:
----------------------------------------------------------------
true
gap> StarOperation := function(A)
>  local S,n,a,t,T,i,I,N,f,F;
>  n:=NumberStatesOfAutomaton(A);
>  a:=AlphabetOfAutomaton(A);
>  T:=StructuralCopy(TransitionMatrixOfAutomaton(A));
>  I:=InitialStatesOfAutomaton(A);
>  F:=FinalStatesOfAutomaton(A);
>  for i in [1..a] do
>   t:=T[i];
>   N:=List(I,q->T[i][q]);
>   Add(t,N);
>   for f in F do
>    if not IsList(T[i][f]) then
>     T[i][f] := [T[i][f]];
>    fi;
>    T[i][f] := Union(T[i][f],N);
>   od;
>  od;
>  S:=Automaton("nondet",n+1,a,T,[n+1],Concatenation(F,[n+1]));
>  return S;
> end;
function( A ) ... end
gap> n:=8;; k:=3;;
gap> A:=StarOperation(Automaton("det",n,3,[Concatenation([2..n],[1]),Concatenation([1],[3..n],[2]),Concatenation([n,2],[4 .. n-4],[1],[n-2,n-1,3],[n-3])],[1],[n-k+1..n]));;
```

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.8.10, 15-Jan-2018, build of 2018-01-15 14:36:25 (GMTST)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i686-pc-cygwin-gcc-default32
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.8, Browse 1.8.7, CRISP 1.4.4, Cryst 4.1.13,
             CrystCat 1.1.6, CTblLib 1.2.2, FactInt 1.6.0, FGA 1.3.1, GAPDoc 1.6.1, IO 4.5.1, IRREDSOL 1.4,
             LAGUNA 3.8.0, Polenta 1.3.8, Polycyclic 2.11, RadiRoot 2.7, ResClasses 4.7.1, Sophus 1.23, SpinSym 1.5,
             TomLib 1.2.6, utils 0.49
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment] 2018-03-02 23:21
HI there, thank you for taking the time to report a bug! And sorry for any inconvenience caused by it

This particular issue is known (I am not 100% sure, but it may have been issue #1447) and has already been fixed in the development version of GAP quite some time ago (I just confirmed this with your example code). The fix will be in GAP 4.9, which we plan to release officially on April 1st (you can view the full releases notes at https://github.com/gap-system/gap/wiki/GAP-4.9-release-notes). In the meantime, if you are interested, you can download the beta release of GAP 4.9  from https://www.gap-system.org/pub/gap/gap-4.9/beta/ -- despite being labeled "beta", it should be stable, we mostly call it beta to give package authors some time to adapt their packages, if needed. Any feedback on the beta release is highly welcome!

**Comment by sylvie-ln** [comment] 2018-03-03 01:27
Sorry for the duplicate, I didn't notice that issue! I installed GAP 4.9 and it seems to produce the correct result.

**Comment by fingolfin** [comment] 2018-03-05 09:19
@sylvie-ln no worries, nothing to be sorry about; I wouldn't expect anybody to find that duplicate (and even if: it's not that clear that it is really a duplicate). I merely pointed it out for context. Anyway, I am glad that GAP 4.9 solves the issue for you. Please do not hesitate to report further issues as you encounter them, an don't worry too much about duplicates (though of course it's always a good idea to search through open and closed issues first, but again, don't worry too much about that :-)

**Closed by fingolfin** 2018-03-05 09:19 UTC
Labels: bug, duplicate
