### ISSUE TITLE
GAP inserts carriage return characters when getting input from a pipe

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#1745] opened 2017-09-25 19:14 UTC
I also tried this using `bash --norc` because I read somewhere that maybe the config messes up things. Maybe also some of my environment variables are messing things up.
### Observed behaviour
```
echo "1; QUIT;" | gap -q > out
od -xc out
0000000    310d    000a
         \r   1  \n
0000003
```

**Comment by fingolfin** [comment] 2017-09-26 00:08
This is a duplicate of https://github.com/gap-system/gap/issues/430

**Closed by fingolfin** 2017-09-26 00:08 UTC
