### ISSUE TITLE
Spurious leading ^M in *stdout*

### ISSUE THREAD

**Issue by kiryph** [gap-system/gap#5461] opened 2023-06-14 07:51 UTC
### Observed behaviour

shell prompt (zsh):

```
$ gap -b --nointeract -c 'PrintTo("*stdout*", "Hello");' | more
^MHello
```

### Expected behaviour

No leading ctrl m when printing to stdout:

```
$ gap -b --nointeract -c 'PrintTo("*stdout*", "Hello");' | more
Hello
```

OS: macOS 12.6.5 (Monterey)

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.12.2 of 2022-12-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin21-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.6, AutoDoc 2022.10.20, AutPGrp 1.11, Browse 1.8.19,
             CaratInterface 2.3.4, Congruence 1.2.4, CRISP 1.4.6, crypting 0.10.4, Cryst 4.1.25, CrystCat 1.1.10,
             CTblLib 1.3.4, curlInterface 2.3.1, datastructures 0.3.0, Digraphs 1.6.1, EDIM 1.3.6, FactInt 1.6.3,
             ferret 1.0.9, FGA 1.4.0, Forms 1.2.9, FUtil 0.1.5, GAPDoc 1.6.6, genss 1.6.8, GRAPE 4.9.0,
             groupoids 1.71, HAP 1.47, HAPcryst 0.1.15, images 1.3.1, IO 4.8.0, IRREDSOL 1.4.4, json 2.1.1,
             LAGUNA 3.9.5, Memoisation 1.0, nq 2.5.9, orb 4.9.0, Polenta 1.3.10, Polycyclic 2.16, polymaking 0.8.6,
             PrimGrp 3.4.3, RadiRoot 2.9, recog 1.4.2, ResClasses 4.7.3, Semigroups 5.2.0, singular 2022.09.23,
             SmallGrp 1.5.1, Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.3, utils 0.81, XMod 2.88
```

**Comment by fingolfin** [comment] 2023-06-15 15:56
Duplicate of issue #430.

**Closed by fingolfin** 2023-06-15 15:56 UTC

**Comment by kiryph** [comment] 2023-06-15 16:10
Thanks for pointing me to the issue. I can confirm that not loading any package with `-A` removes the spurious `^M`:

```
$ gap -A -b --nointeract -c 'PrintTo("*stdout*", "Hello");' | more
Hello
```

From the far distance I am looking at this, I do not understand why packages can affect IO of core GAP. IMHO they should not. Anyhow, as far as I have read the referenced issue, it has been decided that there will be no change and I will take this into account.

**Comment by fingolfin** [comment] 2023-06-15 16:13
A package can execute arbitrary code, including printing, so of course it can affect the IO of GAP (the same holds for packages for Python/Rust/Zig/Julia/...). Of course we'd prefer if this one didn't but nobody could figure out a workable solution. If you have a brilliant insight how to do it, we'd be happy to hear it.

**Comment by kiryph** [comment] 2023-06-15 16:26
> If you have a brilliant insight how to do it, we'd be happy to hear it.

Sorry, no brilliant inside into GAP inner working on my side and a solution for this.

Since probably people are now used to it, changing could break workflows ([xkcd](https://xkcd.com/1172/) 😄).

**Comment by fingolfin** [comment] 2023-06-15 20:21
I don't think fixing this would break any workflows that don't deserve it 😉

As to Sage: it might just not be including the Browse package, and/or not loading it by default.

**Comment by kiryph** [comment] 2023-06-16 05:52
> As to Sage: it might just not be including the Browse package, and/or not loading it by default.

Yes, that is very likely the reason.

If I got it correctly, the additional `CR` is related to ncurses, could the option `--nointeract` be considered to avoid the additional `CR`?
