### ISSUE TITLE
GAP fails to enter break loop

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3011] opened 2018-11-16 11:11 UTC
[in GAP 4.10dev-1462-g06ba3fe of today]

The following function

    Fail:=function()
    local a,v;
      a:=[1.2,3];
      v:=2;
      v:=a{v};
    end;

produces (as expected) an error

    Error, List Elements: <positions> must be a dense list of positive integers in
      v := a{v}; at ...

but then does not enter the break loop, but bail out to the main gap> loop.

**Comment by markuspf** [comment] 2018-11-16 11:36
This is probably related (or a duplicate of) #2920

**Comment by fingolfin** [comment] 2018-11-16 13:11
Note quite, this is a regression; there is a break loop in older GAP loops.

**Comment by fingolfin** [comment] 2018-11-16 13:11
It works in GAP up to 4.9, but is broken in GAP 4.10. Probably my fault, I'll submit a fix ASAP.

**Comment by hulpke** [comment] 2018-11-16 13:14
@markuspf Yes, thank you. I'll leave this open as it isn't directly interpreted code but in a function where there certainly should be a break loop.

**Comment by fingolfin** [comment] 2018-11-16 13:17
Actually, @markuspf is right and this is more or less #2920, sorry about the confusion. Anyway, my PR fixes both.

**Closed** 2018-11-17 09:12 UTC
Labels: kind: bug, topic: error handling
