### ISSUE TITLE
Compiler warning in the master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3141] opened 2018-12-22 14:03 UTC
New compiler warning in the master branch:
```
libtool: compile:  gcc -std=gnu99 -MQ obj/src/c_oper1.lo -MMD -MP -MF obj/src/.deps/c_oper1.d -m64 -Werror -fno-strict-aliasing -Wall -Wextra -Wundef -Wwrite-strings -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wmissing-field-initializers -Wformat=2 -Wformat-nonliteral -Wformat-security -Wno-sign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wreturn-type -Wno-inline -Wlogical-op -Wdouble-promotion -Wno-cast-function-type -Wnested-externs -Wno-implicit-fallthrough -Wimplicit-function-declaration -Wold-style-definition -Wjump-misses-init -Wno-error=unused-parameter -Wno-error=sign-compare -Wno-error=inline -I./gen -I./src -DHAVE_CONFIG_H -c src/c_oper1.c  -fPIC -DPIC -o obj/src/.libs/c_oper1.o
In file included from src/system.h:32:0,
                 from src/gasman.h:39,
                 from src/objects.h:20,
                 from src/ariths.h:16,
                 from src/compiled.h:21,
                 from src/c_oper1.c:3:
src/finfield.h: In function ���POW_FFV���:
src/debug.h:43:33: error: typedef ���static_assertion_291��� locally defined but not used [-Werror=unused-local-typedefs]
     typedef char _intern_CONCAT(static_assertion_, __LINE__)[(cond)? 1 : -1]
                                 ^
src/debug.h:40:32: note: in definition of macro ���_intern_CONCAT_���
 #define _intern_CONCAT_(X, Y)  X ## Y
                                ^
src/debug.h:43:18: note: in expansion of macro ���_intern_CONCAT���
     typedef char _intern_CONCAT(static_assertion_, __LINE__)[(cond)? 1 : -1]
                  ^
src/finfield.h:290:5: note: in expansion of macro ���GAP_STATIC_ASSERT���
     GAP_STATIC_ASSERT(sizeof(UInt) >= 2 * sizeof(FFV),
     ^
src/c_oper1.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: error: unrecognized command line option "-Wno-cast-function-type" [-Werror]
cc1: all warnings being treated as errors
make: *** [obj/src/c_oper1.lo] Error 1
Build step 'Execute shell' marked build as failure
```

**Comment by fingolfin** [comment] 2018-12-22 16:40
Please state what compiler and OS that is (note that our Travis tests run with `-Werror`, so whenever you see warnings, you can be certain that it is specific to your compiler, and we need to know details about it)

**Comment by alex-konovalov** [comment] 2018-12-22 19:12
Here it is:

![screen shot 2018-12-22 at 19 09 43](https://user-images.githubusercontent.com/5751387/50377863-3258a800-061d-11e9-9f7d-5a27364505f1.png)

Linux with gcc 4.8.5 and 6.3.1
Cygwin wih 4.9.2 (32 bit) and  4.9.3 (64-bit).

**Comment by fingolfin** [comment] 2018-12-27 14:07
Hmm, GCC implemented support for `_Static_assert` since version 4.6, and `static_assert` should be defined -- so the code path triggering the warning should not at all be taken. Did perhaps some system upgrade take place which changed `/usr/include/assert.h` to a version which is strict about when it #defines `static_assert`? Still, odd...

The only other thing I can think of is that here, `GAP_STATIC_ASSERT` is used in a header file. Perhaps moving it from inside `POW_FFV` in `finfield.h` to somewhere in `finfield.c` would help? Alas, I cannot test this theory, as I found no way to reproduce this warning.

**Comment by fingolfin** [comment] 2019-01-08 11:58
Could you please attach your `config.log` file to help reproduce this?

**Closed** 2019-02-08 12:22 UTC
