### ISSUE TITLE
Make windows installer work with all paths

### ISSUE THREAD

**Issue by JHahnHRO** [gap-system/gap#3300] opened 2019-02-15 00:38 UTC
### Observed behaviour
When using the GAP 4.10 .exe installer, the installation does not work when the installation path contains spaces, e.g. "C:\Program Files\gap-4.10.0". In this case bin/gap.bat cannot start cygwin or find the executable correctly because the bat files is incorrectly generated (without quotes around string literals containing spaces). Manually adding the necessary quotes within gap.bat makes it a little bit better: the GAP prompt itself starts now, even though it crashes almost immediately. Using gapcmd.bat instead of gap.bat gives at least an error message: "cygwin1.dll could not be found".

This feels like something out of the DOS-era.

### Expected behaviour
GAP should, as any other windows program, be installed under %PROGRAMFILES% or %PROGRAMFILES(X86)% which is not only the standard behaviour, but best practice for any software. Not only should that be possible, that should be the default.
Writing directly under C:\ is something very fishy. It's like writing directly into / under linux. Professional software simply doesn't do such things (unless it is actually connected in some relevant way to the OS itself which GAP isn't).

Come to think of it: gap.exe should just run when double-clicked upon. No .bat's or other intermediates should be necessary.

**Comment by fingolfin** [comment] 2019-02-15 08:19
Thank you for your report.

I am not involved with the Windows version of GAP (@alex-konovalov is), but based on what I know from Unix-like systems, my guess is that at least part of the problem is that there are some packages whose build system unfortunately does not work with spaces in their path. I agree this is bad in 2019, but it's not something that we can fix easily or quickly (it's the in the hands of the package author's).

That said, doesn't the Windows version ship with precompiled versions of many packages? In that case, one could perhaps allow this installation, but with a warning that some things might break (perhaps explicitly informing the user about this if the install destination has spaces in its path; and asking users to report any issues they encounter in practice, so that we can eventually fix it.

**Comment by JHahnHRO** [comment] 2019-03-20 10:57
Not having a Linux with me at the moment, I just tried installing GAP inside the WSL (=Windows subsystem for Linux). It turns out that the usual ./configure + make combination does not work there either if the GAP directory contains spaces. I will try it some time in a proper Linux system too, but from the looks of it, it seems to be a problem with the make-process not the Windows subsystem for Linux.

If that turns out to be the case, this is a bigger problem than just the windows installer.

**Comment by alex-konovalov** [comment] 2019-03-20 14:05
Even if we will fix this for the core GAP system, there are packages, and as @fingolfin said above, ensuring that all packages support paths with spaces is not an easy task. In this case I prefer to not to fix this in the core system at all, instead of ending up with a semi-broken system. What I am going to do with this issue is to check that this is adequately explained on the website and installation instructions and then close it.

**Comment by ChrisJefferson** [comment] 2021-02-24 11:59
This will be fixed in the new cygwin installer

**Closed** 2022-08-17 11:46 UTC
Labels: kind: enhancement, os: windows, topic: infrastructure
