### ISSUE TITLE
Error in autocompletion when trying to access a component object via record access by accident

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#5241] opened 2022-12-05 10:26 UTC
Steps to reproduce:
```gap
gap> G := SymmetricGroup( 3 );;
gap> G.test.
```
and now press Tab to autocomplete.

### Observed behaviour

```gap
Error, illegal access to record component `IsBound(obj.test)'
of the object <obj>. (Objects by default do not have record components.
The error might be a relic from translated GAP3 code.) at /usr/share/gap/lib/record.gi:171 called from
if not hasbang[j - 1] and IsBound( r.(cmps[j]) ) then
    r := r.(cmps[j]);
elif hasbang[j - 1] and IsBound( r!.(cmps[j]) ) then
    r := r!.(cmps[j]);
else
    r := fail;
    break;
fi; at /usr/share/gap/lib/cmdledit.g:979 called from
GAPInfo.CommandLineEditFunctions.Functions.(l[2])( l ) at /usr/share/gap/lib/cmdledit.g:291 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:2
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

### Expected behaviour

Of course the real problem is the user typing a wrong expression, but I think it would be nice to fail in a more graceful way here. If you don't think so, or if fixing this is not easy (there might actually be a method for `\.` installed and I'm not sure if one can easily detect this), feel free to close this issue.

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.12.1 of 2022-10-20
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.6.dev, IO 4.7.0dev, PrimGrp 3.4.2, SmallGrp 1.5, TransGrp 3.6.3
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment] 2022-12-05 16:49
Thank you for reporting this. That's indeed a regression from the "nicer" record tab completion introduced in 4.12, and should be fixed.

**Comment by fingolfin** [comment] 2022-12-05 16:54
Actually even in older versions something weird happens, but unrelated to tab completion: If I press "return" instead of tab, I see this:
```
gap> G.test.
Error, illegal access to record component `obj.test'
of the object <obj>. (Objects by default do not have record components.
The error might be a relic from translated GAP3 code.)       called from
<function "unknown">( <arguments> )
 called from read-eval loop at line 3 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```
If I now enter `quit;` I am put into a continuation prompt (as the semicolon was missing). That's *really* weird: the first time around I exited the break loop via Ctrl-d, and thought GAP was locked up, because nothing happened. I had to press a second time to exit for real. This is an artefact of GAP trying to parse beyond errors. Not sure I like it here, though...

**Comment by zickgraf** [comment] 2022-12-07 08:10
Out of curiosity: Why is there a distinction between `.` and `!.`? I guess due to the part of the documentation which says "One must be very careful when using the !. operator"?

**Comment by fingolfin** [comment] 2022-12-07 08:29
`IsBound(foo.b)` is only supported by records. `IsBound(foo!.b)` is supported by records and component objects.

**Comment by zickgraf** [comment] 2022-12-07 08:36
> `IsBound(foo.b)` is only supported by records. `IsBound(foo!.b)` is supported by records and component objects.

The question was not meant in the concrete context of this issue, sorry. New try: Why does GAP not allow to access components of component objects via `.` in the first place?

**Comment by ChrisJefferson** [comment] 2022-12-07 09:36
My belief is this is a safety / organisation issue. In general the names of components of component objects aren't fixed between versions of GAP, and also you can create some horrible bugs (and possibly even crashes) if you started editing components of component objects in ways you are not supposed to.

There isn't (I believe) any reason we couldn't just use "." for accessing all "record-like" objects, and get rid of "!.", except as you point out the documentation discourages uses "!." as you are digging inside objects.

**Comment by zickgraf** [comment] 2022-12-07 10:39
I see, this matches what I expected, thanks for the thorough explanation! :-)

**Comment by fingolfin** [comment] 2022-12-07 13:29
@ChrisJefferson no, that's not right! Objects can overload `.`, and frequently do; e.g. if `G` is a permutation group then `G.1` is its first generator. Ultimately, this can be used to implement custom record types.

In particular, it is possible for `G.FOO` and `G!.FOO` to behave differently, e.g. both may be defined and return different objects.

In contrast, `G!.FOO` is an access for internal data of a component type object. And for various reasons, we *also* allow accessing record elements via `r!.FOO` -- this is actually the oddball, and I'd be happy to remove it, except I bet there is some code out there which shouldn't be using it but is using it and would be broken by a removal...

**Comment by ChrisJefferson** [comment] 2022-12-07 22:06
Oh, I didn't realise you overload them both separately.

I've also been surprised that g!.foo works for records, but I also agree that I bet some code is using it -- it doesn't feel worth breaking that code.

**Comment by zickgraf** [comment] 2022-12-08 09:42
Thanks for the detailed answers! I have recently started a prototype of a system automatically converting GAP code to Julia code, so all this information is valuable :-)

**Closed** 2022-12-09 08:48 UTC
Labels: kind: bug
