### ISSUE TITLE
Segmentation Fault with "??memory"

### ISSUE THREAD

**Issue by rfmorse** [gap-system/gap#5702] opened 2024-04-17 13:07 UTC
Please use the following template to submit an issue
(you may delete lines which are not used). Thank you!

### Observed behaviour
```
 ┌───────┐   GAP 4.13.0 of 2024-03-15
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin23-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.8, AutPGrp 1.11, Browse 1.8.21, CaratInterface 2.3.6, 
             CRISP 1.4.6, Cryst 4.1.27, CrystCat 1.1.10, CTblLib 1.3.9, curlInterface 2.3.2, FactInt 1.6.3, FGA 1.5.0, 
             Forms 1.2.9, GAPDoc 1.6.7, genss 1.6.8, IO 4.8.2, IRREDSOL 1.4.4, LAGUNA 3.9.6, orb 4.9.0, 
             Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.4, RadiRoot 2.9, recog 1.4.2, ResClasses 4.7.3, 
             SmallGrp 1.5.3, Sophus 1.27, SpinSym 1.5.2, StandardFF 1.0, TomLib 1.2.11, TransGrp 3.6.5, utils 0.85
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> ??memory
zsh: segmentation fault  gap
```
### Expected behaviour
Similar to gap-4.12.2
```
   Choose an entry to view, 'q' for none (or use ?<nr> later):                                                        │
│[1]   Reference: Tracking Memory Usage                                                                                │
│[2]   Reference: Global Memory Information                                                                            │
│[3]   Reference: memory_allocated                                                                                     │
│[4]   Reference: TotalMemoryAllocated                                                                                 │
│[5]   Reference: memory_allocated                                                                                     │
│[6]   Reference: MemoryUsage                                                                                          │
│[7]   Reference: StringOfMemoryAmount                                                                                 │
│[8]   cvec (not loaded): Compressed Vectors in Memory                                                                 │
│[9]   loops (not loaded): Memory Management                                                                           │
│[10]  orb: Memory requirements                                                                                        │
│[11]  orb: Memory forob                                                                                               │
│[12]  orb: Memory forobsol                                                                                            │
│[13]  RCWA (not loaded): Saving memory -- the sparse representation of rcwa mappings                                  │
│[14]  recog: Elements with memory                                                                                     │
│[15]  SCSCP (not loaded): MemoryUsageByGAPinKbytes                                                                    │
│[16]  Smallsemi (not loaded): Memory Issues                                                                           │
│[17]  ToolsForHomalg (not loaded): MemoryToString   
```

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.13.0 of 2024-03-15
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin23-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
```
Intel iMac, Sonoma 14.4.1

**Comment by fingolfin** [comment] 2024-04-18 07:36
Very strange. Also unfortunately not enough information go say much... Hm.

How was GAP installed? Self-compiled? If so please attach the `config.log` file, and the output of `cc -v`

**Comment by ThomasBreuer** [comment] 2024-04-18 08:00
@rfmorse I cannot reproduce the crash.
It depends on several preferences what actually happens after entering `??memory`.
- Could you perhaps try what happens if you start GAP with the `-A` option? In this case, the Bowse package is not available, and help overviews will be shown without Browse support.
- Could you start GAP with the `-A` option and then call `SetUserPreference( "Pager", "builtin" )` before entering `??memory`? In this case, neither Browse nor an external pager will be involved.

**Comment by rfmorse** [comment] 2024-04-18 09:43
Here is the config.log 
[config.log](https://github.com/gap-system/gap/files/15022914/config.log)

cc -v
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by rfmorse** [comment] 2024-04-18 09:49
Works fine with the -A option:

gap> ??memory
Help: several entries match this topic - type ?2 to get match [2]
[1] Reference: Tracking Memory Usage
[2] Reference: Global Memory Information
[3] Reference: memory_allocated
[4] Reference: TotalMemoryAllocated
[5] Reference: memory_allocated
[6] Reference: MemoryUsage
[7] Reference: StringOfMemoryAmount
[8] cvec (not loaded): Compressed Vectors in Memory
[9] loops (not loaded): Memory Management
[10] orb (not loaded): Memory requirements
[11] orb (not loaded): Memory forob
[12] orb (not loaded): Memory forobsol
[13] RCWA (not loaded): Saving memory -- the sparse representation of rcwa mappings
[14] recog (not loaded): Elements with memory
[15] SCSCP (not loaded): MemoryUsageByGAPinKbytes
[16] Smallsemi (not loaded): Memory Issues
[17] ToolsForHomalg (not loaded): MemoryToString

Also works fine after issuing   SetUserPreference( "Pager", "builtin" )

**Comment by fingolfin** [comment] 2024-04-18 11:40
So if you start with `-A` then do `LoadPackage("browse");` then try `??memory`, does it crash?

If it does, can you please repeat the first two steps and then tell us the output of `Filename(DirectoriesPackagePrograms("Browse"), "ncurses.so");` ?

**Comment by rfmorse** [comment] 2024-04-18 12:22
The session crashes after loading the browse package.  Here is the output  of filename.

gap> Filename(DirectoriesPackagePrograms("Browse"), "ncurses.so");
"/Users/morse/gap-4.13.0/pkg/browse//bin/x86_64-apple-darwin23-default64-kv9/ncurses.so"

**Comment by fingolfin** [comment] 2024-04-18 13:02
That looks fine.

OK, so what is the output of
```
otool -L /Users/morse/gap-4.13.0/pkg/browse//bin/x86_64-apple-darwin23-default64-kv9/ncurses.so
```

**Comment by rfmorse** [comment] 2024-04-18 13:05
Output from otool:

/Users/morse/gap-4.13.0/pkg/browse//bin/x86_64-apple-darwin23-default64-kv9/ncurses.so:
	/usr/lib/libpanel.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)

**Comment by fingolfin** [comment] 2024-04-22 08:14
Perhaps you are daring enough to try to use a debugger to get slightly more input. Here is how (please feel free to ask for any details or clarifications!!!)

1. start GAP with `lldb ./gap`  from inside the GAP directory
2. this opens a prompt `(lldb) ` -- enter the command `pro la` on it (this runs GAP)
3. the OS at this point will probably ask you for an admin username/password, just give it
4. now you should be in GAP. Trigger the crash. This should print a lot of text. Please attach that here, in a comment.

**Comment by rfmorse** [comment] 2024-04-22 09:56
Here is the output from lldb:

````
morse@Roberts-iMac gap-4.13.0 % lldb ./gap
(lldb) target create "./gap"
Current executable set to '/Users/morse/gap-4.13.0/gap' (x86_64).
(lldb) pro la
Process 9861 launched: '/Users/morse/gap-4.13.0/gap' (x86_64)
 ┌───────┐   GAP 4.13.0 of 2024-03-15
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin23-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.8, AutPGrp 1.11, 
             Browse 1.8.21, CaratInterface 2.3.6, CRISP 1.4.6, Cryst 4.1.27, 
             CrystCat 1.1.10, CTblLib 1.3.9, curlInterface 2.3.2, 
             FactInt 1.6.3, FGA 1.5.0, Forms 1.2.9, GAPDoc 1.6.7, genss 1.6.8, 
             IO 4.8.2, IRREDSOL 1.4.4, LAGUNA 3.9.6, orb 4.9.0, 
             Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.4, RadiRoot 2.9, 
             recog 1.4.2, ResClasses 4.7.3, SmallGrp 1.5.3, Sophus 1.27, 
             SpinSym 1.5.2, StandardFF 1.0, TomLib 1.2.11, TransGrp 3.6.5, 
             utils 0.85
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> ??memory
Process 9861 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x00007ff823433825 libpanel.5.4.dylib`new_panel + 24
libpanel.5.4.dylib`new_panel:
->  0x7ff823433825 <+24>: cmpq   $0x0, 0x10(%rax)
    0x7ff82343382a <+29>: jne    0x7ff82343389d            ; <+144>
    0x7ff82343382c <+31>: callq  0x7ff823433f16            ; symbol stub for: _nc_panelhook
    0x7ff823433831 <+36>: cmpq   $0x0, 0x10(%rax)
Target 0: (gap) stopped.
```

**Comment by fingolfin** [comment] 2024-05-04 12:49
At this point I am stumped. It looks as if it fails to load the ncurses library, maybe? But then it should be displaying an error somewhere before the crash. Really strange.


"It works over here and on several other macs" of course doesn't help you, but unfortunately without being able to reproduce this, it is difficult to say much more :-(.

Perhaps if I could ssh into your machine to debug it, I could find out more.

In the meantime you could delete `/Users/morse/gap-4.13.0/pkg/browse//bin/x86_64-apple-darwin23-default64-kv9/ncurses.so` as a workaround (then of course you are missing the functionality of Browse which makes the interactive help system behave nicer, but if the alternative is a crash...)

**Comment by rfmorse** [comment] 2024-05-04 14:15
Sorry for taking so long to reply.  I have found the issue and a type of fix. I have been meaning to write things up.

In short it is a problem with readline (which gap finds in my macports (see the config file))  and macOS native ncurses which browse uses. The macOS ncurses is not used to build the Mac ports readline and hence the incompatibility and segfault.

I will write a fulll report about this soon. 

It seems to be a problem on a number of platforms (but not home brew as it explicitly uses macOS native ncurses to build its readline). So for a person using ports this problem happens. The fix I used is to force browse to use the macports ncurses and the error is fixed.

**Comment by ThomasBreuer** [comment] 2024-05-04 16:16
@rfmorse great if there is a fix.
Is there perhaps something we can change in Browse in order to avoid the "communication problem" between the involved libraries?

**Comment by rfmorse** [comment] 2024-05-04 16:48
The issue is that two different ncurses libraries are being used. One by readline compiled by MacPorts using the MacPorts ncurses library. The other version by Browse for actual ncurses functionality using the macOS native ncurses. They don't mix very well and cause the segfault. 

The config log shows that GMP is found in the MacPorts tree, but since MacPorts puts everything in one tree, things bleed over and it found readline in the same location at the same time.

Homebrew does not have this problem as it builds readline with the macOS native ncurses. 

[Homebrew](https://github.com/Homebrew/homebrewcore/blob/4d9a30e547fdab3ec539e0837fc75dcd414cbc75/Formula/r/readline.rb#L79)

The fix (OK hack) I used was to force Browse to use MacPorts' ncurses by modifying its Makefile:

```
-LOPTS=$(LDFLAGS) -lpanel -lncurses
+CURSES_HOME=/opt/local
+CURSES_INC=$(CURSES_HOME)/include
+CURSES_LIB=$(CURSES_HOME)/lib
+CFLAGS+= -I$(CURSES_INC)
+LOPTS=$(LDFLAGS) -L$(CURSES_LIB) -lpanel -lncurses
```

This seems to be a general problem making sure the same base ncurses is used: 

[FreeBSD](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220998)

MacPorts seems to be a popular enough configuration that it might be worth it to ensure that GAP uses readline with the same ncurses base as Browse in this case.  Maybe GAP might put something in 'sysinfo.gap` to help Browse configure to MacPorts  ncurses location. In this specific MacPorts case as to where readline was found. Hard problem in general as you can get a feel for with the FreeBSD link.

**Comment by fingolfin** [comment] 2024-06-18 08:48
This is a problem on the user side, there is no way we can detect and avoid all possible combinations of broken or mixed dependencies, sorry.

At best we could add code to perhaps detect it; but I see no good way to do that in a portable, platform independent way. It would thus require code specific to Linux/macOS/FreeBSD, and I am afraid would be likely to introduce further problems of it is own. I don't really want to go down that road.

FreeBSD users can just [install GAP from ports](https://www.freshports.org/math/gap) (and if that has any trouble of this kind, report it there so it can be fixed there).

And MacPorts users in turn are a dying breed (no offense), I don't know where you get the "popular enough configuration" from -- this issue is the first time I see anyone even mention MacPorts in maybe two years. It's Homebrew or nothing for Mac users (with "normal" people falling into the "nothing" category 90% of the time, and people doing development work frequently having Homebrew).

**Closed by fingolfin** 2024-06-18 08:48 UTC

**Comment by rfmorse** [comment] 2024-06-18 13:43
As noted above one can direct Browse to use the same ncurses used in building the readline GAP uses and avoid the seg fault.  Only time will tell if this comes up again for someone else. At least there's now a pointer on possible cause and how to get around the problem.

The other possible fix is to direct GAP to use the MacOS's native readline regardless as to where it gets other installed libraries from such as GMP.

**Comment by fingolfin** [comment] 2024-06-18 14:25
> As noted above one can direct Browse to use the same ncurses used in building the readline GAP uses and avoid the seg fault. 

Yes of course -- but that's for users, we can not do it for them in an automatic fashion as GAP does not use ncurses directly and has no (portable) way to detect which ncurses is used by the GNU readline it links against.


> 
> The other possible fix is to direct GAP to use the MacOS's native readline regardless as to where it gets other installed libraries from such as GMP.

No, that "readline" is not a plug-in replacement for GNU readline, it does not support all the APIs  we need.
