### ISSUE TITLE
When using ACE for coset enumeration, automatic table resizing loops forever

### ISSUE THREAD

**Issue by rokicki** [gap-system/gap#5749] opened 2024-06-17 20:24 UTC
```
LoadPackage("ace");
TCENUM:=ACETCENUM;;
Print("aaaa,aba'b'a'bb");;
f := FreeGroup("a","b");;
g := f / [ f.1*f.1*f.1*f.1,f.1*f.2*f.1^-1*f.2^-1*f.1^-1*f.2*f.2 ];
Size(g);
```

### Observed behaviour

Scrolling message:

```
#I  Coset table calculation failed -- trying with bigger table limit
```

forever.  From debugging it appears the workspace size and/or table limit is not
actually being increased.

Identical (bad) behavior on Linux and on MacOS.

### Expected behaviour

The table limit and/or workspace size should be increased, so the coset enumeration
succeeds.  (ACE easily handles the group given in the example above.)

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.13.0 of 2024-03-15
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: aarch64-apple-darwin23-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.8, AutPGrp 1.11, 
             CRISP 1.4.6, Cryst 4.1.27, CrystCat 1.1.10, CTblLib 1.3.9, 
             FactInt 1.6.3, FGA 1.5.0, GAPDoc 1.6.7, IRREDSOL 1.4.4, 
             LAGUNA 3.9.6, Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.4, 
             RadiRoot 2.9, ResClasses 4.7.3, SmallGrp 1.5.3, Sophus 1.27, 
             SpinSym 1.5.2, StandardFF 1.0, TomLib 1.2.11, TransGrp 3.6.5, 
             utils 0.85
```

**Comment by james-d-mitchell** [comment] 2024-06-18 08:04
Thanks for the report @rokicki, but isn't this an issue for the ACE package rather than for GAP itself?

**Comment by fingolfin** [comment] 2024-06-18 08:41
Indeed, this should be reported at https://github.com/gap-packages/ace/issues

All I can say here right now is that this issue already occurs in ACE 5.1 with GAP 4.5. And the message "trying with bigger table limit" comes from GAP's `FinIndexCyclicSubgroupGenerator` which indeed *does* increase the limit (doubling it each time around) but this adjusteed limit either does not reach ACE, or the problem causing the enumeration failure is unrelated to table size. 

Modifying the warning `Coset table calculation failed` to also print the value of `max`, and inserting into the example the line
```
gap> SetInfoLevel(InfoACE, 3);
```
then one my machine I see this:
```
gap> Size(g);
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  INDEX = 1 (a=1 r=2 h=1 n=2; l=3 c=0.00; m=1 t=1)
#I  co: a=1 r=2 h=1 n=2; c=+0.00
#I   coset |      a      A      b      B
#I  -------+----------------------------
#I       1 |      1      1      1      1
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  OVERFLOW (a=235298 r=79818 h=79819 n=249999; l=458 c=0.03; m=239616 t=249998)
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  OVERFLOW (a=234046 r=80672 h=80673 n=249999; l=460 c=0.02; m=238880 t=249998)
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  OVERFLOW (a=234046 r=80672 h=80673 n=249999; l=460 c=0.02; m=238880 t=249998)
#I  Coset table calculation failed -- trying with bigger table limit 8192000
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  INDEX = 1 (a=1 r=2 h=1 n=2; l=3 c=0.00; m=1 t=1)
#I  co: a=1 r=2 h=1 n=2; c=+0.00
#I   coset |      a      A      b      B
#I  -------+----------------------------
#I       1 |      1      1      1      1
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  OVERFLOW (a=235298 r=79818 h=79819 n=249999; l=458 c=0.02; m=239616 t=249998)
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  OVERFLOW (a=234046 r=80672 h=80673 n=249999; l=460 c=0.02; m=238880 t=249998)
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  OVERFLOW (a=234046 r=80672 h=80673 n=249999; l=460 c=0.02; m=238880 t=249998)
#I  Coset table calculation failed -- trying with bigger table limit 16384000
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  INDEX = 1 (a=1 r=2 h=1 n=2; l=3 c=0.00; m=1 t=1)
#I  co: a=1 r=2 h=1 n=2; c=+0.00
#I   coset |      a      A      b      B
#I  -------+----------------------------
#I       1 |      1      1      1      1
#I  ACE 3.001        Tue Jun 18 10:35:17 2024
#I  =========================================
#I  Host information:
#I    name = killwaas.mathematik.uni-kl.de
#I  ***
#I  OVERFLOW (a=235298 r=79818 h=79819 n=249999; l=458 c=0.02; m=239616 t=249998)
[...]
```


I don't have time to dig but I think the way to pass on a custom workspace size to `ACE` is via the `workspace` option. So this works:
```
gap> Size(g : workspace:=8192000);
2361960
gap> time;
8208
```
Whether or not there is some "translation" missing in GAP, in ACE, or both, or not, I can't say right now. Ideally someone else would investigate further, I don't really have time for that ATM.

**Comment by james-d-mitchell** [comment] 2024-06-19 11:06
@fingolfin can you perhaps transfer this issue to the ACE repo?

**Comment by fingolfin** [comment] 2024-06-19 11:13
No, one cannot transfer issues across organizations (otherwise I would have done it).

**Comment by fingolfin** [comment] 2024-06-19 11:14
Closing in favor of https://github.com/gap-packages/ace/issues/39

**Closed by fingolfin** 2024-06-19 11:14 UTC

**Comment by james-d-mitchell** [comment] 2024-06-19 11:17
> No, one cannot transfer issues across organizations (otherwise I would have done it).

Ah, I didn't realise that. Thanks!

**Comment by james-d-mitchell** [comment] 2024-06-19 12:24
On further inspection, it seems that in the library code the ACE options `max` and `workspace` are maybe conflated, which is what seems to be causing this issue. The issue seems to disappear with the following patch:

~~~
diff --git a/lib/grpfp.gi b/lib/grpfp.gi
index b84ded14a..62684f85e 100644
--- a/lib/grpfp.gi
+++ b/lib/grpfp.gi
@@ -3790,14 +3790,17 @@ end );
 ##  enumerations with cumulatively bigger coset tables up to table size
 ##  <maxtable>. It returns `fail' if no table could be found.
 BindGlobal("FinIndexCyclicSubgroupGenerator",function(G,maxtable)
-  local fgens, grels, powers, max, gens, t, Attempt, perms, short;
+  local fgens, grels, powers, max, gens, t, Attempt, perms, short, oldmax,
+  workspace;
 
   fgens:=FreeGeneratorsOfFpGroup(G);
   grels:=RelatorsOfFpGroup(G);
 
   max:=ValueOption("max");
+  workspace:=ValueOption("workspace");
   if max=fail then
     max:=CosetTableDefaultMaxLimit;
+    workspace:=max;
   fi;
   max:=Minimum(max,maxtable);
 
@@ -3829,7 +3832,7 @@ BindGlobal("FinIndexCyclicSubgroupGenerator",function(G,maxtable)
     trial:=sgens{[1..m]};
     Info(InfoFpGroup,1,"FIS: trying ",trial);
     t:=CosetTableFromGensAndRels(fgens,grels,
-        trial:silent:=true,max:=max);
+        trial:silent:=true,max:=max,workspace:=workspace);
     if t<>fail and Length(trial)>1 then
       Unbind(t);
       t:=Attempt(trial);
@@ -3841,7 +3844,7 @@ BindGlobal("FinIndexCyclicSubgroupGenerator",function(G,maxtable)
       trial:=sgens{[m+1..l]};
       Info(InfoFpGroup,1,"FIS: trying other half ",trial);
       t:=CosetTableFromGensAndRels(fgens,grels,
-          List(trial,UnderlyingElement):silent:=true,max:=max);
+          List(trial,UnderlyingElement):silent:=true,max:=max,workspace:=workspace);
       if t=fail then
         return fail;
       elif Length(trial)>1 then
@@ -3875,14 +3878,16 @@ BindGlobal("FinIndexCyclicSubgroupGenerator",function(G,maxtable)
       return [ElementOfFpGroup(FamilyObj(One(G)),short[Length(short)][2]),
               max];
     fi;
+    oldmax := max;
     if max*3/2<maxtable and max*2>maxtable then
       max:=maxtable;
     else
       max:=max*2;
     fi;
+    workspace := max;
     if max<=maxtable then
       Info(InfoWarning,1,
-        "Coset table calculation failed -- trying with bigger table limit");
+        StringFormatted("Coset table calculation failed with max. cosets {} -- trying with bigger table limit {}", oldmax, max));
     fi;
   od;
   return fail;
~~~

Although this is extremely slow (8s versus ~1.3s without using ACE), it seems like ~80% of the time is spent reading ACE's output:

~~~
  count  self/ms  chld/ms  stor/kb  chld/kb  package  function
 196843       47        0        0        0           GcdOp: integers: n*
 197240       43        5        0        0           =: for graphviz ed*
 229058       42        7        0        0  (oprt.)  Remove
     21       60        0        0        0           Order: for a permu*
     21        0       60        0        0  (oprt.)  Order
    290        3       73     4623    60249  GAP      List
 196831      106       36        0        0  (oprt.)  GcdOp
 590509      162        0    18453        0  GAP      Meth(FileDescripto*
 590495      281        0    88839        0           SplitString: for t*
 590509      243      177        0    18453  (oprt.)  FileDescriptorOfSt*
 393662      297      239     4613        0  GAP      Gcd
 590495      279      268        0    88839  (oprt.)  SplitString
2591186      567       18   112392        0  (oprt.)  Add
2361976      582       12        0        0           Int: for strings
      1      178      573     6150     4613  GAP      NEWTC_CyclicSubgro*
      2      833      218    63282     8821  GAP      NEWTC_CosetEnumera*
 590495      774      538    44979        0  GAP      Chomp
2361984     1184      531        0        0  (oprt.)  Int
212585*     5082       70   103804        0  (oprt.)  Append
480889*    10891       80        0        0  (oprt.)  Length
 590509    21118    14568   207600    77273  GAP      ReadLine: iostream
 590509      293    35692        0   284874  (oprt.)  ReadLine
 590519     1528    37051    24220   329854  GAP      ReadAllLine: iostr*
 590519      376    38870   119948   354075  GAP      ReadAllLine: iostr*
1181048      544    38969        0   474023  (oprt.)  ReadAllLine
 590509      322    39519        0   474021  ACE      ACE_READ_NEXT_LINE
      2     1591    43968    12111   712173  ACE      ACE_COSET_TABLE
      2        0    45587        0   724716  GAP      CosetTableFromGens*
      2        0    45587        0   724715  ACE      ACECosetTableFromG*
      4        0    45587        2   724713  ACE      ACECosetTable
      3        0    47461        0   872235  (oprt.)  Size
      1        1    47460        1   872230  GAP      Size: for finitely*
              34             61210                    OTHER
           47461            872235                    TOTAL
~~~

I'm happy to open a PR with the patch above, if this actually fixes the issue.

**Comment by fingolfin** [comment] 2024-06-19 12:37
But the idea of the `TCENUM` interface is to provide a bunch of functions that can be used interchangeably for different Todd-Coxeter implementations. If we now add options specific to one implementation, that defeats the purpose. From that point of view, it seems to me that it is ACE that ought to be changed to honor the right options passed by GAP.

**Comment by james-d-mitchell** [comment] 2024-06-19 13:17
I see what you mean. I'm not sure how to proceed, given that there is an option in both the ACE package and GAP with the name `max` but they have different meanings. If the ACE package was intended to fulfil the `TCENUM` interface and provide an interface to the ACE binary, then fixing this might be complicated. From what I saw when preparing the comment about it appears that the options set in GAP just fall through to ACE unmodified at present, and I'm not sure what the map from GAP options to ACE options might be.
