### ISSUE TITLE
Multiplication of lists affected by ResClasses

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#1133] opened 2017-02-10 18:08 UTC
Edit:
### Observed behaviour
Multplying `[ [] ] * [ [1,2,3] ];` yields `[ [] ]` in GAP whereas HPCGAP throws the error
```
gap> [[]] * [ [1,2,3] ];
Error, Inner product multiplication of lists: no summands in
   called from 
return PROD_LIST_LIST_DEFAULT( left, right, depthDiff )
 ; at /home/sergio/hpcgap/gap/lib/list.gi:3374PROD_LIST_SCL_DEFAULT( left, right 
 ) at /home/sergio/hpcgap/gap/lib/list.gi:3393 called from
<function "unknown">( <arguments> )
 called from read-eval loop at line 1 of stream
```

Sorry about the bad previous issue and pull request. Lesson learned. 
### Observed behaviour
Multplying a list L with an empty list `[] * L;` raises an error.

### Expected behaviour
The product of two lists L and H returns the empty list, if L is empty - as in GAP.

**Comment by fingolfin** [comment] 2017-02-10 19:51
I cannot reproduce this with the GAP master branch. I get this:
```
gap> [] * [1,2,3];
Error, Inner product multiplication of lists: no summands in
  return PROD_LIST_LIST_DEFAULT( left, right, depthDiff ); at /Users/mhorn/Projekte/GAP/gap.github/lib/list.gi:3397 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:1
```
Which version of GAP are you using? Try loading gap  with the `-A` option, does the error then get displayed for you, too? In that case, it might be due to a package...

**Comment by markuspf** [comment] 2017-02-10 19:55
@fingolfin also see my comment on #1334

**Comment by ssiccha** [comment] 2017-02-10 23:03
When I run the following code in GAP 4.8.6 I get:
```
gap> f := ApplicableMethod(\*, [[[]],[[1,2,3]]], 1);
#I  Searching Method for * with 2 arguments:
#I  Total: 250 entries
#I  Method 98: ``*'', value: 34
function( left, right ) ... end
gap> PageSource(f);
Showing source in /opt/gap/gap4r8/lib/list.gi (from line 3229)
```
This means, that no package is interfering with the way these two lists are multiplied. Therefore, the implementations of `PROD_LIST_LIST_DEFAULT` in GAP and HPCGAP have diverged. Is this correct?
In HPCGAP the function in listoper.c, containing line 1014:
```
ErrorMayQuit("Inner product multiplication of lists: no summands", 0, 0);
```
seems to be responsible. I compared the hpcgap-default and the 4.8.6 version of the C-function `ProdListList` but they seem to be identical.
Is the `ErrorMayQuit` statement handled differently by GAP and HPCGAP?

**Comment by fingolfin** [comment] 2017-02-11 09:02
@ssiccha From what you write, it is unclear what output `[] * [1,2,3];` produces for you on GAP 4.8.6. In any case, I just tested with GAP 4.8.6 and GAP 4.7.4, and always get the same error.

Please try to do what was suggested: Start GAP via `gap -A` and then report the full output of `[] * [1,2,3];` (ideally from the line you entered the command `gap -A` in, i.e. including the full GAP banner).

**Comment by fingolfin** [comment] 2017-02-11 09:04
Actually, I retract everything and apologize -- if only my reading comprehension skills were better... *sigh* the command you are using is `[ [] ] * [ [1,2,3] ];` of course.. And for that, it does indeed return `[]` for me with GAP 4.7.4, though not with `master` or `stable-4.8`. Will investigate

**Comment by fingolfin** [comment] 2017-02-11 09:12
OK, I also get the error with `[ [] ] * [ [1,2,3] ];` and even with GAP 4.7.4, when I start it with the `-A` option. But it "works" with 4.7.4 with default options. Packages it loads:
```
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, Browse 1.8.3, CRISP 1.3.8, Cryst 4.1.12, CrystCat 1.1.6,
             CTblLib 1.2.2, FactInt 1.5.3, FGA 1.2.0, GAPDoc 1.5.1, IO 4.2, IRREDSOL 1.2.4, LAGUNA 3.6.4, Polenta 1.3.1,
             Polycyclic 2.11, RadiRoot 2.6, ResClasses 3.3.2, Sophus 1.23, SpinSym 1.5, TomLib 1.2.4
```

Looking at that list, my first suspect immediately was `ResClasses`, and indeed, it causes the difference in behavior.

So this is not an issue with HPC-GAP at all.

**Comment by fingolfin** [comment] 2017-02-11 12:47
So I looked closer at this. The applicable method indeed at first is the same. It ends up calling `ProdListScl` in the kernel, which then essentially tries to compute `[] * [ [1,2,3] ];` which gives an error in plain GAP, but with resclasses, returns `[]` due to this method in `resclass.gi:2395`:
```gap
InstallOtherMethod( \*, "for empty list and matrix (ResClasses)",
                    ReturnTrue, [ IsList and IsEmpty, IsMatrix ], 0,
                    function ( empty, M ) return [  ]; end );
```

**Comment by ssiccha** [comment] 2017-02-11 17:31
@fingolfin No apology needed. :)

So, should we move the corresponding method into the GAP library and then merge that commit into hpcgap-default? Changing behaviour like that in a package seems a bit odd.
If you say that's sensible I'll take care of it.

**Comment by fingolfin** [comment] 2017-02-11 18:57
I don't think at all that we should move this to this library. I think I prefer the error over the to me rather arbitrary behavior introduced by resclasses. So I'd prefer if resclasses was changed by @Stefan-Kohl to not modify the behavior of GAP like this...

Alas, perhaps there are strong reasons why this alternate behavior is deemed useful by you guys, so feel free to state your case :-).

**Comment by ssiccha** [comment] 2017-02-11 19:02
A HiWi of ours used that behaviour in a parallel gauss prototype. It just saves you of doing one extra if-clause IMO, so I also think it should go.

**Comment by Stefan-Kohl** [comment] 2017-02-11 23:41
In principle, [] * [ [1,2,3] ]; doesn't need to work. -- But what really needs to work is multiplication of an empty list by a square matrix (presently only the case 2x2 is actually used) with integer entries:

```
gap> [] * [ [1,2],[3,4] ];
[  ]
```

-- If that doesn't work, then computation with unions of residue classes of Z^2 is broken.

**Comment by ssiccha** [comment] 2017-02-12 14:12
@Stefan-Kohl Could we reimplement the corresponding parts so that `[] * [ [1,2],[3,4] ];` can again throw an error?

If you would point me to the corresponding lines of ResClasses I would be happy to try and have a go at it.

**Comment by Stefan-Kohl** [comment] 2017-02-12 14:39
As said, making [] * [ [1,2],[3,4] ]; throw an error would break ResClasses.

**Comment by alex-konovalov** [comment] 2017-02-12 17:03
My understanding of this issue, although I am not familiar with ResClasses code, is thatL
* It's hard, if even possible, to define unambiguously what `[] * [ [1,2],[3,4] ]` should do
* It's inconvenient if e.g. someone was *relying* that it will throw an error, and then it works, or vice versa
* The ResClasses manuals says "The elements of ℤ^2 are represented as lists of length 2 with integer entries. The modulus of a residue class union of ℤ^2 is a lattice. This lattice is stored as a 2 × 2 integer matrix of full rank in Hermite normal form, whose rows are the spanning vectors."
* It could be possibly resolved if ResClasses would use a new kind of objects for the lattice and implement multiplication for such objects as required, instead of redefining it for existing objects.

Unfortunately, there is no public repository for ResClasses, so one can not submit a pull request to  @Stefan-Kohl.

**Comment by Stefan-Kohl** [comment] 2017-02-12 18:55
@alex-konovalov:Your last point is plainly wrong. -- Anyway things turned out to be easier than I initially thought (only one method needed adjustments), since I had implemented some internals a bit better than I remembered. In the next version of ResClasses,  [] * [ [1,2],[3,4] ] won't be defined any more.
Anyway -- what concerns pull requests: properly making such changes requires taking a closer look at the implementation.

**Comment by fingolfin** [comment] 2017-02-12 19:07
@Stefan-Kohl Thank you for looking into it and making that change! Looking forwad to the next ResClasses release then :-).

**Comment by Stefan-Kohl** [comment] 2017-02-13 21:38
@fingolfin: Since RCWA had enough changes since the last release in May 2016, I made the next release now -- as usual, together with ResClasses. As you know, the PackageInfo.g URL's have changed -- as there is forwarding set up, will this be picked up automatically?

**Comment by alex-konovalov** [comment] 2017-02-13 22:04
Thank you - both of them were picked up this morning, you can see their new versions in the table at https://github.com/gap-system/gap/wiki/Package-updates-status (the Trello board for package updates is not supported any more).

Looking at RCWA tests, I've discovered that they are currently broken in the master branch:
```
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packages/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/pkg/rcwa-4.4.1/tst/database.tst:23
# Input is:
LoadDatabaseOfGroupsGeneratedBy3ClassTranspositions(6);
# Expected output:
"3CTsGroups6"
# But found:
Error, Variable: '~' must have an assigned value
########
```
Could that be related with #1050?

**Comment by Stefan-Kohl** [comment] 2017-02-13 22:58
Quite possibly. -- Though I don't see on a first glance what #1050 really is about exactly.

**Comment by alex-konovalov** [comment] 2017-02-13 23:12
@Stefan-Kohl it fixed #1049, and since `~` appears in the error message, that looks like a clue.

**Comment by Stefan-Kohl** [comment] 2017-02-13 23:20
The tilde always worked this way, and now it is broken. -- How to proceed with this?

**Comment by ChrisJefferson** [comment] 2017-02-13 23:23
@Stefan-Kohl : I'm going to look into it. I may well have broken the tilde, in which case I will fix it -- In the standard library and standard tests there aren't really any interesting examples of the use of `~`, and it isn't that well documented in the manual.

I'm having some trouble making this test quickly -- `testall.g` takes a long time on my machine! If anyone has any short examples, that would be helpful.

**Comment by alex-konovalov** [comment] 2017-02-13 23:25
It could probably help if we can have a smaller example. At the moment you read as function `/data/3ctsgroups6/database.g` and that file has almost 6000 lines.

**Comment by ChrisJefferson** [comment] 2017-02-13 23:26
Looking at just the bad line,

```LoadPackage("rcwa"); LoadDatabaseOfGroupsGeneratedBy3ClassTranspositions(6);;``` seems to work fine, so that's not enough to cause a problem. Or I've not got things set up right.

**Comment by Stefan-Kohl** [comment] 2017-02-13 23:48
Strange ... . -- At which line in database.g does the error occur?

**Comment by alex-konovalov** [comment] 2017-02-13 23:50
@Stefan-Kohl I've posted partial output at https://github.com/Stefan-Kohl/stefan-kohl.github.io/issues/3 - line 6908 but that does not help.

**Comment by Stefan-Kohl** [comment] 2017-02-14 00:04
Hmm -- no idea ... .

**Comment by ChrisJefferson** [comment] 2017-02-14 08:56
@Stefan-Kohl : Which GAP version do you use for development? I want to compare master, with a version where rcwa is known to work.

**Comment by Stefan-Kohl** [comment] 2017-02-14 13:49
I am presently using GAP 4.8.5 of 25-Sep-2016 (didn't update to 4.8.6 so far since there didn't seem to be much changes of interest to me).

**Comment by alex-konovalov** [comment] 2017-02-21 12:33
This may be closed:
- New version of ResClasses picked up and should appear in the next release.
- The problem with `LoadDatabaseOfGroupsGeneratedBy3ClassTranspositions ` in RCWA fixed in https://github.com/gap-system/gap/pull/1151

**Closed by alex-konovalov** 2017-02-21 12:33 UTC
