### ISSUE TITLE
Recursion depth trap when repeatedly calling `Test`

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#1752] opened 2017-09-29 12:39 UTC
### Observed behaviour
If the contents of the test file `bug.tst` is:

    gap> START_TEST("bug.tst");
    gap> IsAbelian("A");
    Error, no method found! For debugging hints type ?Recovery from NoMethodFound
    Error, no 1st choice method found for `IsCommutative' on 1 arguments
    gap> STOP_TEST("bug.tst");

and I load GAP without any packages `gap -A`, then do 

        i := 0;; repeat i := i + 1; until not Test("bug.tst");

then when `i` is `1665`

    ########> Diff in bug.tst:2
    # Input is:
    IsAbelian("A");
    # Expected output:
    Error, no method found! For debugging hints type ?Recovery from NoMethodFound
    Error, no 1st choice method found for `IsCommutative' on 1 arguments
    # But found:
    Error, no method found! For debugging hints type ?Recovery from NoMethodFound
    Error, recursion depth trap (5000)

This is a minimal example of the problem, but this is causing some of the Semigroups package continuous integration test to fail, see [the discussion here](https://github.com/gap-packages/Semigroups/pull/347) for more details. This bug is confirm by several others, not only me, so unlikely to be an issue with my setup. 

### Expected behaviour

The loop to run forever. 

### Copy and paste GAP banner (to tell us about your setup)

     ┌───────┐   GAP 4.8.7-4353-ga179f09 of today
     │  GAP  │   https://www.gap-system.org
     └───────┘   Architecture: x86_64-apple-darwin16.6.0-clang-default64
     Configuration:  gmp 6.1.1
     Loading the library and packages ...
     Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
     Packages:   GAPDoc 1.5.1
     Try '??help' for help. See also '?copyright', '?cite' and '?authors'
    gap>

**Comment by ChrisJefferson** [comment] 2017-09-29 12:43
I suspect the problem is we don't reset the depth of the stack when we longjmp.

**Comment by james-d-mitchell** [comment] 2017-09-29 12:46
It seems to be a bit unpredictable.

**Comment by ChrisJefferson** [comment] 2017-09-29 12:47
It will be (I suspect) connected to the number of tests which exit via an error.

**Comment by wilfwilson** [comment] 2017-09-29 12:50
Yes. In our continuous integration, it was always one of the last files to be tested that was having problems.

**Comment by ChrisJefferson** [comment] 2017-09-29 12:53
Ah, just checking, is this only on 4.8? I have a feeling I fixed something related to this in master (and the error doesn't seem to trigger in master for me)

**Comment by wilfwilson** [comment] 2017-09-29 12:54
We only test with master at the moment, so I don't know anything about whether it's present in stable-4.8.

**Comment by ChrisJefferson** [comment] 2017-09-29 12:55
Ah, no, I can reproduce it, it just takes a while.

If I add a way of printing out GAP's `RecursionDepth`, then I can see it increases by 3 each time we run the test, so eventually we overflow.

**Comment by ChrisJefferson** [comment] 2017-09-29 12:59
Fix coming up.

**Comment by james-d-mitchell** [comment] 2017-09-29 13:00
Awesome @ChrisJefferson, thanks

**Comment by ChrisJefferson** [comment] 2017-09-29 13:24
This is (hopefully) fixed by #1753.

**Comment by markuspf** [comment] 2017-10-02 12:14
Fixed by #1753

**Closed by markuspf** 2017-10-02 12:14 UTC
Labels: bug
